"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

import argparse
from typing import Any

from museoncli.domains._model import (
    ROUTINES_DOMAIN,
    AdapterType,
    CommandSpec,
    Domain,
    ExecutionMode,
    RiskLevel,
)
from museoncli.domains._shared import (
    _spec_schema_payload,
    _spec_summary_payload,
)
from museoncli.domains.routines import ROUTINE_INSTRUCTION_MAX_LENGTH
from museoncli.domains import (
    research,
    content_analysis,
    asset,
    artifacts,
    generation,
    social_account,
    campaign_monitor,
    social_media,
    skills,
    evaluator,
    routines,
    account_operation,
)


_DOMAIN_MODULES = (
    research,
    content_analysis,
    asset,
    artifacts,
    generation,
    social_account,
    campaign_monitor,
    social_media,
    skills,
    evaluator,
    routines,
    account_operation,
)


def command_specs() -> list[CommandSpec]:
    specs: list[CommandSpec] = []
    for module in _DOMAIN_MODULES:
        specs.extend(module.specs())
    return specs


def command_executors() -> "dict[str, Any]":
    merged: dict[str, Any] = {}
    for module in _DOMAIN_MODULES:
        merged.update(getattr(module, "EXECUTORS", {}))
    return merged


def command_executor(schema_name: str):
    executor = command_executors().get(schema_name)
    if executor is None:
        raise RuntimeError(f"no executor registered for {schema_name}")
    return executor


def fixed_domain_values() -> list[str]:
    return [*specs_by_domain()]


def specs_by_domain() -> dict[str, list[CommandSpec]]:
    grouped: dict[str, list[CommandSpec]] = {}
    for spec in command_specs():
        grouped.setdefault(spec.domain.value, []).append(spec)
    return grouped


def get_command_spec(schema_name: str) -> CommandSpec:
    normalized = schema_name.replace(".+", ".")
    for spec in command_specs():
        if spec.schema_name == normalized:
            return spec
    raise ValueError(f"Unknown command schema: {schema_name}")


def add_domain_command_parsers(
    subparsers: argparse._SubParsersAction[argparse.ArgumentParser],
) -> None:
    for domain, specs in specs_by_domain().items():
        if not specs:
            continue
        domain_parser = subparsers.add_parser(domain)
        shortcut_subparsers = domain_parser.add_subparsers(dest="shortcut", required=True)
        for spec in specs:
            shortcut_parser = shortcut_subparsers.add_parser(spec.shortcut)
            spec.add_arguments(shortcut_parser)
            shortcut_parser.set_defaults(domain_command=spec.schema_name)


def schema_payload(schema_name: str | None = None) -> dict[str, Any]:
    if schema_name:
        normalized = schema_name.replace(".+", ".")
        domain_specs = specs_by_domain().get(normalized)
        if domain_specs is not None:
            return _domain_schema_payload(normalized, domain_specs)
        return _spec_schema_payload(get_command_spec(schema_name))
    commands = {
        domain: [_spec_summary_payload(spec) for spec in specs]
        for domain, specs in specs_by_domain().items()
    }
    return {
        "domains": fixed_domain_values(),
        "commands": commands,
    }


def _domain_schema_payload(domain: str, specs: list[CommandSpec]) -> dict[str, Any]:
    return {
        "domain": domain,
        "commands": [_spec_summary_payload(spec) for spec in specs],
    }


def command_payload(args: argparse.Namespace) -> dict[str, Any]:
    return get_command_spec(args.domain_command).build_arguments(args)


__all__ = [
    "command_executor",
    "command_executors",
    "ROUTINES_DOMAIN",
    "AdapterType",
    "CommandSpec",
    "Domain",
    "ExecutionMode",
    "RiskLevel",
    "ROUTINE_INSTRUCTION_MAX_LENGTH",
    "add_domain_command_parsers",
    "command_payload",
    "command_specs",
    "fixed_domain_values",
    "get_command_spec",
    "schema_payload",
    "specs_by_domain",
]
