"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

import argparse
from typing import Any

from museoncli.domains._model import (
    ROUTINES_DOMAIN,
    AdapterType,
    CommandSpec,
    Domain,
    ExecutionMode,
    RiskLevel,
    Stability,
    Transport,
)
from museoncli.domains._shared import (
    _spec_schema_payload,
    _spec_summary_payload,
)
from museoncli.domains.routines import ROUTINE_INSTRUCTION_MAX_LENGTH
from museoncli.domains import (
    research,
    content_analysis,
    asset,
    artifacts,
    generation,
    social_account,
    account_publish,
    campaign_monitor,
    social_media,
    skills,
    evaluator,
    routines,
    account_operation,
    agentic_campaign,
    product,
)


_DOMAIN_MODULES = (
    research,
    content_analysis,
    asset,
    artifacts,
    generation,
    social_account,
    account_publish,
    campaign_monitor,
    social_media,
    skills,
    evaluator,
    routines,
    account_operation,
    agentic_campaign,
    product,
)


def command_specs() -> list[CommandSpec]:
    specs: list[CommandSpec] = []
    for module in _DOMAIN_MODULES:
        specs.extend(module.specs())
    return specs


def discoverable_command_specs() -> list[CommandSpec]:
    return [spec for spec in command_specs() if spec.discoverable]


def command_executors() -> "dict[str, Any]":
    merged: dict[str, Any] = {}
    for module in _DOMAIN_MODULES:
        merged.update(getattr(module, "EXECUTORS", {}))
    return merged


def command_executor(schema_name: str):
    executor = command_executors().get(schema_name)
    if executor is None:
        raise RuntimeError(f"no executor registered for {schema_name}")
    return executor


def fixed_domain_values() -> list[str]:
    return [*specs_by_domain()]


def specs_by_domain() -> dict[str, list[CommandSpec]]:
    grouped: dict[str, list[CommandSpec]] = {}
    for spec in command_specs():
        grouped.setdefault(spec.domain.value, []).append(spec)
    return grouped


def get_command_spec(schema_name: str) -> CommandSpec:
    normalized = schema_name.replace(".+", ".")
    for spec in command_specs():
        if spec.schema_name == normalized:
            return spec
    raise ValueError(f"Unknown command schema: {schema_name}")


def add_domain_command_parsers(
    subparsers: argparse._SubParsersAction[argparse.ArgumentParser],
) -> None:
    for domain, specs in specs_by_domain().items():
        if not specs:
            continue
        domain_parser = subparsers.add_parser(domain)
        shortcut_subparsers = domain_parser.add_subparsers(dest="shortcut", required=True)

        def add_command_parser(
            parser: argparse._SubParsersAction[argparse.ArgumentParser],
            spec: CommandSpec,
            shortcut: str,
            *,
            hidden: bool = False,
        ) -> None:
            examples = "\n".join(f"  {example}" for example in spec.examples)
            shortcut_parser = parser.add_parser(
                shortcut,
                help=argparse.SUPPRESS if hidden else None,
                description=spec.summary,
                epilog=f"Examples:\n{examples}" if examples else None,
                formatter_class=argparse.RawDescriptionHelpFormatter,
            )
            spec.add_arguments(shortcut_parser)
            shortcut_parser.set_defaults(domain_command=spec.schema_name)

        resource_specs: dict[str, list[CommandSpec]] = {}
        for spec in specs:
            if spec.resource is None:
                add_command_parser(shortcut_subparsers, spec, spec.shortcut)
                continue
            resource_specs.setdefault(spec.resource, []).append(spec)
            for legacy_shortcut in spec.legacy_shortcuts:
                add_command_parser(shortcut_subparsers, spec, legacy_shortcut, hidden=True)

        for resource, grouped_specs in resource_specs.items():
            resource_parser = shortcut_subparsers.add_parser(resource)
            action_subparsers = resource_parser.add_subparsers(dest="resource_action", required=True)
            for spec in grouped_specs:
                add_command_parser(action_subparsers, spec, spec.shortcut)


def schema_payload(schema_name: str | None = None) -> dict[str, Any]:
    if schema_name:
        normalized = schema_name.replace(".+", ".")
        domain_specs = specs_by_domain().get(normalized)
        if domain_specs is not None:
            return _domain_schema_payload(normalized, domain_specs)
        return _spec_schema_payload(get_command_spec(schema_name))
    commands = {}
    for domain, specs in specs_by_domain().items():
        visible = [spec for spec in specs if spec.discoverable]
        if visible:
            commands[domain] = [_spec_summary_payload(spec) for spec in visible]
    return {
        "domains": fixed_domain_values(),
        "commands": commands,
    }


def _domain_schema_payload(domain: str, specs: list[CommandSpec]) -> dict[str, Any]:
    return {
        "domain": domain,
        "commands": [_spec_summary_payload(spec) for spec in specs if spec.discoverable],
    }


def command_payload(args: argparse.Namespace) -> dict[str, Any]:
    return get_command_spec(args.domain_command).build_arguments(args)


__all__ = [
    "command_executor",
    "command_executors",
    "ROUTINES_DOMAIN",
    "AdapterType",
    "CommandSpec",
    "Domain",
    "ExecutionMode",
    "RiskLevel",
    "Stability",
    "Transport",
    "ROUTINE_INSTRUCTION_MAX_LENGTH",
    "add_domain_command_parsers",
    "command_payload",
    "command_specs",
    "discoverable_command_specs",
    "fixed_domain_values",
    "get_command_spec",
    "schema_payload",
    "specs_by_domain",
]
