"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

import argparse
from collections.abc import Callable
from dataclasses import dataclass
from enum import Enum
from typing import Any, Literal


RiskLevel = Literal["read", "write", "destructive"]


ExecutionMode = Literal["direct", "async_run"]


AdapterType = Literal[
    "internal_tool",
    "run_status",
]


ROUTINES_DOMAIN = "routines"


class Domain(str, Enum):
    RESEARCH = "research"
    CONTENT_ANALYSIS = "content-analysis"
    ASSET = "asset"
    ARTIFACTS = "artifacts"
    GENERATION = "generation"
    SOCIAL_ACCOUNT = "social-account"
    CAMPAIGN_MONITOR = "campaign-monitor"
    SKILLS = "skills"
    EVALUATOR = "evaluator"
    ROUTINES = ROUTINES_DOMAIN
    ACCOUNT_OPERATION = "account-operation"


@dataclass(frozen=True, slots=True)
class CommandSpec:
    domain: Domain
    shortcut: str
    summary: str
    risk_level: RiskLevel
    execution: ExecutionMode
    adapter_tool_name: str
    input_schema: dict[str, Any]
    output_schema: dict[str, Any]
    examples: list[str]
    add_arguments: Callable[[argparse.ArgumentParser], None]
    build_arguments: Callable[[argparse.Namespace], dict[str, Any]]
    adapter_type: AdapterType = "internal_tool"
    supports_dry_run: bool = False
    requires_confirmation: bool = False

    @property
    def schema_name(self) -> str:
        return f"{self.domain.value}.{self.shortcut.removeprefix('+')}"
