"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any
from museoncli.domains._model import CommandSpec


def _frontend_url_template(
    label: str,
    path_template: str,
    *,
    description: str,
    required_fields: list[str] | None = None,
    applies_when: dict[str, str] | None = None,
    requires_auth: bool = True,
) -> dict[str, Any]:
    return {
        "label": label,
        "path_template": path_template,
        "url_template": f"{{frontend_origin}}{path_template}",
        "description": description,
        "required_fields": required_fields or [],
        "applies_when": applies_when or {},
        "requires_auth": requires_auth,
    }


_ASSET_FRONTEND_URL_TEMPLATES = [
    _frontend_url_template(
        "Product detail",
        "/assets/products/{id}",
        description="Open a product resource returned by asset commands.",
        required_fields=["id"],
        applies_when={"type": "product"},
    ),
    _frontend_url_template(
        "Persona detail",
        "/assets/personas/{id}",
        description="Open a persona resource returned by asset commands.",
        required_fields=["id"],
        applies_when={"type": "persona"},
    ),
    _frontend_url_template(
        "Topic detail",
        "/assets/topics/{id}",
        description="Open a content topic resource returned by asset commands.",
        required_fields=["id"],
        applies_when={"type": "topic"},
    ),
    _frontend_url_template(
        "Topic directions",
        "/assets/topics",
        description="Open the topics page that manages topic directions and topics.",
        applies_when={"type": "topic_direction"},
    ),
    _frontend_url_template(
        "Format detail",
        "/assets/formats/{id}",
        description="Open a slideshow format resource returned by asset commands.",
        required_fields=["id"],
        applies_when={"type": "format"},
    ),
    _frontend_url_template(
        "Media gallery",
        "/gallery",
        description="Open the media gallery for uploaded and generated media assets.",
        applies_when={"type": "media"},
    ),
]


_ARTIFACT_FRONTEND_URL_TEMPLATES = [
    _frontend_url_template(
        "Artifacts",
        "/artifacts",
        description="Open the artifact library.",
    ),
    _frontend_url_template(
        "Artifact detail",
        "/artifacts/{artifact_id}",
        description="Open one uploaded artifact after the response returns artifact_id.",
        required_fields=["artifact_id"],
    ),
]


_CONTENT_ANALYSIS_FRONTEND_URL_TEMPLATES = [
    _frontend_url_template(
        "Content Analyzer",
        "/content-analyzer",
        description="Open the Content Analyzer workspace page.",
    ),
    _frontend_url_template(
        "Content Analyzer history",
        "/content-analyzer/history",
        description="Open prior Content Analyzer runs.",
    ),
    _frontend_url_template(
        "Content Analyzer result",
        "/content-analyzer/result/{run_id}",
        description="Open one Content Analyzer run result.",
        required_fields=["run_id"],
    ),
]


_GENERATION_FRONTEND_URL_TEMPLATES = [
    _frontend_url_template(
        "Slideshow generation preview",
        "/generations/{generation_id}",
        description="Open the public generation detail route.",
        required_fields=["generation_id"],
        requires_auth=False,
    ),
    _frontend_url_template(
        "Format detail",
        "/slideshow-formats/{format_id}",
        description="Open the source format tied to a slideshow generation.",
        required_fields=["format_id"],
    ),
]


_SOCIAL_ACCOUNT_CONNECT_LINK_FRONTEND_URL_TEMPLATES = [
    _frontend_url_template(
        "Social accounts",
        "/social-accounts",
        description="Open the workspace page for connected social accounts.",
    ),
]


_SOCIAL_ACCOUNT_FRONTEND_URL_TEMPLATES = [
    _frontend_url_template(
        "Social accounts",
        "/social-accounts",
        description="Open the social accounts workspace.",
    ),
    _frontend_url_template(
        "Pool account performance",
        "/social-accounts/pool-accounts/{account_id}/performance",
        description="Open one pool account performance page.",
        required_fields=["account_id"],
    ),
    _frontend_url_template(
        "Account publish calendar",
        "/social-accounts/calendar",
        description="Open the account publish calendar.",
    ),
]


_SOCIAL_MEDIA_CREATOR_FRONTEND_URL_TEMPLATES = [
    _frontend_url_template(
        "Campaign creators",
        "/campaigns/creators",
        description="Open the global campaign creators page.",
    ),
]


_SOCIAL_MEDIA_POST_FRONTEND_URL_TEMPLATES = [
    _frontend_url_template(
        "Posts",
        "/posts",
        description="Open the workspace posts page.",
    ),
    _frontend_url_template(
        "Post detail",
        "/posts/{content_id}",
        description="Open one synced social post/content record.",
        required_fields=["content_id"],
    ),
]


_CAMPAIGN_FRONTEND_URL_TEMPLATES = [
    _frontend_url_template(
        "Campaigns",
        "/campaigns",
        description="Open the campaign monitor list.",
    ),
    _frontend_url_template(
        "Campaign creators",
        "/campaigns/{campaign_id}/creators",
        description="Open creators covered by one campaign monitor.",
        required_fields=["campaign_id"],
    ),
    _frontend_url_template(
        "Campaign contents",
        "/campaigns/{campaign_id}/contents",
        description="Open posts/content covered by one campaign monitor.",
        required_fields=["campaign_id"],
    ),
    _frontend_url_template(
        "Campaign analytics",
        "/campaigns/{campaign_id}/analytics",
        description="Open the campaign performance analytics page.",
        required_fields=["campaign_id"],
    ),
]


_ROUTINE_FRONTEND_URL_TEMPLATES = [
    _frontend_url_template(
        "Routines",
        "/routines",
        description="Open the routine list.",
    ),
    _frontend_url_template(
        "Routine detail",
        "/routines?routine_id={routine_id}",
        description="Open one routine when a routine_id is available.",
        required_fields=["routine_id"],
    ),
]


def _add_common_adapter_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--workspace-id")
    parser.add_argument("--args-json")
    parser.add_argument("--args-file")


def _load_structured_args(args: argparse.Namespace) -> dict[str, Any]:
    if getattr(args, "args_file", None):
        value = Path(args.args_file).read_text(encoding="utf-8")
        return _json_object(value, flag="--args-file")
    if getattr(args, "args_json", None):
        return _json_object(args.args_json, flag="--args-json")
    return {}


def _json_object(value: str, *, flag: str) -> dict[str, Any]:
    try:
        parsed = json.loads(value)
    except ValueError as exc:
        raise ValueError(f"{flag} must be valid JSON.") from exc
    if not isinstance(parsed, dict):
        raise ValueError(f"{flag} must be a JSON object.")
    return dict(parsed)


def _json_list(value: str, *, flag: str) -> list[Any]:
    try:
        parsed = json.loads(value)
    except ValueError as exc:
        raise ValueError(f"{flag} must be valid JSON.") from exc
    if not isinstance(parsed, list):
        raise ValueError(f"{flag} must be a JSON array.")
    return list(parsed)


def _ordered_strings(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    output: list[str] = []
    seen: set[str] = set()
    for item in value:
        text = str(item).strip() if item is not None else ""
        if text and text not in seen:
            output.append(text)
            seen.add(text)
    return output


def _without_none(payload: dict[str, Any]) -> dict[str, Any]:
    return {key: value for key, value in payload.items() if value is not None}


def _spec_summary_payload(spec: CommandSpec) -> dict[str, Any]:
    payload = {
        "name": spec.schema_name,
        "domain": spec.domain.value,
        "shortcut": spec.shortcut,
        "summary": spec.summary,
        "risk_level": spec.risk_level,
        "execution": spec.execution,
        "supports_dry_run": spec.supports_dry_run,
        "requires_confirmation": spec.requires_confirmation,
    }
    frontend_url_templates = _frontend_url_templates_for_spec(spec)
    if frontend_url_templates:
        payload["frontend_url_templates"] = frontend_url_templates
    return payload


def _spec_schema_payload(spec: CommandSpec) -> dict[str, Any]:
    return {
        **_spec_summary_payload(spec),
        "input_schema": spec.input_schema,
        "output_schema": spec.output_schema,
        "supports_dry_run": spec.supports_dry_run,
        "requires_confirmation": spec.requires_confirmation,
        "examples": spec.examples,
    }


def _frontend_url_templates_for_spec(spec: CommandSpec) -> list[dict[str, Any]]:
    schema_name = spec.schema_name
    if schema_name.startswith("asset."):
        return [dict(template) for template in _ASSET_FRONTEND_URL_TEMPLATES]
    if schema_name.startswith("artifacts."):
        return [dict(template) for template in _ARTIFACT_FRONTEND_URL_TEMPLATES]
    if schema_name.startswith("content-analysis."):
        return [dict(template) for template in _CONTENT_ANALYSIS_FRONTEND_URL_TEMPLATES]
    if schema_name.startswith("generation."):
        return [dict(template) for template in _GENERATION_FRONTEND_URL_TEMPLATES]
    if schema_name.startswith("social-account.connect-link"):
        return [dict(template) for template in _SOCIAL_ACCOUNT_CONNECT_LINK_FRONTEND_URL_TEMPLATES]
    if schema_name.startswith("social-account."):
        return [dict(template) for template in _SOCIAL_ACCOUNT_FRONTEND_URL_TEMPLATES]
    if schema_name.startswith("campaign-monitor.creator-get"):
        return [dict(template) for template in _SOCIAL_MEDIA_CREATOR_FRONTEND_URL_TEMPLATES]
    if schema_name.startswith("campaign-monitor.post"):
        return [dict(template) for template in _SOCIAL_MEDIA_POST_FRONTEND_URL_TEMPLATES]
    if schema_name.startswith("campaign-monitor."):
        return [dict(template) for template in _CAMPAIGN_FRONTEND_URL_TEMPLATES]
    if schema_name.startswith("routines."):
        return [dict(template) for template in _ROUTINE_FRONTEND_URL_TEMPLATES]
    return []


def _direct_output_schema(description: str) -> dict[str, Any]:
    return {
        "type": "object",
        "description": description,
        "properties": {
            "ok": {"type": "boolean"},
            "command": {"type": "string"},
            "workspace": {"type": ["object", "null"]},
            "data": {"type": ["object", "array", "string", "number", "boolean", "null"]},
            "run": {"type": ["object", "null"]},
            "warnings": {"type": "array", "items": {"type": "string"}},
            "next_steps": {"type": "array", "items": {"type": "string"}},
        },
        "required": ["ok", "command", "data", "run", "warnings", "next_steps"],
    }


def _async_output_schema(
    description: str,
    *,
    include_generation_guidance: bool = False,
) -> dict[str, Any]:
    schema = _direct_output_schema(description)
    run_properties: dict[str, Any] = {
        "id": {"type": "string"},
        "type": {"type": "string"},
        "status": {"type": "string"},
        "watch_command": {"type": ["string", "null"]},
    }
    if include_generation_guidance:
        run_properties.update(
            {
                "ref": {
                    "type": ["string", "null"],
                    "description": (
                        "Customer-facing generation progress link. Include it in the current "
                        "final response while generation is still running."
                    ),
                },
                "recommended_wakeup_delay_seconds": {
                    "type": "integer",
                    "minimum": 1,
                    "description": "Recommended delay before the next generation status check.",
                },
            }
        )
    schema["properties"]["run"] = {
        "type": "object",
        "properties": run_properties,
        "required": ["id", "status"],
    }
    return schema


_UUID_ID_DESCRIPTION = (
    "Canonical UUID copied from a previous command response. Never pass "
    "placeholders ('?', 'TBD') or descriptive text; look the ID up first "
    "with the matching +list/+get command."
)


def _uuid_id_schema(extra: str = "") -> dict[str, Any]:
    description = f"{_UUID_ID_DESCRIPTION} {extra}".strip()
    return {"type": "string", "format": "uuid", "description": description}


def kebab_choices(values: list[str]) -> list[str]:
    """CLI flag enum values are kebab-case; server contract values stay snake_case."""
    return [value.replace("_", "-") for value in values]


def dekebab(value: str | None) -> str | None:
    return value.replace("-", "_") if isinstance(value, str) else value
