"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

from museoncli.domains._shared import dekebab

from museoncli.execution import compact_params, read_json_option

from museoncli.execution import (
    CommandContext,
    direct_enveloped,
)

import argparse
from typing import Any
from museoncli.domains._model import CommandSpec, Domain
from museoncli.domains._shared import _direct_output_schema


def _add_account_operation_submit_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--pool-account-id", required=True)
    parser.add_argument("--organization-id", required=True)
    parser.add_argument(
        "--product-id",
        default=None,
        help=(
            "Optional workspace Product/CTA context: product truth, description/media, and "
            "promotion guidance; an explicit audience action is optional. Re-submitting the "
            "same Product is idempotent; changing it is rejected."
        ),
    )
    parser.add_argument("--niche", default=None)
    parser.add_argument("--persona-id", default=None)
    parser.add_argument(
        "--session-conversation-id",
        default=None,
        help=(
            "Work-session conversation (topic/thread) to bind as the account's "
            "workbench; defaults to the CURRENT session from the per-turn runtime context."
        ),
    )
    parser.add_argument("--target-delivery-mode", default=None)
    parser.add_argument(
        "--research-prompt",
        default=None,
        help=(
            "Operator's research directive (free text; may include benchmark accounts). "
            "ONLY pass when the operator explicitly mentioned research direction — "
            "forces research even for established accounts."
        ),
    )
    parser.add_argument(
        "--reference-url",
        default=None,
        help=(
            "Benchmark account URL the operator named for research anchoring. "
            "ONLY pass when explicitly mentioned."
        ),
    )
    parser.add_argument(
        "--preferred-publish-time",
        default=None,
        help=(
            "Preferred daily publish time as 24h HH:MM (e.g. 17:00). Stored on the "
            "operation; the daily routine then schedules posts at this local time. "
            "Pair with --publish-timezone."
        ),
    )
    parser.add_argument(
        "--publish-timezone",
        default=None,
        help="IANA timezone for --preferred-publish-time (e.g. Asia/Shanghai).",
    )
    parser.add_argument("--dry-run", action="store_true")


def _build_account_operation_submit_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "pool_account_id": args.pool_account_id,
        "organization_id": args.organization_id,
        "product_id": args.product_id,
        "niche": args.niche,
        "persona_id": args.persona_id,
        "session_conversation_id": args.session_conversation_id,
        "target_delivery_mode": args.target_delivery_mode,
        "research_prompt": args.research_prompt,
        "reference_url": args.reference_url,
        "preferred_publish_time": args.preferred_publish_time,
        "preferred_publish_timezone": args.publish_timezone,
    }


def _add_account_operation_submit_batch_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--pool-account-ids",
        required=True,
        help="Comma-separated pool account ids (one shared session/campaign).",
    )
    parser.add_argument("--organization-id", required=True)
    parser.add_argument(
        "--product-id",
        default=None,
        help=(
            "Optional shared workspace Product/CTA context for the entire batch. One batch "
            "has at most one Product; per-account overrides are not supported."
        ),
    )
    parser.add_argument("--niche", default=None, help="Shared niche default for all accounts.")
    parser.add_argument("--session-conversation-id", default=None)
    parser.add_argument("--target-delivery-mode", default=None)
    parser.add_argument(
        "--research-prompt",
        default=None,
        help="Shared research directive. ONLY when the operator explicitly mentioned it.",
    )
    parser.add_argument(
        "--reference-url",
        default=None,
        help="Shared benchmark account URL. ONLY when explicitly mentioned.",
    )
    parser.add_argument(
        "--preferred-publish-time",
        default=None,
        help=(
            "Shared preferred daily publish time (24h HH:MM, e.g. 17:00) applied to "
            "every account in the batch. Pair with --publish-timezone."
        ),
    )
    parser.add_argument(
        "--publish-timezone",
        default=None,
        help="Shared IANA timezone for --preferred-publish-time (e.g. Asia/Shanghai).",
    )
    parser.add_argument("--dry-run", action="store_true")


def _build_account_operation_submit_batch_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "pool_account_ids": args.pool_account_ids,
        "organization_id": args.organization_id,
        "product_id": args.product_id,
        "niche": args.niche,
        "session_conversation_id": args.session_conversation_id,
        "target_delivery_mode": args.target_delivery_mode,
        "research_prompt": args.research_prompt,
        "reference_url": args.reference_url,
        "preferred_publish_time": args.preferred_publish_time,
        "preferred_publish_timezone": args.publish_timezone,
    }


def _add_account_operation_id_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--id", dest="operation_id", required=True)


def _build_account_operation_id_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {"operation_id": args.operation_id}


def _add_account_operation_list_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--page", type=int, default=1)
    parser.add_argument("--page-size", type=int, default=50)


def _add_account_operation_id_limit_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--id", dest="operation_id", required=True)
    parser.add_argument("--limit", type=int, default=10)


def _build_account_operation_id_limit_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {"operation_id": args.operation_id, "limit": args.limit}


def _build_account_operation_list_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {"page": args.page, "page_size": args.page_size}


def _add_account_operation_ops_status_arguments(parser: argparse.ArgumentParser) -> None:
    # Workspace comes from the global --workspace-id / selected workspace
    # (ctx.workspace_id), like +list. --window scopes ONLY failed_reasons.
    parser.add_argument(
        "--window",
        choices=["24h", "7d"],
        default=None,
        help="failed_reasons clustering window (default 24h; all other stats stay 24h).",
    )


def _build_account_operation_ops_status_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {"window": args.window}


def _add_account_operation_daily_roster_arguments(parser: argparse.ArgumentParser) -> None:
    # Workspace comes from the global --workspace-id / selected workspace.
    parser.add_argument(
        "--date",
        default=None,
        help="Local calendar day YYYY-MM-DD (default: today in --tz).",
    )
    parser.add_argument(
        "--tz",
        dest="timezone",
        default=None,
        help="IANA timezone for --date and the day window, e.g. Asia/Shanghai (default UTC).",
    )
    parser.add_argument(
        "--managed",
        choices=["all", "full", "semi"],
        default=None,
        help="Management-mode filter: all (default) | full (全托管) | semi (半托管).",
    )
    parser.add_argument(
        "--success",
        choices=["any", "all"],
        default=None,
        help="published_ok basis: any (>=1 item published, default) | all (every live item published).",
    )
    parser.add_argument(
        "--as-of",
        dest="as_of",
        default=None,
        help=(
            "Intra-day cutoff HH:MM (local, on --date/--tz), e.g. 18:00. Adds per-account "
            "cutoff {due, published, unpublished} and enables --filter behind."
        ),
    )
    parser.add_argument(
        "--filter",
        dest="result_filter",
        choices=["all", "unscheduled", "failed", "no-publish", "behind"],
        default=None,
        help="Narrow returned rows (summary always covers the whole cohort). Default all. "
        "'behind' needs --as-of.",
    )
    parser.add_argument("--page", type=int, default=1)
    parser.add_argument("--page-size", type=int, default=200)


def _build_account_operation_daily_roster_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "date": args.date,
        "timezone": args.timezone,
        "managed": args.managed,
        "success": args.success,
        "as_of": args.as_of,
        "result_filter": dekebab(args.result_filter),
        "page": args.page,
        "page_size": args.page_size,
    }


def _add_account_operation_plan_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--id", dest="operation_id", required=True)
    parser.add_argument("--format-ids", default=None, help="Comma-separated format ids.")
    parser.add_argument("--topic-ids", default=None, help="Comma-separated content topic ids.")
    parser.add_argument(
        "--required-hashtags",
        default=None,
        help=(
            "Comma-separated account-wide required hashtags. Pass an empty string to clear them."
        ),
    )
    parser.add_argument("--note", default=None)
    parser.add_argument("--dry-run", action="store_true")


def _csv_id_list(value: str | None) -> list[str] | None:
    if value is None:
        return None
    return [part.strip() for part in str(value).split(",") if part.strip()]


def _build_account_operation_plan_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = {
        "operation_id": args.operation_id,
        "format_ids": _csv_id_list(args.format_ids),
        "topic_ids": _csv_id_list(args.topic_ids),
        "note": args.note,
    }
    if args.required_hashtags is not None:
        payload["required_hashtags"] = _csv_id_list(args.required_hashtags)
    return payload


def _add_account_operation_persona_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--id", dest="operation_id", required=True)
    parser.add_argument("--name", required=True, help="Persona name (人设名).")
    parser.add_argument(
        "--description",
        default=None,
        help="Persona voice/audience/positioning summary.",
    )
    parser.add_argument("--tags", default=None, help="Comma-separated style/audience tags.")
    parser.add_argument("--dry-run", action="store_true")


def _build_account_operation_persona_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "operation_id": args.operation_id,
        "name": args.name,
        "description": args.description,
        "tags": _csv_id_list(args.tags),
    }


def _add_account_operation_decide_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--id", dest="operation_id", required=True)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--decided-by", required=True, choices=["human", "auto-timeout"])
    parser.add_argument("--decision-json", default=None, help="Optional decision JSON object.")
    parser.add_argument("--dry-run", action="store_true")


def _build_account_operation_decide_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "operation_id": args.operation_id,
        "run_id": args.run_id,
        "decided_by": dekebab(args.decided_by),
        "decision_json": args.decision_json,
    }


def _add_account_operation_stop_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--id", dest="operation_id", required=True)
    parser.add_argument(
        "--reason",
        default=None,
        help=(
            "Why the account leaves 全托管 (audit trail; quote the operator's "
            "instruction, e.g. 历史冲突换一批账号)."
        ),
    )
    parser.add_argument("--dry-run", action="store_true")


def _build_account_operation_stop_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {"operation_id": args.operation_id, "reason": args.reason}


def _add_account_operation_elements_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--id", dest="operation_id", required=True)
    parser.add_argument("--add-format-ids", default=None)
    parser.add_argument("--add-topic-ids", default=None)
    parser.add_argument("--resume-format-ids", default=None)
    parser.add_argument("--resume-topic-ids", default=None)
    parser.add_argument("--pause-format-ids", default=None)
    parser.add_argument("--pause-topic-ids", default=None)
    parser.add_argument("--note", default=None)
    parser.add_argument("--dry-run", action="store_true")


def _build_account_operation_elements_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "operation_id": args.operation_id,
        "add_format_ids": _csv_id_list(args.add_format_ids),
        "add_topic_ids": _csv_id_list(args.add_topic_ids),
        "resume_format_ids": _csv_id_list(args.resume_format_ids),
        "resume_topic_ids": _csv_id_list(args.resume_topic_ids),
        "pause_format_ids": _csv_id_list(args.pause_format_ids),
        "pause_topic_ids": _csv_id_list(args.pause_topic_ids),
        "note": args.note,
    }


def _account_operation_input_schema(fields: dict[str, str]) -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            name: {"type": "string", "description": desc} for name, desc in fields.items()
        },
    }


def _account_operation_plan_input_schema() -> dict[str, Any]:
    schema = _account_operation_input_schema(
        {
            "operation_id": "Account operation id",
            "format_ids": "CSV format ids",
            "topic_ids": "CSV topic ids",
        }
    )
    schema["properties"]["required_hashtags"] = {
        "type": "array",
        "items": {"type": "string"},
        "maxItems": 50,
        "description": (
            "Account-wide required hashtags. Omit to preserve the current setting; "
            "pass an empty array to clear it."
        ),
    }
    return schema


def _account_operation_specs() -> list[CommandSpec]:
    return [
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+submit",
            summary=(
                "Submit a pool account into automated operation (registers + binds the agent "
                "conversation). Response data.research_disposition tells the outcome: "
                "established_seeded=直接 active(继承既有排期元素,无需调研); "
                "research_directed/inductive/full=进入 onboarding 调研. "
                "When a Product is resolved, pass optional --product-id once to bind product "
                "truth, description/media, and promotion guidance to the operation; an "
                "explicit audience action is optional. Same-Product retries are idempotent "
                "and a different Product is rejected. "
                "Submitting is the explicit Account Publish -> fully-managed mode switch: "
                "an account_publish allocation is atomically transferred and existing "
                "publish configuration is preserved. Live schedule work never blocks the "
                "switch and must NOT be cancelled first: future scheduled items are adopted "
                "by the operation as managed schedule, and generating/generated/publishing "
                "items simply finish outside managed attribution. "
                "Pass --research-prompt/--reference-url ONLY when the operator explicitly "
                "mentioned research direction or benchmark accounts. When submitting MULTIPLE "
                "accounts in one turn, reply ONE consolidated confirmation card "
                "(per-account row: username/op_id/disposition) instead of N cards. "
                "NOTE: an account already operating under a DIFFERENT session is NOT moved "
                "here — you get the existing op back unchanged (no rebind); prefer +submit-batch "
                "which reports this explicitly in meta.existing[] with a conflict link."
            ),
            risk_level="write",
            execution="direct",
            adapter_tool_name="account_operation_submit",
            input_schema=_account_operation_input_schema(
                {
                    "pool_account_id": "Pool account id",
                    "organization_id": "Organization id",
                    "product_id": (
                        "Optional workspace Product/CTA asset id for product context. Stable "
                        "for the operation; different-Product re-submission is rejected."
                    ),
                }
            ),
            output_schema=_direct_output_schema("Account operation registry row."),
            examples=[
                "museoncli account-operation +submit --pool-account-id <uuid> "
                "--organization-id <uuid> --product-id <product_uuid> --niche leather_care"
            ],
            add_arguments=_add_account_operation_submit_arguments,
            build_arguments=_build_account_operation_submit_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+submit-batch",
            summary=(
                "Batch-submit MULTIPLE pool accounts into automated operation in ONE call — "
                "PREFERRED over N single +submit calls when the operator hands over a batch. "
                "All accounts bind to the current session; account-operation submission does "
                "NOT create a campaign monitor. One optional --product-id identifies the "
                "shared Product/CTA context for the ENTIRE batch; one batch has at most one "
                "Product and per-account overrides are forbidden. Shared "
                "--niche/--research-prompt/--reference-url apply to every account. Reply ONE "
                "consolidated confirmation card from the "
                "response rows (username/op_id/research_disposition). "
                "IMPORTANT: per-account failures are isolated — ALWAYS check meta.failed[] "
                "(each {pool_account_id, error}); if non-empty, call out the dropped accounts "
                "in the confirmation and re-submit them, do NOT assume all landed. "
                "ALSO check meta.existing[]: these accounts were ALREADY in operation (not new). "
                "outcome='existing_other_session' means the account is already running under a "
                "DIFFERENT session and was NOT added here — pick a fresh 账号库 account instead, "
                "and surface conflict_session_url so the operator can open that session to check. "
                "outcome='occupied_other_business' means the account is already used by another "
                "business (for example campaign) and was NOT taken into "
                "全托管运营 — pick a different 账号库 (unoccupied) account. "
                "An account_publish holder is transferred automatically during submit; its "
                "live schedule never blocks the transfer — future scheduled items are "
                "adopted by the operation and in-flight items finish as-is, so never cancel "
                "schedules to unblock enrollment. "
                "outcome='not_in_workspace' means the account does not belong to this workspace's "
                "account pool and was NOT taken into 全托管运营 — pick an account from this "
                "workspace. "
                "outcome='existing_product_conflict' means that account is already managed for "
                "another Product and was NOT changed; report current_product_id and "
                "requested_product_id instead of silently switching it. "
                "meta.created_count = how many were genuinely new."
            ),
            risk_level="write",
            execution="direct",
            adapter_tool_name="account_operation_submit_batch",
            input_schema=_account_operation_input_schema(
                {
                    "pool_account_ids": "Comma-separated pool account ids",
                    "organization_id": "Organization id",
                    "product_id": (
                        "Optional single workspace Product/CTA asset id shared by the entire "
                        "batch; one batch has at most one Product and per-account overrides "
                        "are forbidden."
                    ),
                }
            ),
            output_schema=_direct_output_schema(
                "Batch result: data=[operation rows], meta.failed_count, "
                "meta.failed=[{pool_account_id, error}], "
                "meta.created_count, meta.existing_count, meta.existing=[{pool_account_id, "
                "outcome, current_session_conversation_id, conflict_session_url, "
                "occupied_by_type, occupied_by_related_id, "
                "current_product_id, requested_product_id}]."
            ),
            examples=[
                "museoncli account-operation +submit-batch --pool-account-ids <uuid1>,<uuid2> "
                "--organization-id <uuid> --product-id <product_uuid> "
                "--niche diy_restoration --reference-url https://www.tiktok.com/@benchmark"
            ],
            add_arguments=_add_account_operation_submit_batch_arguments,
            build_arguments=_build_account_operation_submit_batch_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+get",
            summary="Get one operated account (lifecycle, health, baseline).",
            risk_level="read",
            execution="direct",
            adapter_tool_name="account_operation_get",
            input_schema=_account_operation_input_schema({"operation_id": "Account operation id"}),
            output_schema=_direct_output_schema("Account operation detail."),
            examples=["museoncli account-operation +get --id <uuid>"],
            add_arguments=_add_account_operation_id_arguments,
            build_arguments=_build_account_operation_id_arguments,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+list",
            summary="List operated accounts in the workspace.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="account_operation_list",
            input_schema=_account_operation_input_schema(
                {"page": "Page number (1-based)", "page_size": "Page size"}
            ),
            output_schema=_direct_output_schema("Account operation list."),
            examples=["museoncli account-operation +list --page-size 20"],
            add_arguments=_add_account_operation_list_arguments,
            build_arguments=_build_account_operation_list_arguments,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+ops-status",
            summary=(
                "Whole-fleet operation/publish status for the workspace in ONE aggregate query — "
                "USE THIS instead of sampling a few accounts with +get/+runs before concluding "
                "anything about publishing. IMPORTANT: a scheduled backlog draining over hours is "
                "the DESIGNED steady state (finite generation throughput), so backlog/lag alone is "
                "NEVER a problem — report red ONLY on "
                "capacity.due_demand_exceeds_capacity, "
                "delivery stage overdue_items, pipeline.stuck > 0, or "
                "accounts_needing_intervention > 0. Returns: capacity "
                "{backlog_items (legacy all-scheduled), due_backlog_items (headline), "
                "scheduled_future_items, drain_rate_24h_per_hour, "
                "eta_hours_to_clear_due, demand_per_day, capacity_24h_per_day, "
                "due_demand_exceeds_capacity, "
                "publish_success_rate_24h (null = no outcomes)}; accounts_needing_intervention "
                "(THE number: stalled accounts in the cold_start/active/recovering cohort); "
                "delivery_stages (managed lane) + manual_delivery_stages (one_off outside the "
                "managed cohort), each split into future_reservations, due_unclaimed, "
                "awaiting_publish_approval, generation_done_awaiting_handoff, "
                "delivery_executing, and "
                "delivery_succeeded_awaiting_visibility with oldest_age_seconds / "
                "overdue_items; "
                "pipeline in 条 {published_24h, in_flight, pending (waiting its turn = normal), "
                "stuck (FIFO pipeline PASSED IT OVER = real), failed_24h, total = their sum}; "
                "account_health[] per cohort lifecycle {accounts = producing + stalled + "
                "not_ready}; lifecycle_funnel[] (all lifecycles, plain counts); failed_reasons[] "
                "{code, label, items, distinct_accounts} over failed_reasons_window (--window "
                "24h|7d, default 24h). Item stats cover source='one_off' items of accounts under "
                "active operation. Read-only."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="account_operation_ops_status",
            input_schema=_account_operation_input_schema(
                {"window": "failed_reasons window: 24h (default) | 7d"}
            ),
            output_schema=_direct_output_schema(
                "Aggregate ops status: data.capacity (headline), "
                "data.accounts_needing_intervention, data.pipeline (MECE, sums to "
                "pipeline.total), data.delivery_stages + data.manual_delivery_stages, "
                "data.account_health + data.health_cohort_accounts, "
                "data.lifecycle_funnel + data.accounts_total, data.failed_reasons + "
                "data.failed_reasons_window."
            ),
            examples=[
                "museoncli account-operation +ops-status",
                "museoncli account-operation +ops-status --window 7d",
            ],
            add_arguments=_add_account_operation_ops_status_arguments,
            build_arguments=_build_account_operation_ops_status_arguments,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+daily-roster",
            summary=(
                "Per-account schedule/publish roster for ONE local day across the WHOLE "
                "publish-line fleet in one query — USE THIS to answer 'which accounts have no "
                "schedule / have not published for day X' instead of sampling +runs per account. "
                "Covers BOTH 全托管 and 半托管 accounts (each row tagged is_fully_managed); "
                "--managed all|full|semi filters. Returns data.summary (whole cohort: "
                "accounts_total, full_managed, semi_managed, scheduled, unscheduled, "
                "publish_success, publish_failed, no_publish) and data.accounts[] per account "
                "{is_fully_managed, lifecycle_status, scheduled_items, has_schedule, "
                "succeeded_items, failed_items, in_flight_items, waiting_items, cancelled_items, "
                "published_ok, unpublished_reason_kind (failed|in_flight|waiting|no_schedule)}. "
                "scheduled_items EXCLUDES cancelled/skipped. --success any (>=1 published, "
                "default) | all (every live item published). --date YYYY-MM-DD in --tz "
                "(default today). For a within-day 'not published by <time>' question "
                "(e.g. BJT 18:00) pass --as-of 18:00: each row then carries cutoff "
                "{due, published, unpublished} and --filter behind returns only accounts with "
                "items due by the cutoff that had not published — excluding slots not yet due. "
                "--filter narrows returned rows (all|unscheduled|failed|no-publish|behind). "
                "Read-only."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="account_operation_daily_roster",
            input_schema=_account_operation_input_schema(
                {
                    "date": "Local calendar day YYYY-MM-DD (default: today in timezone)",
                    "timezone": "IANA timezone, e.g. Asia/Shanghai (default UTC)",
                    "managed": "Management-mode filter: all (default) | full | semi",
                    "success": "published_ok basis: any (default) | all",
                    "as_of": "Intra-day cutoff HH:MM local (e.g. 18:00); enables cutoff + filter behind",
                    "filter": "Row filter: all (default) | unscheduled | failed | no-publish | behind",
                    "page": "Page number (1-based)",
                    "page_size": "Page size (default 200, max 500)",
                }
            ),
            output_schema=_direct_output_schema(
                "Daily roster: data.summary (whole-cohort counts, incl. behind when as_of set) + "
                "data.accounts[] (per-account schedule/publish status, tagged is_fully_managed, "
                "plus cutoff when as_of set) + data.pagination."
            ),
            examples=[
                "museoncli account-operation +daily-roster --tz Asia/Shanghai",
                "museoncli account-operation +daily-roster --date 2026-07-21 --tz Asia/Shanghai --filter no-publish",
                "museoncli account-operation +daily-roster --tz Asia/Shanghai --as-of 18:00 --filter behind",
            ],
            add_arguments=_add_account_operation_daily_roster_arguments,
            build_arguments=_build_account_operation_daily_roster_arguments,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+runs",
            summary="List an operated account's daily runs (steps, attribution flag, schedule result).",
            risk_level="read",
            execution="direct",
            adapter_tool_name="account_operation_runs",
            input_schema=_account_operation_input_schema(
                {"operation_id": "Account operation id", "limit": "Max rows (default 10)"}
            ),
            output_schema=_direct_output_schema("Daily run list."),
            examples=["museoncli account-operation +runs --id <uuid> --limit 5"],
            add_arguments=_add_account_operation_id_limit_arguments,
            build_arguments=_build_account_operation_id_limit_arguments,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+tags",
            summary="List an operated account's element tags (format/topic/combo lifecycle).",
            risk_level="read",
            execution="direct",
            adapter_tool_name="account_operation_tags",
            input_schema=_account_operation_input_schema({"operation_id": "Account operation id"}),
            output_schema=_direct_output_schema("Element tag list."),
            examples=["museoncli account-operation +tags --id <uuid>"],
            add_arguments=_add_account_operation_id_arguments,
            build_arguments=_build_account_operation_id_arguments,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+attribution",
            summary="List an operated account's attribution reports (comment classes, recommendation, decision).",
            risk_level="read",
            execution="direct",
            adapter_tool_name="account_operation_attribution",
            input_schema=_account_operation_input_schema(
                {"operation_id": "Account operation id", "limit": "Max rows (default 10)"}
            ),
            output_schema=_direct_output_schema("Attribution report list."),
            examples=["museoncli account-operation +attribution --id <uuid> --limit 5"],
            add_arguments=_add_account_operation_id_limit_arguments,
            build_arguments=_build_account_operation_id_limit_arguments,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+plan-submit",
            summary="Write back the onboarding/reset research plan (seed formats/topics) -> cold_start.",
            risk_level="write",
            execution="direct",
            adapter_tool_name="account_operation_plan_submit",
            input_schema=_account_operation_plan_input_schema(),
            output_schema=_direct_output_schema("Updated account operation."),
            examples=[
                (
                    "museoncli account-operation +plan-submit --id <uuid> "
                    "--format-ids f1,f2 --topic-ids t1,t2 "
                    "--required-hashtags '#PlantSenso,#PlantCare'"
                )
            ],
            add_arguments=_add_account_operation_plan_arguments,
            build_arguments=_build_account_operation_plan_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+set-persona",
            summary=(
                "Author & attach the account's persona (REQUIRED first step of onboarding "
                "research, BEFORE +plan-submit). 全托管 accounts have no persona ref, so the "
                "publish pipeline generates from the persona set here; without it, generation "
                "fails. Define {name, description, tags} from research: for a 对标账号 "
                "(reference_url) capture that creator's voice/audience/style; for "
                "established_seeded use the account's OWN seed content; otherwise from open "
                "research. Creates a workspace persona and sets account_operations.persona_id. "
                "Idempotent-safe to re-call to replace the persona."
            ),
            risk_level="write",
            execution="direct",
            adapter_tool_name="account_operation_set_persona",
            input_schema=_account_operation_input_schema(
                {
                    "operation_id": "Account operation id",
                    "name": "Persona name",
                    "description": "Persona voice/audience/positioning summary",
                    "tags": "CSV style/audience tags",
                }
            ),
            output_schema=_direct_output_schema(
                "data.persona_id (new persona) + data.operation_id."
            ),
            examples=[
                'museoncli account-operation +set-persona --id <uuid> --name "Rustic DIY Restorer" '
                '--description "warm, hands-on cast-iron restoration voice for beginner DIYers" '
                "--tags diy,cast_iron,beginner_friendly"
            ],
            add_arguments=_add_account_operation_persona_arguments,
            build_arguments=_build_account_operation_persona_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+strategy-decide",
            summary="Decide the attribution review (human override or auto timeout) and resume the daily run.",
            risk_level="write",
            execution="direct",
            adapter_tool_name="account_operation_strategy_decide",
            input_schema=_account_operation_input_schema(
                {
                    "operation_id": "Account operation id",
                    "run_id": "Daily run id",
                    "decided_by": "human|auto-timeout",
                }
            ),
            output_schema=_direct_output_schema("Daily run after the decision."),
            examples=[
                "museoncli account-operation +strategy-decide --id <uuid> --run-id <uuid> --decided-by auto-timeout"
            ],
            add_arguments=_add_account_operation_decide_arguments,
            build_arguments=_build_account_operation_decide_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+stop",
            summary=(
                "Retire an account from automated operation (TERMINAL). USE WHEN the operator "
                "removes an account from 全托管 — e.g. conflict accounts being replaced by a "
                "new batch (历史冲突，换一批账号), or the operator says an account should no "
                "longer be operated. IMPORTANT: submitting replacement accounts does NOT retire "
                "the originals — without +stop they stay live and the system keeps dispatching "
                "research/persona/daily-run tasks for them forever. Full GC: cancels the op's "
                "pending schedule items, releases the account reservation, unbinds the work "
                "session, detaches the campaign, and frees the account so it can be +submit-ed "
                "afresh later. Pass --reason quoting the operator's instruction (audit trail)."
            ),
            risk_level="write",
            execution="direct",
            adapter_tool_name="account_operation_stop",
            input_schema=_account_operation_input_schema(
                {
                    "operation_id": "Account operation id",
                    "reason": "Retirement reason (operator's instruction)",
                }
            ),
            output_schema=_direct_output_schema("Stopped account operation (terminal)."),
            examples=[
                'museoncli account-operation +stop --id <uuid> --reason "历史冲突，运营指示换一批账号"'
            ],
            add_arguments=_add_account_operation_stop_arguments,
            build_arguments=_build_account_operation_stop_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.ACCOUNT_OPERATION,
            shortcut="+elements-replace",
            summary="Weak recovery write-back: add new formats/topics, resume paused ones, and pause failing ones.",
            risk_level="write",
            execution="direct",
            adapter_tool_name="account_operation_elements_replace",
            input_schema=_account_operation_input_schema(
                {
                    "operation_id": "Account operation id",
                    "add_format_ids": "CSV",
                    "add_topic_ids": "CSV",
                    "resume_format_ids": "CSV format ids to move from pause back to testing",
                    "resume_topic_ids": "CSV topic ids to move from pause back to testing",
                }
            ),
            output_schema=_direct_output_schema("Updated account operation."),
            examples=[
                "museoncli account-operation +elements-replace --id <uuid> --add-format-ids f9 --pause-format-ids f1",
                "museoncli account-operation +elements-replace --id <uuid> --resume-format-ids f2 --note operator-confirmed",
            ],
            add_arguments=_add_account_operation_elements_arguments,
            build_arguments=_build_account_operation_elements_arguments,
            supports_dry_run=True,
        ),
    ]


def specs() -> list[CommandSpec]:
    return _account_operation_specs()


# ---- executors (generated from main.py direct_* chains) ----
async def _execute_elements_replace(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    api_data_v2 = ctx.api_data_v2
    operation_id = str(arguments.get("operation_id") or "")
    payload = {
        "add_format_ids": _account_operation_csv(arguments.get("add_format_ids")),
        "add_topic_ids": _account_operation_csv(arguments.get("add_topic_ids")),
        "resume_format_ids": _account_operation_csv(arguments.get("resume_format_ids")),
        "resume_topic_ids": _account_operation_csv(arguments.get("resume_topic_ids")),
        "pause_format_ids": _account_operation_csv(arguments.get("pause_format_ids")),
        "pause_topic_ids": _account_operation_csv(arguments.get("pause_topic_ids")),
        "note": arguments.get("note"),
    }
    return await api_data_v2(
        cfg, "POST", f"/account-operations/{operation_id}/elements:replace", json_body=payload
    )


async def _execute_get(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    api_data_v2 = ctx.api_data_v2
    operation_id = str(arguments.get("operation_id") or "")
    return await api_data_v2(cfg, "GET", f"/account-operations/{operation_id}")


async def _execute_ops_status(ctx: CommandContext) -> Any:
    return await ctx.api_data_v2(
        ctx.cfg,
        "GET",
        "/account-operations/ops-status",
        params=compact_params(
            {"workspace_id": ctx.workspace_id, "window": ctx.arguments.get("window")}
        ),
    )


async def _execute_daily_roster(ctx: CommandContext) -> Any:
    arguments = ctx.arguments
    payload = compact_params(
        {
            "workspace_id": ctx.workspace_id,
            "date": arguments.get("date"),
            "timezone": arguments.get("timezone"),
            "managed": arguments.get("managed"),
            "success": arguments.get("success"),
            "as_of": arguments.get("as_of"),
            "filter": arguments.get("result_filter"),
            "page": arguments.get("page"),
            "page_size": arguments.get("page_size"),
        }
    )
    return await ctx.api_data_v2(
        ctx.cfg, "POST", "/account-ops-health/roster/query", json_body=payload
    )


async def _execute_runs(ctx: CommandContext) -> Any:
    operation_id = str(ctx.arguments.get("operation_id") or "")
    return await ctx.api_data_v2(
        ctx.cfg,
        "GET",
        f"/account-operations/{operation_id}/daily-runs",
        params={"limit": ctx.arguments.get("limit", 10)},
    )


async def _execute_tags(ctx: CommandContext) -> Any:
    operation_id = str(ctx.arguments.get("operation_id") or "")
    return await ctx.api_data_v2(ctx.cfg, "GET", f"/account-operations/{operation_id}/tags")


async def _execute_attribution(ctx: CommandContext) -> Any:
    operation_id = str(ctx.arguments.get("operation_id") or "")
    return await ctx.api_data_v2(
        ctx.cfg,
        "GET",
        f"/account-operations/{operation_id}/attribution-reports",
        params={"limit": ctx.arguments.get("limit", 10)},
    )


async def _execute_list(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data_v2 = ctx.api_data_v2
    return await api_data_v2(
        cfg,
        "GET",
        "/account-operations",
        params=compact_params(
            {
                "workspace_id": workspace_id,
                "limit": arguments.get("page_size", 50),
                "offset": (int(arguments.get("page", 1)) - 1) * int(arguments.get("page_size", 50)),
            }
        ),
    )


async def _execute_plan_submit(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    api_data_v2 = ctx.api_data_v2
    operation_id = str(arguments.get("operation_id") or "")
    payload = {
        "format_ids": _account_operation_csv(arguments.get("format_ids")),
        "topic_ids": _account_operation_csv(arguments.get("topic_ids")),
        "note": arguments.get("note"),
    }
    if "required_hashtags" in arguments:
        payload["required_hashtags"] = _account_operation_csv(arguments.get("required_hashtags"))
    return await api_data_v2(
        cfg, "POST", f"/account-operations/{operation_id}/plan:submit", json_body=payload
    )


async def _execute_set_persona(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    api_data_v2 = ctx.api_data_v2
    operation_id = str(arguments.get("operation_id") or "")
    payload = compact_params(
        {
            "name": arguments.get("name"),
            "description": arguments.get("description"),
            "tags": _account_operation_csv(arguments.get("tags")),
        }
    )
    return await api_data_v2(
        cfg, "POST", f"/account-operations/{operation_id}/persona", json_body=payload
    )


async def _execute_strategy_decide(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    api_data_v2 = ctx.api_data_v2
    operation_id = str(arguments.get("operation_id") or "")
    run_id = str(arguments.get("run_id") or "")
    decision = (
        read_json_option(value=arguments.get("decision_json"), file_path=None, field="decision")
        if arguments.get("decision_json")
        else None
    )
    payload = compact_params({"decided_by": arguments.get("decided_by"), "decision": decision})
    return await api_data_v2(
        cfg,
        "POST",
        f"/account-operations/{operation_id}/daily-runs/{run_id}/strategy:decide",
        json_body=payload,
    )


async def _execute_stop(ctx: CommandContext) -> Any:
    operation_id = str(ctx.arguments.get("operation_id") or "")
    payload = compact_params({"reason": ctx.arguments.get("reason")})
    return await ctx.api_data_v2(
        ctx.cfg, "POST", f"/account-operations/{operation_id}/stop", json_body=payload
    )


async def _execute_submit(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data_v2 = ctx.api_data_v2
    runtime = cfg.runtime_context if isinstance(cfg.runtime_context, dict) else {}
    # Per-turn patched runtime context: conversation_id == the CURRENT session
    # (topic/thread) — the account's dedicated workbench.
    session_conversation_id = arguments.get("session_conversation_id") or runtime.get(
        "conversation_id"
    )
    source_channel_message_id = runtime.get("source_channel_message_id")
    payload = compact_params(
        {
            "workspace_id": workspace_id,
            "organization_id": arguments.get("organization_id"),
            "pool_account_id": arguments.get("pool_account_id"),
            "persona_id": arguments.get("persona_id"),
            "product_id": arguments.get("product_id"),
            "niche": arguments.get("niche"),
            "session_conversation_id": session_conversation_id,
            "source_channel_message_id": source_channel_message_id,
            "target_delivery_mode": arguments.get("target_delivery_mode"),
            "research_prompt": arguments.get("research_prompt"),
            "reference_url": arguments.get("reference_url"),
            "preferred_publish_time": arguments.get("preferred_publish_time"),
            "preferred_publish_timezone": arguments.get("preferred_publish_timezone"),
        }
    )
    return await api_data_v2(cfg, "POST", "/account-operations", json_body=payload)


async def _execute_submit_batch(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    runtime = cfg.runtime_context if isinstance(cfg.runtime_context, dict) else {}
    session_conversation_id = arguments.get("session_conversation_id") or runtime.get(
        "conversation_id"
    )
    raw_ids = str(arguments.get("pool_account_ids") or "")
    pool_ids = [part.strip() for part in raw_ids.split(",") if part.strip()]
    payload = compact_params(
        {
            "workspace_id": ctx.workspace_id,
            "organization_id": arguments.get("organization_id"),
            "session_conversation_id": session_conversation_id,
            "source_channel_message_id": runtime.get("source_channel_message_id"),
            "target_delivery_mode": arguments.get("target_delivery_mode"),
            "product_id": arguments.get("product_id"),
            "niche": arguments.get("niche"),
            "research_prompt": arguments.get("research_prompt"),
            "reference_url": arguments.get("reference_url"),
            "preferred_publish_time": arguments.get("preferred_publish_time"),
            "preferred_publish_timezone": arguments.get("preferred_publish_timezone"),
            "accounts": [{"pool_account_id": pid} for pid in pool_ids],
        }
    )
    return await ctx.api_data_v2(cfg, "POST", "/account-operations/batch:submit", json_body=payload)


EXECUTORS = {
    "account-operation.attribution": direct_enveloped(_execute_attribution),
    "account-operation.daily-roster": direct_enveloped(_execute_daily_roster),
    "account-operation.elements-replace": direct_enveloped(_execute_elements_replace),
    "account-operation.get": direct_enveloped(_execute_get),
    "account-operation.list": direct_enveloped(_execute_list),
    "account-operation.ops-status": direct_enveloped(_execute_ops_status),
    "account-operation.plan-submit": direct_enveloped(_execute_plan_submit),
    "account-operation.runs": direct_enveloped(_execute_runs),
    "account-operation.set-persona": direct_enveloped(_execute_set_persona),
    "account-operation.stop": direct_enveloped(_execute_stop),
    "account-operation.strategy-decide": direct_enveloped(_execute_strategy_decide),
    "account-operation.submit": direct_enveloped(_execute_submit),
    "account-operation.submit-batch": direct_enveloped(_execute_submit_batch),
    "account-operation.tags": direct_enveloped(_execute_tags),
}


def _account_operation_csv(value: Any) -> list[str]:
    if not value:
        return []
    if isinstance(value, list):
        return [str(part).strip() for part in value if str(part).strip()]
    return [part.strip() for part in str(value).split(",") if part.strip()]
