"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from museoncli.artifact_validation import validate_artifact_file
from museoncli.domains._model import CommandSpec, Domain
from museoncli.domains._shared import (
    _add_common_adapter_arguments,
    _direct_output_schema,
    _json_object,
    _load_structured_args,
    _without_none,
)
from museoncli.execution import CommandContext, direct_enveloped


def _add_artifact_upload_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--file", required=True)
    parser.add_argument("--artifact-id")
    parser.add_argument("--artifact-type", default="file")
    parser.add_argument("--title")
    parser.add_argument("--runtime-context-json")
    parser.add_argument("--runtime-context-file")
    parser.add_argument("--metadata-json")
    parser.add_argument("--metadata-file")
    # Markdown customer deliverables are public by default; --no-public keeps them private.
    parser.add_argument(
        "--public",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Publish markdown artifacts to a public share URL (default: true).",
    )
    parser.add_argument("--dry-run", action="store_true")


def _add_artifact_share_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--artifact-id", required=True)
    parser.add_argument("--dry-run", action="store_true")


def _add_artifact_validate_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--file", required=True)


def _build_artifact_upload_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update(
        _without_none(
            {
                "file": args.file,
                "artifact_id": args.artifact_id,
                "artifact_type": args.artifact_type,
                "title": args.title,
                "runtime_context": _structured_object_arg(
                    args.runtime_context_json,
                    args.runtime_context_file,
                    flag="--runtime-context-json",
                    file_flag="--runtime-context-file",
                ),
                "metadata": _structured_object_arg(
                    args.metadata_json,
                    args.metadata_file,
                    flag="--metadata-json",
                    file_flag="--metadata-file",
                ),
                "public": bool(args.public),
            }
        )
    )
    return _without_none(payload)


def _build_artifact_share_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update({"artifact_id": args.artifact_id})
    return _without_none(payload)


def _build_artifact_validate_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {"file": args.file}


def _structured_object_arg(
    value: str | None,
    file_value: str | None,
    *,
    flag: str,
    file_flag: str,
) -> dict[str, Any] | None:
    if value is not None and file_value is not None:
        raise ValueError(f"{flag} and {file_flag} cannot be used together.")
    if value is not None:
        return _json_object(value, flag=flag)
    if file_value is not None:
        raw = Path(file_value).read_text(encoding="utf-8")
        return _json_object(raw, flag=file_flag)
    return None


def _artifact_upload_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "file": {
                "type": "string",
                "minLength": 1,
                "description": "Local file path uploaded as multipart form-data.",
            },
            "artifact_id": {
                "type": ["string", "null"],
                "format": "uuid",
                "description": "Existing artifact UUID to replace. Omit to create a new artifact.",
            },
            "artifact_type": {
                "type": "string",
                "default": "file",
                "description": (
                    "Storage field on agents_artifacts (default file). "
                    "Not a deliverable taxonomy — all markdown reports use the same template."
                ),
            },
            "title": {"type": ["string", "null"]},
            "runtime_context": {
                "type": ["object", "null"],
                "description": "Runtime context object stored under agents_artifacts.metadata.",
            },
            "metadata": {
                "type": ["object", "null"],
                "description": "Additional metadata merged into agents_artifacts.metadata.",
            },
            "public": {
                "type": "boolean",
                "default": True,
                "description": (
                    "Publish markdown artifacts to a public share URL (default true). "
                    "Pass false / --no-public only when the user explicitly wants a private artifact."
                ),
            },
            "dry_run": {"type": "boolean", "default": False},
        },
        "required": ["file"],
    }


def _artifact_share_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "artifact_id": {
                "type": "string",
                "format": "uuid",
                "description": "Agent artifact UUID to publish to the public internet.",
            },
            "dry_run": {"type": "boolean", "default": False},
        },
        "required": ["artifact_id"],
    }


def _artifact_unshare_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "artifact_id": {
                "type": "string",
                "format": "uuid",
                "description": "Agent artifact UUID whose public internet link should be revoked.",
            },
            "dry_run": {"type": "boolean", "default": False},
        },
        "required": ["artifact_id"],
    }


def _artifact_validate_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "file": {
                "type": "string",
                "minLength": 1,
                "description": "Local UTF-8 Artifact Markdown file to validate without uploading.",
            }
        },
        "required": ["file"],
    }


def specs() -> list[CommandSpec]:
    return [
        CommandSpec(
            domain=Domain.ARTIFACTS,
            shortcut="+validate",
            summary=(
                "Validate one local Artifact Markdown file before upload. Checks frontmatter, "
                "report-directions YAML and field schema, preview URLs, optional stats, and "
                "duplicate social Embed placements. This command performs no network calls."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="artifact_validate",
            input_schema=_artifact_validate_input_schema(),
            output_schema=_direct_output_schema(
                "Validation result with data.valid, errors, warnings, and structural counts."
            ),
            examples=["museoncli artifacts +validate --file ./report.md"],
            add_arguments=_add_artifact_validate_arguments,
            build_arguments=_build_artifact_validate_arguments,
        ),
        CommandSpec(
            domain=Domain.ARTIFACTS,
            shortcut="+upload",
            summary=(
                "Upload or replace one local agent file artifact through multipart form-data. "
                "Markdown uploads are public by default. After upload, give BOTH links when both "
                "exist: data.public_url (public share link, anyone with the link) and data.url "
                "(workspace/private link, logged-in workspace members). Use --no-public only when "
                "the user explicitly wants a private artifact (then only data.url). To embed "
                "resources inside markdown, paste their ready-made ref "
                "([name](https://www.museon.ai/section/id)) from asset +get/+list, "
                "generation +get/+list/+create, or routines +get/+list verbatim. "
                "For generation batch/summary artifacts, paste each generation ref alone on "
                "its own line so it renders as a card; do not hand-write generation links, "
                "file names, local paths, or storage paths as links. You can also paste a raw "
                "TikTok, Instagram, or YouTube URL on its own line to embed a player."
            ),
            risk_level="write",
            execution="direct",
            adapter_tool_name="artifact_upload",
            input_schema=_artifact_upload_input_schema(),
            output_schema=_direct_output_schema(
                "Uploaded artifact payload. data.public_url is the public share link; data.url is "
                "the workspace/private link. Give both when public_url is present; if private-only, "
                "give data.url only."
            ),
            examples=[
                (
                    "museoncli artifacts +upload --file ./report.md "
                    '--runtime-context-json \'{"turn_id":"turn-1"}\''
                ),
                (
                    "museoncli artifacts +upload --file ./report.md "
                    "--artifact-id <artifact_id> --title 'Updated report'"
                ),
                "museoncli artifacts +upload --file ./report.md --no-public",
            ],
            add_arguments=_add_artifact_upload_arguments,
            build_arguments=_build_artifact_upload_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.ARTIFACTS,
            shortcut="+share",
            summary=(
                "Re-enable public internet access for one markdown artifact "
                "(for example after +unshare). Prefer +upload defaults for new reports."
            ),
            risk_level="write",
            execution="direct",
            adapter_tool_name="artifact_share",
            input_schema=_artifact_share_input_schema(),
            output_schema=_direct_output_schema(
                "Public sharing state and public_url returned by Museon API."
            ),
            examples=[
                "museoncli artifacts +share --artifact-id <artifact_id>",
            ],
            add_arguments=_add_artifact_share_arguments,
            build_arguments=_build_artifact_share_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.ARTIFACTS,
            shortcut="+unshare",
            summary=(
                "Revoke the public internet link for one artifact. "
                "Use only when the user explicitly wants to revoke public access."
            ),
            risk_level="write",
            execution="direct",
            adapter_tool_name="artifact_unshare",
            input_schema=_artifact_unshare_input_schema(),
            output_schema=_direct_output_schema(
                "Public sharing state after revocation returned by Museon API."
            ),
            examples=[
                "museoncli artifacts +unshare --artifact-id <artifact_id>",
            ],
            add_arguments=_add_artifact_share_arguments,
            build_arguments=_build_artifact_share_arguments,
            supports_dry_run=True,
        ),
    ]


# ---- executors ----


async def _execute_upload(ctx: CommandContext) -> Any:
    return await ctx.upload_artifact_file(
        ctx.cfg, workspace_id=ctx.workspace_id, arguments=ctx.arguments
    )


async def _execute_validate(ctx: CommandContext) -> Any:
    return validate_artifact_file(str(ctx.arguments.get("file") or ""))


async def _execute_share(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    artifact_id = str(ctx.arguments.get("artifact_id") or "")
    return await ctx.api_data(
        ctx.cfg,
        "POST",
        f"/agent-cli/artifacts/{artifact_id}/share/enable",
        params={"workspace_id": ctx.workspace_id},
    )


async def _execute_unshare(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    artifact_id = str(ctx.arguments.get("artifact_id") or "")
    return await ctx.api_data(
        ctx.cfg,
        "POST",
        f"/agent-cli/artifacts/{artifact_id}/share/disable",
        params={"workspace_id": ctx.workspace_id},
    )


EXECUTORS = {
    "artifacts.validate": direct_enveloped(_execute_validate, with_workspace=False),
    "artifacts.upload": direct_enveloped(_execute_upload),
    "artifacts.share": direct_enveloped(_execute_share),
    "artifacts.unshare": direct_enveloped(_execute_unshare),
}
