"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

from museoncli.execution import agent_domain_result, compact_params

from museoncli.execution import (
    CommandContext,
    direct_enveloped,
)

import argparse
from typing import Any
from museoncli.domains._model import CommandSpec, Domain
from museoncli.domains._shared import (
    _add_common_adapter_arguments,
    _direct_output_schema,
    _load_structured_args,
    _without_none,
)


def _add_campaign_monitor_list_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--search")
    parser.add_argument("--timezone")
    parser.add_argument("--sort", default="created_at_desc")
    parser.add_argument("--page", type=int, default=1)
    parser.add_argument("--page-size", dest="page_size", type=int, default=50)


def _build_campaign_monitor_list_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update(
        _without_none(
            {
                "search": args.search,
                "timezone": args.timezone,
                "sort": args.sort,
                "page": args.page,
                "page_size": args.page_size,
            }
        )
    )
    return payload


def _add_campaign_monitor_id_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", dest="campaign_id", required=True)


def _build_campaign_monitor_id_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload["campaign_id"] = args.campaign_id
    return payload


def _add_campaign_monitor_date_range_arguments(parser: argparse.ArgumentParser) -> None:
    _add_campaign_monitor_id_arguments(parser)
    parser.add_argument("--date-from")
    parser.add_argument("--date-to")


def _build_campaign_monitor_date_range_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _build_campaign_monitor_id_arguments(args)
    payload.update(_without_none({"date_from": args.date_from, "date_to": args.date_to}))
    return payload


def _add_campaign_monitor_paged_tracking_arguments(
    parser: argparse.ArgumentParser,
) -> None:
    _add_campaign_monitor_date_range_arguments(parser)
    parser.add_argument("--page", type=int, default=1)
    parser.add_argument("--page-size", type=int, default=20)
    parser.add_argument("--search")
    parser.add_argument("--platform")
    parser.add_argument("--sort")


def _add_campaign_monitor_creator_list_arguments(
    parser: argparse.ArgumentParser,
) -> None:
    _add_campaign_monitor_paged_tracking_arguments(parser)


def _build_campaign_monitor_creator_list_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _build_campaign_monitor_date_range_arguments(args)
    payload.update(
        _without_none(
            {
                "page": args.page,
                "page_size": args.page_size,
                "search": args.search,
                "platform": args.platform,
                "sort": args.sort,
            }
        )
    )
    return payload


def _add_campaign_monitor_content_list_arguments(parser: argparse.ArgumentParser) -> None:
    _add_campaign_monitor_paged_tracking_arguments(parser)
    parser.add_argument("--creator-id", dest="creator_id")


def _add_campaign_monitor_content_remove_arguments(parser: argparse.ArgumentParser) -> None:
    _add_campaign_monitor_id_arguments(parser)
    parser.add_argument("--collection-content-id", required=True)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--yes", action="store_true")


def _add_campaign_monitor_content_batch_remove_arguments(
    parser: argparse.ArgumentParser,
) -> None:
    _add_campaign_monitor_id_arguments(parser)
    parser.add_argument("--collection-content-ids", required=True)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--yes", action="store_true")


def _build_campaign_monitor_content_list_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _build_campaign_monitor_date_range_arguments(args)
    payload.update(
        _without_none(
            {
                "page": args.page,
                "page_size": args.page_size,
                "search": args.search,
                "platform": args.platform,
                "sort": args.sort,
                "creator_id": args.creator_id,
            }
        )
    )
    return payload


def _build_campaign_monitor_content_remove_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update(
        {
            "campaign_id": args.campaign_id,
            "collection_content_id": args.collection_content_id,
            "dry_run": bool(args.dry_run),
        }
    )
    return payload


def _build_campaign_monitor_content_batch_remove_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update(
        {
            "campaign_id": args.campaign_id,
            "collection_content_ids": _collection_content_ids_csv(args.collection_content_ids),
            "dry_run": bool(args.dry_run),
        }
    )
    return payload


def _collection_content_ids_csv(value: str) -> list[str]:
    collection_content_ids: list[str] = []
    seen: set[str] = set()
    for raw_id in value.split(","):
        collection_content_id = raw_id.strip()
        if collection_content_id and collection_content_id not in seen:
            seen.add(collection_content_id)
            collection_content_ids.append(collection_content_id)
    return collection_content_ids


def _add_campaign_monitor_creator_add_arguments(parser: argparse.ArgumentParser) -> None:
    _add_campaign_monitor_id_arguments(parser)
    parser.add_argument("--url", action="append", dest="creator_urls")
    parser.add_argument("--creator-id", action="append", dest="creator_ids")
    parser.add_argument("--hashtag", action="append", dest="hashtags")
    parser.add_argument("--no-sync", action="store_true", dest="no_sync")
    parser.add_argument("--dry-run", action="store_true")


def _build_campaign_monitor_creator_add_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _build_campaign_monitor_id_arguments(args)
    payload.update(
        _without_none(
            {
                "creator_urls": list(args.creator_urls) if args.creator_urls else None,
                "creator_ids": list(args.creator_ids) if args.creator_ids else None,
                "hashtags": list(args.hashtags) if args.hashtags else None,
            }
        )
    )
    if getattr(args, "no_sync", False):
        payload["sync"] = False
    if not payload.get("creator_urls") and not payload.get("creator_ids"):
        raise ValueError("Provide at least one --url or --creator-id.")
    return payload


def _add_campaign_monitor_creator_remove_arguments(parser: argparse.ArgumentParser) -> None:
    _add_campaign_monitor_id_arguments(parser)
    parser.add_argument("--creator-id", dest="creator_social_account_id", required=True)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--yes", action="store_true")


def _build_campaign_monitor_creator_remove_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update(
        {
            "campaign_id": args.campaign_id,
            "creator_social_account_id": args.creator_social_account_id,
            "dry_run": bool(args.dry_run),
        }
    )
    return payload


def _add_campaign_monitor_content_add_arguments(parser: argparse.ArgumentParser) -> None:
    _add_campaign_monitor_id_arguments(parser)
    parser.add_argument("--url", action="append", dest="content_urls")
    parser.add_argument("--content-id", action="append", dest="content_ids")
    parser.add_argument("--no-sync", action="store_true", dest="no_sync")
    parser.add_argument("--dry-run", action="store_true")


def _build_campaign_monitor_content_add_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _build_campaign_monitor_id_arguments(args)
    payload.update(
        _without_none(
            {
                "content_urls": list(args.content_urls) if args.content_urls else None,
                "content_ids": list(args.content_ids) if args.content_ids else None,
            }
        )
    )
    if getattr(args, "no_sync", False):
        payload["sync"] = False
    if not payload.get("content_urls") and not payload.get("content_ids"):
        raise ValueError("Provide at least one --url or --content-id.")
    return payload


def _add_campaign_monitor_summary_arguments(parser: argparse.ArgumentParser) -> None:
    _add_campaign_monitor_date_range_arguments(parser)
    parser.add_argument("--granularity", default="day")
    parser.add_argument("--search")
    parser.add_argument("--platform")
    parser.add_argument("--metrics")
    parser.add_argument("--creator-id", dest="creator_id")


def _build_campaign_monitor_summary_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _build_campaign_monitor_date_range_arguments(args)
    payload.update(
        _without_none(
            {
                "granularity": args.granularity,
                "search": args.search,
                "platform": args.platform,
                "metrics": args.metrics,
                "creator_id": args.creator_id,
            }
        )
    )
    return payload


def _campaign_monitor_list_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "search": {"type": ["string", "null"]},
            "timezone": {"type": ["string", "null"]},
            "sort": {"type": "string", "default": "created_at_desc"},
            "page": {"type": "integer", "minimum": 1, "default": 1},
            "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 50},
        },
        "required": [],
    }


def _campaign_monitor_id_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {"campaign_id": {"type": "string", "minLength": 1}},
        "required": ["campaign_id"],
    }


def _campaign_monitor_date_range_input_schema() -> dict[str, Any]:
    schema = _campaign_monitor_id_input_schema()
    schema["properties"].update(
        {
            "date_from": {"type": ["string", "null"]},
            "date_to": {"type": ["string", "null"]},
        }
    )
    return schema


def _campaign_monitor_paged_input_schema() -> dict[str, Any]:
    schema = _campaign_monitor_date_range_input_schema()
    schema["properties"].update(
        {
            "page": {"type": "integer", "minimum": 1, "default": 1},
            "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 20},
            "search": {"type": ["string", "null"]},
            "platform": {"type": ["string", "null"]},
            "sort": {"type": ["string", "null"]},
        }
    )
    return schema


def _campaign_monitor_creator_list_input_schema() -> dict[str, Any]:
    schema = _campaign_monitor_paged_input_schema()
    return schema


def _campaign_monitor_content_list_input_schema() -> dict[str, Any]:
    schema = _campaign_monitor_paged_input_schema()
    schema["properties"].update(
        {
            "creator_id": {"type": ["string", "null"]},
        }
    )
    return schema


def _campaign_monitor_content_remove_input_schema() -> dict[str, Any]:
    schema = _campaign_monitor_id_input_schema()
    schema["properties"].update(
        {
            "collection_content_id": {"type": "string", "minLength": 1},
            "dry_run": {"type": "boolean", "default": False},
        }
    )
    schema["required"].append("collection_content_id")
    return schema


def _campaign_monitor_content_batch_remove_input_schema() -> dict[str, Any]:
    schema = _campaign_monitor_id_input_schema()
    schema["properties"].update(
        {
            "collection_content_ids": {
                "type": "array",
                "items": {"type": "string", "minLength": 1},
                "minItems": 1,
                "maxItems": 100,
            },
            "dry_run": {"type": "boolean", "default": False},
        }
    )
    schema["required"].append("collection_content_ids")
    return schema


def _campaign_monitor_creator_add_input_schema() -> dict[str, Any]:
    schema = _campaign_monitor_id_input_schema()
    schema["properties"].update(
        {
            "creator_urls": {
                "type": ["array", "null"],
                "items": {"type": "string"},
                "description": (
                    "Public creator profile URLs to track. Resolved in a background "
                    "task (response data.url_import_task); verify later with +creator-list."
                ),
            },
            "creator_ids": {
                "type": ["array", "null"],
                "items": {"type": "string"},
                "description": "Existing creator_social_account ids already known to Museon.",
            },
            "hashtags": {
                "type": ["array", "null"],
                "items": {"type": "string"},
                "description": "Optional hashtag filters stored on the creator monitors.",
            },
            "sync": {"type": "boolean", "default": True},
        }
    )
    return schema


def _campaign_monitor_creator_remove_input_schema() -> dict[str, Any]:
    schema = _campaign_monitor_id_input_schema()
    schema["properties"].update(
        {
            "creator_social_account_id": {"type": "string", "minLength": 1},
            "dry_run": {"type": "boolean", "default": False},
        }
    )
    schema["required"].append("creator_social_account_id")
    return schema


def _campaign_monitor_content_add_input_schema() -> dict[str, Any]:
    schema = _campaign_monitor_id_input_schema()
    schema["properties"].update(
        {
            "content_urls": {
                "type": ["array", "null"],
                "items": {"type": "string"},
                "description": (
                    "Public post/video URLs to track. Resolved in a background task "
                    "(response data.url_import_task); verify later with +content-list."
                ),
            },
            "content_ids": {
                "type": ["array", "null"],
                "items": {"type": "string"},
                "description": "Existing content ids already known to Museon (field `id` from +content-list).",
            },
            "sync": {"type": "boolean", "default": True},
        }
    )
    return schema


def _campaign_monitor_summary_input_schema() -> dict[str, Any]:
    schema = _campaign_monitor_date_range_input_schema()
    schema["properties"].update(
        {
            "granularity": {"type": "string", "default": "day"},
            "search": {"type": ["string", "null"]},
            "platform": {"type": ["string", "null"]},
            "metrics": {"type": ["string", "null"]},
            "creator_id": {"type": ["string", "null"]},
        }
    )
    return schema


def specs() -> list[CommandSpec]:
    return [
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+list",
            summary="List campaign monitor collections available to the active workspace.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="campaign_monitor_list",
            input_schema=_campaign_monitor_list_input_schema(),
            output_schema=_direct_output_schema(
                "Campaign monitor list payload returned by Museon API."
            ),
            examples=[
                "museoncli campaign-monitor +list --search launch --limit 20",
            ],
            add_arguments=_add_campaign_monitor_list_arguments,
            build_arguments=_build_campaign_monitor_list_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+get",
            summary="Read one campaign monitor collection.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="campaign_monitor_get",
            input_schema=_campaign_monitor_id_input_schema(),
            output_schema=_direct_output_schema(
                "Campaign monitor detail payload returned by Museon API."
            ),
            examples=[
                "museoncli campaign-monitor +get --id <campaign_monitor_id>",
            ],
            add_arguments=_add_campaign_monitor_id_arguments,
            build_arguments=_build_campaign_monitor_id_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+creator-list",
            summary="List creators covered by a campaign monitor.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="campaign_monitor_creator_list",
            input_schema=_campaign_monitor_creator_list_input_schema(),
            output_schema=_direct_output_schema(
                "Campaign monitor creator payload returned by Museon API."
            ),
            examples=[
                ("museoncli campaign-monitor +creator-list --id <campaign_id> --sort views_desc"),
            ],
            add_arguments=_add_campaign_monitor_creator_list_arguments,
            build_arguments=_build_campaign_monitor_creator_list_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+creator-add",
            summary=(
                "Track creators in a campaign so their matching posts sync in going "
                "forward. --url imports new creators by public profile URL via a "
                "background task (response data.url_import_task); --creator-id attaches "
                "creators already known to Museon. Verify with +creator-list later."
            ),
            risk_level="write",
            supports_dry_run=True,
            execution="direct",
            adapter_tool_name="campaign_monitor_creator_add",
            input_schema=_campaign_monitor_creator_add_input_schema(),
            output_schema=_direct_output_schema(
                "Add summary: requested ids/urls, creator_id_task, url_import_task."
            ),
            examples=[
                (
                    "museoncli campaign-monitor +creator-add --id <campaign_id> "
                    "--url https://www.tiktok.com/@creator1"
                ),
                (
                    "museoncli campaign-monitor +creator-add --id <campaign_id> "
                    "--creator-id <creator_social_account_id>"
                ),
            ],
            add_arguments=_add_campaign_monitor_creator_add_arguments,
            build_arguments=_build_campaign_monitor_creator_add_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+creator-remove",
            summary=(
                "Stop tracking a creator in a campaign: removes the creator monitor and "
                "its derived content monitors from this campaign and resyncs. This does "
                "NOT delete the creator's social-platform account; explicit operator "
                "confirmation is required before running with --yes. Tracking is "
                "workspace-wide, so the monitor is only fully deleted when no other "
                "campaign references it. --creator-id is the creator_social_account_id "
                "from +creator-list."
            ),
            risk_level="destructive",
            requires_confirmation=True,
            supports_dry_run=True,
            execution="direct",
            adapter_tool_name="campaign_monitor_creator_remove",
            input_schema=_campaign_monitor_creator_remove_input_schema(),
            output_schema=_direct_output_schema(
                "Creator removal payload: affected monitor_ids and scope note."
            ),
            examples=[
                (
                    "museoncli campaign-monitor +creator-remove --id <campaign_id> "
                    "--creator-id <creator_social_account_id> --dry-run"
                ),
            ],
            add_arguments=_add_campaign_monitor_creator_remove_arguments,
            build_arguments=_build_campaign_monitor_creator_remove_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+content-list",
            summary="List posts/content covered by a campaign monitor.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="campaign_monitor_content_list",
            input_schema=_campaign_monitor_content_list_input_schema(),
            output_schema=_direct_output_schema(
                "Campaign monitor content payload returned by Museon API."
            ),
            examples=[
                (
                    "museoncli campaign-monitor +content-list "
                    "--id <campaign_id> --platform tiktok --page-size 20"
                ),
            ],
            add_arguments=_add_campaign_monitor_content_list_arguments,
            build_arguments=_build_campaign_monitor_content_list_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+content-add",
            summary=(
                "Track individual posts in a campaign. --url imports new posts by public "
                "URL via a background task (response data.url_import_task); --content-id "
                "attaches posts already known to Museon. Verify with +content-list later."
            ),
            risk_level="write",
            supports_dry_run=True,
            execution="direct",
            adapter_tool_name="campaign_monitor_content_add",
            input_schema=_campaign_monitor_content_add_input_schema(),
            output_schema=_direct_output_schema(
                "Add summary: requested ids/urls, content_id_task, url_import_task."
            ),
            examples=[
                (
                    "museoncli campaign-monitor +content-add --id <campaign_id> "
                    "--url https://www.tiktok.com/@creator/video/123"
                ),
                (
                    "museoncli campaign-monitor +content-add --id <campaign_id> "
                    "--content-id <content_id>"
                ),
            ],
            add_arguments=_add_campaign_monitor_content_add_arguments,
            build_arguments=_build_campaign_monitor_content_add_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+content-remove",
            summary=(
                "Remove one content record from a campaign monitor. This only removes "
                "the collection record from the campaign monitor (soft delete), it does "
                "NOT delete the original social-platform post; explicit operator "
                "confirmation is required before running with --yes. The "
                "collection_content_id comes from the +content-list response, and the "
                "response includes removed / missing detail."
            ),
            risk_level="destructive",
            requires_confirmation=True,
            supports_dry_run=True,
            execution="direct",
            adapter_tool_name="campaign_monitor_content_remove",
            input_schema=_campaign_monitor_content_remove_input_schema(),
            output_schema=_direct_output_schema(
                "Campaign monitor content removal payload returned by Museon API."
            ),
            examples=[
                (
                    "museoncli campaign-monitor +content-remove --id <campaign_id> "
                    "--collection-content-id <collection_content_id> --dry-run"
                ),
            ],
            add_arguments=_add_campaign_monitor_content_remove_arguments,
            build_arguments=_build_campaign_monitor_content_remove_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+content-batch-remove",
            summary=(
                "Remove content records from a campaign monitor in batch. This only "
                "removes the collection record from the campaign monitor (soft delete), "
                "it does NOT delete the original social-platform post; explicit "
                "operator confirmation is required before running with --yes. Batch "
                "size <=100, split into multiple batches if exceeded; response includes "
                "removed / missing detail; collection_content_id comes from the "
                "+content-list response."
            ),
            risk_level="destructive",
            requires_confirmation=True,
            supports_dry_run=True,
            execution="direct",
            adapter_tool_name="campaign_monitor_content_batch_remove",
            input_schema=_campaign_monitor_content_batch_remove_input_schema(),
            output_schema=_direct_output_schema(
                "Campaign monitor batch content removal payload returned by Museon API."
            ),
            examples=[
                (
                    "museoncli campaign-monitor +content-batch-remove --id <campaign_id> "
                    "--collection-content-ids <collection_content_id_1>,<collection_content_id_2> "
                    "--dry-run"
                ),
            ],
            add_arguments=_add_campaign_monitor_content_batch_remove_arguments,
            build_arguments=_build_campaign_monitor_content_batch_remove_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+summary",
            summary="Read campaign monitor level performance summary.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="campaign_monitor_summary",
            input_schema=_campaign_monitor_summary_input_schema(),
            output_schema=_direct_output_schema(
                "Campaign monitor summary payload returned by Museon API."
            ),
            examples=[
                (
                    "museoncli campaign-monitor +summary --id <campaign_id> "
                    "--date-from 2026-06-01 --date-to 2026-06-08"
                ),
            ],
            add_arguments=_add_campaign_monitor_summary_arguments,
            build_arguments=_build_campaign_monitor_summary_arguments,
        ),
    ]


# ---- executors (generated from main.py direct_* chains) ----
async def _execute_content_remove(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    campaign_id = str(arguments.get("campaign_id") or "")
    collection_content_id = str(arguments.get("collection_content_id") or "")
    return agent_domain_result(
        await api_data(
            cfg,
            "POST",
            f"/agent-cli/campaign-monitors/{campaign_id}/content/batch-remove",
            json_body={
                "workspace_id": workspace_id,
                "payload": {"collection_content_ids": [collection_content_id]},
            },
        )
    )


async def _execute_content_batch_remove(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    campaign_id = str(arguments.get("campaign_id") or "")
    raw_ids = arguments.get("collection_content_ids")
    if isinstance(raw_ids, list):
        collection_content_ids = _dedupe_collection_content_ids(raw_ids)
    else:
        collection_content_ids = _collection_content_ids_csv(str(raw_ids or ""))
    return agent_domain_result(
        await api_data(
            cfg,
            "POST",
            f"/agent-cli/campaign-monitors/{campaign_id}/content/batch-remove",
            json_body={
                "workspace_id": workspace_id,
                "payload": {"collection_content_ids": collection_content_ids},
            },
        )
    )


async def _execute_content_list(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    base_params = {"workspace_id": workspace_id}
    campaign_id = str(arguments.get("campaign_id") or "")
    date_params = {
        **base_params,
        "date_from": arguments.get("date_from"),
        "date_to": arguments.get("date_to"),
    }
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/campaign-monitors/{campaign_id}/content",
            params=compact_params(
                {
                    **date_params,
                    "page": arguments.get("page", 1),
                    "page_size": arguments.get("page_size", 20),
                    "search": arguments.get("search"),
                    "platform": arguments.get("platform"),
                    "sort": arguments.get("sort"),
                    "creator_id": arguments.get("creator_id"),
                }
            ),
        )
    )


async def _execute_creator_list(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    base_params = {"workspace_id": workspace_id}
    campaign_id = str(arguments.get("campaign_id") or "")
    date_params = {
        **base_params,
        "date_from": arguments.get("date_from"),
        "date_to": arguments.get("date_to"),
    }
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/campaign-monitors/{campaign_id}/creators",
            params=compact_params(
                {
                    **date_params,
                    "page": arguments.get("page", 1),
                    "page_size": arguments.get("page_size", 20),
                    "search": arguments.get("search"),
                    "platform": arguments.get("platform"),
                    "sort": arguments.get("sort"),
                }
            ),
        )
    )


async def _execute_get(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    base_params = {"workspace_id": workspace_id}
    campaign_id = str(arguments.get("campaign_id") or "")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/campaign-monitors/{campaign_id}",
            params=base_params,
        )
    )


async def _execute_list(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    base_params = {"workspace_id": workspace_id}
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            "/agent-cli/campaign-monitors",
            params=compact_params(
                {
                    **base_params,
                    "search": arguments.get("search"),
                    "timezone": arguments.get("timezone"),
                    "sort": arguments.get("sort"),
                    "page": arguments.get("page", 1),
                    "limit": arguments.get("page_size", 50),
                }
            ),
        )
    )


async def _execute_summary(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    base_params = {"workspace_id": workspace_id}
    campaign_id = str(arguments.get("campaign_id") or "")
    date_params = {
        **base_params,
        "date_from": arguments.get("date_from"),
        "date_to": arguments.get("date_to"),
    }
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/campaign-monitors/{campaign_id}/summary",
            params=compact_params(
                {
                    **date_params,
                    "granularity": arguments.get("granularity", "day"),
                    "search": arguments.get("search"),
                    "platform": arguments.get("platform"),
                    "metrics": arguments.get("metrics"),
                    "creator_id": arguments.get("creator_id"),
                }
            ),
        )
    )


async def _execute_creator_add(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    campaign_id = str(arguments.get("campaign_id") or "")
    payload = compact_params(
        {
            "creator_urls": arguments.get("creator_urls"),
            "creator_ids": arguments.get("creator_ids"),
            "hashtags": arguments.get("hashtags"),
        }
    )
    if arguments.get("sync") is not None:
        payload["sync"] = bool(arguments["sync"])
    return agent_domain_result(
        await api_data(
            cfg,
            "POST",
            f"/agent-cli/campaign-monitors/{campaign_id}/creators",
            json_body={"workspace_id": workspace_id, "payload": payload},
        )
    )


async def _execute_creator_remove(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    campaign_id = str(arguments.get("campaign_id") or "")
    creator_social_account_id = str(arguments.get("creator_social_account_id") or "")
    return agent_domain_result(
        await api_data(
            cfg,
            "POST",
            f"/agent-cli/campaign-monitors/{campaign_id}/creators/{creator_social_account_id}/remove",
            json_body={"workspace_id": workspace_id, "payload": {}},
        )
    )


async def _execute_content_add(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    campaign_id = str(arguments.get("campaign_id") or "")
    payload = compact_params(
        {
            "content_urls": arguments.get("content_urls"),
            "content_ids": arguments.get("content_ids"),
        }
    )
    if arguments.get("sync") is not None:
        payload["sync"] = bool(arguments["sync"])
    return agent_domain_result(
        await api_data(
            cfg,
            "POST",
            f"/agent-cli/campaign-monitors/{campaign_id}/content",
            json_body={"workspace_id": workspace_id, "payload": payload},
        )
    )


def _dedupe_collection_content_ids(raw_ids: list[Any]) -> list[str]:
    collection_content_ids: list[str] = []
    seen: set[str] = set()
    for raw_id in raw_ids:
        collection_content_id = str(raw_id).strip()
        if collection_content_id and collection_content_id not in seen:
            seen.add(collection_content_id)
            collection_content_ids.append(collection_content_id)
    return collection_content_ids


EXECUTORS = {
    "campaign-monitor.content-add": direct_enveloped(_execute_content_add),
    "campaign-monitor.content-batch-remove": direct_enveloped(_execute_content_batch_remove),
    "campaign-monitor.content-list": direct_enveloped(_execute_content_list),
    "campaign-monitor.content-remove": direct_enveloped(_execute_content_remove),
    "campaign-monitor.creator-add": direct_enveloped(_execute_creator_add),
    "campaign-monitor.creator-list": direct_enveloped(_execute_creator_list),
    "campaign-monitor.creator-remove": direct_enveloped(_execute_creator_remove),
    "campaign-monitor.get": direct_enveloped(_execute_get),
    "campaign-monitor.list": direct_enveloped(_execute_list),
    "campaign-monitor.summary": direct_enveloped(_execute_summary),
}
