"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

from museoncli.domains._shared import dekebab, kebab_choices

from museoncli.execution import agent_domain_result

from museoncli.execution import (
    CommandContext,
    direct_enveloped,
)

import argparse
from typing import Any
from museoncli.domains._model import CommandSpec, Domain
from museoncli.domains._shared import (
    _add_common_adapter_arguments,
    _direct_output_schema,
    _load_structured_args,
    _uuid_id_schema,
    _without_none,
)


CONTENT_ANALYSIS_TYPE_CHOICES = ["content-analysis", "reverse-ai-prompt"]


CONTENT_ANALYSIS_SOURCE_TYPE_CHOICES = ["upload", "platform_link"]


CONTENT_ANALYSIS_MEDIA_TYPE_CHOICES = ["video"]


def _add_content_analysis_run_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--type", choices=CONTENT_ANALYSIS_TYPE_CHOICES, required=True)
    parser.add_argument("--url")
    parser.add_argument("--media-id")
    parser.add_argument("--file")
    parser.add_argument(
        "--media-type", choices=CONTENT_ANALYSIS_MEDIA_TYPE_CHOICES, default="video"
    )
    parser.add_argument("--title")
    parser.add_argument("--description")
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--wait", action="store_true")
    parser.add_argument("--timeout", type=int, default=60)
    parser.add_argument("--poll-interval", type=float, default=2.0)
    parser.add_argument("--dry-run", action="store_true")


def _build_content_analysis_run_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload["type"] = args.type
    source_fields = [
        bool(args.url),
        bool(args.media_id),
        bool(args.file),
    ]
    if sum(source_fields) != 1:
        raise ValueError(
            "content-analysis +run requires exactly one source: --url, --media-id, or --file."
        )
    payload.update(
        _without_none(
            {
                "url": args.url,
                "media_id": args.media_id,
                "file": args.file,
                "media_type": args.media_type if args.file else None,
                "title": args.title,
                "description": args.description,
                "force_reanalysis": args.force,
                "wait": args.wait,
                "wait_timeout_seconds": args.timeout,
                "poll_interval_seconds": args.poll_interval,
            }
        )
    )
    return payload


def _add_content_analysis_get_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", dest="run_id", required=True)


def _build_content_analysis_get_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload["run_id"] = args.run_id
    return payload


def _add_content_analysis_list_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--type", choices=CONTENT_ANALYSIS_TYPE_CHOICES)
    parser.add_argument(
        "--source-type", choices=kebab_choices(CONTENT_ANALYSIS_SOURCE_TYPE_CHOICES)
    )
    parser.add_argument("--search")
    parser.add_argument("--page", type=int, default=1)
    parser.add_argument("--page-size", type=int, default=20)


def _build_content_analysis_list_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update(
        _without_none(
            {
                "type": args.type,
                "source_type": dekebab(args.source_type),
                "search": args.search,
                "page": args.page,
                "page_size": args.page_size,
            }
        )
    )
    return payload


def _content_analysis_run_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "type": {
                "type": "string",
                "enum": CONTENT_ANALYSIS_TYPE_CHOICES,
                "description": "content-analysis maps to content_direction; reverse-ai-prompt maps to reverse_prompt.",
            },
            "url": {"type": ["string", "null"]},
            "media_id": _uuid_id_schema("Existing Museon media UUID."),
            "file": {
                "type": ["string", "null"],
                "description": "Local file path. The CLI uploads it first and passes media_id to the API.",
            },
            "media_type": {
                "type": "string",
                "enum": CONTENT_ANALYSIS_MEDIA_TYPE_CHOICES,
                "default": "video",
                "description": (
                    "Agent CLI Content Analyzer only supports video. Use format/topic "
                    "asset workflows for image, carousel, slideshow, or static post analysis."
                ),
            },
            "title": {"type": ["string", "null"]},
            "description": {"type": ["string", "null"]},
            "force_reanalysis": {"type": "boolean", "default": False},
            "wait": {"type": "boolean", "default": False},
            "wait_timeout_seconds": {
                "type": "integer",
                "minimum": 1,
                "maximum": 300,
                "default": 60,
            },
            "poll_interval_seconds": {
                "type": "number",
                "minimum": 0.25,
                "maximum": 10,
                "default": 2,
            },
        },
        "required": ["type"],
        "oneOf": [
            {"required": ["url"]},
            {"required": ["media_id"]},
            {"required": ["file"]},
        ],
    }


def _content_analysis_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "run_id": _uuid_id_schema("Content Analyzer history run UUID."),
        },
        "required": ["run_id"],
    }


def _content_analysis_list_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "type": {"type": ["string", "null"], "enum": [*CONTENT_ANALYSIS_TYPE_CHOICES, None]},
            "source_type": {
                "type": ["string", "null"],
                "enum": [*kebab_choices(CONTENT_ANALYSIS_SOURCE_TYPE_CHOICES), None],
            },
            "search": {"type": ["string", "null"]},
            "page": {"type": "integer", "minimum": 1, "default": 1},
            "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 20},
        },
        "required": [],
    }


def specs() -> list[CommandSpec]:
    return [
        CommandSpec(
            domain=Domain.CONTENT_ANALYSIS,
            shortcut="+run",
            summary=(
                "Run video-only Content Analyzer for a platform URL, uploaded Museon media ID, "
                "or local video file upload."
            ),
            risk_level="write",
            execution="async_run",
            adapter_tool_name="content_analysis_run",
            input_schema=_content_analysis_run_input_schema(),
            output_schema=_direct_output_schema(
                "Content Analyzer run payload. Completed cached or waited runs include "
                "public_token and share_url for the public result page."
            ),
            examples=[
                (
                    "museoncli content-analysis +run --type content-analysis "
                    "--url https://www.tiktok.com/@creator/video/123"
                ),
                (
                    "museoncli content-analysis +run --type reverse-ai-prompt "
                    "--file ./creative.mp4 --media-type video --wait"
                ),
                (
                    "museoncli content-analysis +run --type content-analysis "
                    "--media-id <media_id> --force"
                ),
            ],
            add_arguments=_add_content_analysis_run_arguments,
            build_arguments=_build_content_analysis_run_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.CONTENT_ANALYSIS,
            shortcut="+get",
            summary="Read one Content Analyzer run by ID.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="content_analysis_get",
            input_schema=_content_analysis_get_input_schema(),
            output_schema=_direct_output_schema(
                "Content Analyzer run detail returned by Museon API. Completed runs include "
                "public_token and share_url for the public result page."
            ),
            examples=[
                "museoncli content-analysis +get --id <run_id>",
            ],
            add_arguments=_add_content_analysis_get_arguments,
            build_arguments=_build_content_analysis_get_arguments,
        ),
        CommandSpec(
            domain=Domain.CONTENT_ANALYSIS,
            shortcut="+list",
            summary="List Content Analyzer runs in the selected workspace.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="content_analysis_list",
            input_schema=_content_analysis_list_input_schema(),
            output_schema=_direct_output_schema(
                "Content Analyzer run list returned by Museon API."
            ),
            examples=[
                "museoncli content-analysis +list --type content-analysis --page-size 10",
                "museoncli content-analysis +list --source-type upload --search skincare",
            ],
            add_arguments=_add_content_analysis_list_arguments,
            build_arguments=_build_content_analysis_list_arguments,
        ),
    ]


# ---- executors (generated from main.py direct_* chains) ----
async def _execute_get(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    run_id = str(arguments.get("run_id") or "")
    if not run_id:
        raise RuntimeError("content-analysis +get requires --id")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/content-analysis/runs/{run_id}",
            params={"workspace_id": workspace_id},
        )
    )


async def _execute_list(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            "/agent-cli/content-analysis/runs",
            params={"workspace_id": workspace_id, **arguments},
        )
    )


async def _execute_run(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    upload_media_file = ctx.upload_media_file
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    payload = dict(arguments)
    file_path = payload.pop("file", None)
    if file_path:
        upload_response = await upload_media_file(
            cfg,
            workspace_id=workspace_id,
            arguments={
                key: value
                for key, value in {
                    "file": file_path,
                    "media_type": payload.pop("media_type", "video"),
                    "title": payload.pop("title", None),
                    "description": payload.pop("description", None),
                }.items()
                if value is not None
            },
        )
        payload["media_id"] = uploaded_media_id(upload_response)
    return agent_domain_result(
        await api_data(
            cfg,
            "POST",
            "/agent-cli/content-analysis/runs",
            json_body={"workspace_id": workspace_id, "payload": payload},
        )
    )


EXECUTORS = {
    "content-analysis.get": direct_enveloped(_execute_get),
    "content-analysis.list": direct_enveloped(_execute_list),
    "content-analysis.run": direct_enveloped(_execute_run),
}


def uploaded_media_id(response: Any) -> str:
    if not isinstance(response, dict):
        raise RuntimeError("media upload did not return a JSON object")
    candidates: list[Any] = [
        response.get("media_id"),
        response.get("id"),
    ]
    data = response.get("data")
    if isinstance(data, dict):
        candidates.extend([data.get("media_id"), data.get("id")])
        asset = data.get("asset")
        if isinstance(asset, dict):
            candidates.extend([asset.get("media_id"), asset.get("id")])
    asset = response.get("asset")
    if isinstance(asset, dict):
        candidates.extend([asset.get("media_id"), asset.get("id")])
    for candidate in candidates:
        if candidate:
            return str(candidate)
    raise RuntimeError("media upload response did not include media_id")
