"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

from museoncli.execution import compact_params

from museoncli.execution import (
    CommandContext,
    direct_enveloped,
)

import argparse
from pathlib import Path
from typing import Any
from museoncli.domains._model import CommandSpec, Domain
from museoncli.domains._shared import (
    _direct_output_schema,
    _json_object,
    _uuid_id_schema,
    _without_none,
)


EVALUATOR_PROMPT_MAX_LENGTH = 20000


EVALUATOR_TEXT_MAX_LENGTH = 50000


def _add_evaluator_scope_argument(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--workspace-id")


def _add_evaluator_list_filter_arguments(parser: argparse.ArgumentParser) -> None:
    _add_evaluator_scope_argument(parser)
    parser.add_argument("--kind")
    parser.add_argument("--include-inactive", action="store_true")
    parser.add_argument("--include-private", action="store_true")
    parser.add_argument("--limit", type=int, default=50)


def _add_evaluator_kind_list_arguments(parser: argparse.ArgumentParser) -> None:
    _add_evaluator_scope_argument(parser)
    parser.add_argument("--include-inactive", action="store_true")
    parser.add_argument("--include-private", action="store_true")
    parser.add_argument("--limit", type=int, default=50)


def _build_evaluator_kind_list_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "include_inactive": args.include_inactive,
        "include_private": args.include_private,
        "limit": args.limit,
    }


def _add_evaluator_list_arguments(parser: argparse.ArgumentParser) -> None:
    _add_evaluator_list_filter_arguments(parser)


def _build_evaluator_list_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return _without_none(
        {
            "kind": args.kind,
            "include_inactive": args.include_inactive,
            "include_private": args.include_private,
            "limit": args.limit,
        }
    )


def _add_evaluator_get_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--id", dest="evaluator_type_id", required=True)


def _build_evaluator_get_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {"evaluator_type_id": args.evaluator_type_id}


def _add_evaluator_create_arguments(parser: argparse.ArgumentParser) -> None:
    _add_evaluator_scope_argument(parser)
    parser.add_argument("--kind", required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--is-public", action=argparse.BooleanOptionalAction, default=False)
    prompt = parser.add_mutually_exclusive_group(required=True)
    prompt.add_argument("--prompt")
    prompt.add_argument("--prompt-file")
    parser.add_argument("--dry-run", action="store_true")


def _build_evaluator_create_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "kind": args.kind,
        "name": args.name,
        "prompt": _evaluator_text_argument(
            args,
            value_attr="prompt",
            file_attr="prompt_file",
            field="prompt",
        ),
        "is_public": args.is_public,
    }


def _add_evaluator_update_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--id", dest="evaluator_type_id", required=True)
    parser.add_argument("--kind")
    parser.add_argument("--name")
    parser.add_argument("--is-active", action=argparse.BooleanOptionalAction, default=None)
    parser.add_argument("--is-public", action=argparse.BooleanOptionalAction, default=None)
    prompt = parser.add_mutually_exclusive_group()
    prompt.add_argument("--prompt")
    prompt.add_argument("--prompt-file")
    parser.add_argument("--dry-run", action="store_true")


def _build_evaluator_update_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload: dict[str, Any] = {"evaluator_type_id": args.evaluator_type_id}
    if args.kind is not None:
        payload["kind"] = args.kind
    if args.name is not None:
        payload["name"] = args.name
    if args.prompt is not None or args.prompt_file is not None:
        payload["prompt"] = _evaluator_text_argument(
            args,
            value_attr="prompt",
            file_attr="prompt_file",
            field="prompt",
        )
    if args.is_active is not None:
        payload["is_active"] = args.is_active
    if args.is_public is not None:
        payload["is_public"] = args.is_public
    return payload


def _add_evaluator_run_arguments(parser: argparse.ArgumentParser) -> None:
    _add_evaluator_scope_argument(parser)
    parser.add_argument("--id", dest="evaluator_type_id", required=True)
    parser.add_argument("--creative-research-snapshot-id")
    parser.add_argument("--slideshow-generation-id")
    text = parser.add_mutually_exclusive_group()
    text.add_argument("--text")
    text.add_argument("--text-file")
    parser.add_argument("--media-id", dest="media_ids", action="append")
    extra_context = parser.add_mutually_exclusive_group()
    extra_context.add_argument("--extra-context-json")
    extra_context.add_argument("--extra-context-file")
    parser.add_argument("--dry-run", action="store_true")


def _build_evaluator_run_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _without_none(
        {
            "evaluator_type_id": args.evaluator_type_id,
            "creative_research_snapshot_id": args.creative_research_snapshot_id,
            "slideshow_generation_id": args.slideshow_generation_id,
            "media_ids": list(args.media_ids) if args.media_ids else None,
        }
    )
    if args.text is not None or args.text_file is not None:
        payload["text"] = _evaluator_text_argument(
            args,
            value_attr="text",
            file_attr="text_file",
            field="text",
        )
    if args.extra_context_json is not None or args.extra_context_file is not None:
        payload["extra_context"] = _evaluator_json_object_argument(
            args,
            value_attr="extra_context_json",
            file_attr="extra_context_file",
            field="extra_context",
        )
    return payload


def _add_evaluator_run_list_arguments(parser: argparse.ArgumentParser) -> None:
    _add_evaluator_scope_argument(parser)
    parser.add_argument("--kind")
    parser.add_argument("--id", dest="evaluator_type_id")
    parser.add_argument("--include-private", action="store_true")
    parser.add_argument("--limit", type=int, default=50)


def _build_evaluator_run_list_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return _without_none(
        {
            "kind": args.kind,
            "evaluator_type_id": args.evaluator_type_id,
            "include_private": args.include_private,
            "limit": args.limit,
        }
    )


def _add_evaluator_run_get_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--id", dest="run_id", required=True)


def _build_evaluator_run_get_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {"run_id": args.run_id}


def _evaluator_text_argument(
    args: argparse.Namespace,
    *,
    value_attr: str,
    file_attr: str,
    field: str,
) -> str:
    _ = field
    value = getattr(args, value_attr, None)
    if value is not None:
        return str(value)
    file_value = getattr(args, file_attr, None)
    if file_value is None:
        return ""
    return Path(file_value).read_text(encoding="utf-8")


def _evaluator_json_object_argument(
    args: argparse.Namespace,
    *,
    value_attr: str,
    file_attr: str,
    field: str,
) -> dict[str, Any] | None:
    value = getattr(args, value_attr, None)
    if value is not None:
        return _json_object(value, flag=f"--{field.replace('_', '-')}-json")
    file_value = getattr(args, file_attr, None)
    if file_value is not None:
        raw = Path(file_value).read_text(encoding="utf-8")
        return _json_object(raw, flag=f"--{field.replace('_', '-')}-file")
    return None


def _evaluator_kind_list_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "include_inactive": {"type": "boolean", "default": False},
            "include_private": {"type": "boolean", "default": False},
            "limit": {"type": "integer", "minimum": 1, "maximum": 100, "default": 50},
        },
        "required": [],
    }


def _evaluator_list_input_schema() -> dict[str, Any]:
    schema = _evaluator_kind_list_input_schema()
    schema["properties"] = {
        "kind": {"type": ["string", "null"], "minLength": 1, "maxLength": 80},
        **schema["properties"],
    }
    return schema


def _evaluator_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "evaluator_type_id": _uuid_id_schema("Evaluator definition UUID returned by +list.")
        },
        "required": ["evaluator_type_id"],
    }


def _evaluator_create_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "kind": {
                "type": "string",
                "minLength": 1,
                "maxLength": 80,
                "pattern": "^[a-z0-9][a-z0-9_-]{0,79}$",
                "description": (
                    "Open evaluator type key, for example official_account_research "
                    "or content_generation."
                ),
            },
            "name": {"type": "string", "minLength": 1, "maxLength": 120},
            "prompt": {
                "type": "string",
                "minLength": 1,
                "maxLength": EVALUATOR_PROMPT_MAX_LENGTH,
            },
            "is_public": {"type": "boolean", "default": False},
        },
        "required": ["kind", "name", "prompt"],
    }


def _evaluator_update_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "evaluator_type_id": _uuid_id_schema("Evaluator definition UUID returned by +list."),
            "kind": {
                "type": ["string", "null"],
                "minLength": 1,
                "maxLength": 80,
                "pattern": "^[a-z0-9][a-z0-9_-]{0,79}$",
            },
            "name": {"type": ["string", "null"], "minLength": 1, "maxLength": 120},
            "prompt": {
                "type": ["string", "null"],
                "minLength": 1,
                "maxLength": EVALUATOR_PROMPT_MAX_LENGTH,
            },
            "is_active": {"type": ["boolean", "null"]},
            "is_public": {"type": ["boolean", "null"]},
        },
        "required": ["evaluator_type_id"],
    }


def _evaluator_run_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "evaluator_type_id": _uuid_id_schema("Evaluator definition UUID returned by +list."),
            "creative_research_snapshot_id": {
                "type": ["string", "null"],
                "format": "uuid",
            },
            "slideshow_generation_id": {
                "type": ["string", "null"],
                "format": "uuid",
            },
            "text": {
                "type": ["string", "null"],
                "minLength": 1,
                "maxLength": EVALUATOR_TEXT_MAX_LENGTH,
            },
            "media_ids": {
                "type": "array",
                "items": _uuid_id_schema("Media UUID."),
                "maxItems": 50,
                "default": [],
            },
            "extra_context": {"type": "object", "default": {}},
        },
        "required": ["evaluator_type_id"],
    }


def _evaluator_run_list_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "kind": {"type": ["string", "null"], "minLength": 1, "maxLength": 80},
            "evaluator_type_id": _uuid_id_schema("Optional evaluator definition UUID filter.")
            | {"type": ["string", "null"]},
            "include_private": {"type": "boolean", "default": False},
            "limit": {"type": "integer", "minimum": 1, "maximum": 100, "default": 50},
        },
        "required": [],
    }


def _evaluator_run_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {"run_id": _uuid_id_schema("Evaluator run UUID returned by +run.")},
        "required": ["run_id"],
    }


def specs() -> list[CommandSpec]:
    return [
        CommandSpec(
            domain=Domain.EVALUATOR,
            shortcut="+kind-list",
            summary="List evaluator kind keys configured in the current workspace.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="evaluator_kind_list",
            input_schema=_evaluator_kind_list_input_schema(),
            output_schema=_direct_output_schema("Evaluator kind options returned by Museon API."),
            examples=["museoncli evaluator +kind-list --include-private"],
            add_arguments=_add_evaluator_kind_list_arguments,
            build_arguments=_build_evaluator_kind_list_arguments,
        ),
        CommandSpec(
            domain=Domain.EVALUATOR,
            shortcut="+list",
            summary="List evaluator definitions available to the current agent runtime.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="evaluator_list",
            input_schema=_evaluator_list_input_schema(),
            output_schema=_direct_output_schema("Evaluator catalog returned by Museon API."),
            examples=["museoncli evaluator +list --kind content_generation"],
            add_arguments=_add_evaluator_list_arguments,
            build_arguments=_build_evaluator_list_arguments,
        ),
        CommandSpec(
            domain=Domain.EVALUATOR,
            shortcut="+get",
            summary="Read one evaluator definition by ID.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="evaluator_get",
            input_schema=_evaluator_get_input_schema(),
            output_schema=_direct_output_schema("Evaluator detail returned by Museon API."),
            examples=["museoncli evaluator +get --id <evaluator_type_id>"],
            add_arguments=_add_evaluator_get_arguments,
            build_arguments=_build_evaluator_get_arguments,
        ),
        CommandSpec(
            domain=Domain.EVALUATOR,
            shortcut="+create",
            summary="Create one prompt-based evaluator definition.",
            risk_level="write",
            execution="direct",
            adapter_tool_name="evaluator_create",
            input_schema=_evaluator_create_input_schema(),
            output_schema=_direct_output_schema("Created evaluator detail returned by Museon API."),
            examples=[
                (
                    "museoncli evaluator +create --kind content_generation "
                    "--name 'Content quality' --prompt-file ./evaluator.md"
                )
            ],
            add_arguments=_add_evaluator_create_arguments,
            build_arguments=_build_evaluator_create_arguments,
            supports_dry_run=True,
            required_roles=("workspace_admin_or_staff",),
        ),
        CommandSpec(
            domain=Domain.EVALUATOR,
            shortcut="+update",
            summary="Update an evaluator definition's prompt, metadata, or visibility.",
            risk_level="write",
            execution="direct",
            adapter_tool_name="evaluator_update",
            input_schema=_evaluator_update_input_schema(),
            output_schema=_direct_output_schema("Updated evaluator detail returned by Museon API."),
            examples=[
                (
                    "museoncli evaluator +update --id <evaluator_type_id> "
                    "--prompt-file ./evaluator.md --no-is-public"
                )
            ],
            add_arguments=_add_evaluator_update_arguments,
            build_arguments=_build_evaluator_update_arguments,
            supports_dry_run=True,
            required_roles=("workspace_admin_or_staff",),
        ),
        CommandSpec(
            domain=Domain.EVALUATOR,
            shortcut="+run",
            summary="Run an evaluator against text, media, research, or generation output.",
            risk_level="write",
            execution="direct",
            adapter_tool_name="evaluator_run",
            input_schema=_evaluator_run_input_schema(),
            output_schema=_direct_output_schema("Evaluator run result returned by Museon API."),
            examples=[
                (
                    "museoncli evaluator +run --id <evaluator_type_id> "
                    "--slideshow-generation-id <generation_id>"
                ),
                "museoncli evaluator +run --id <evaluator_type_id> --text-file ./output.txt",
            ],
            add_arguments=_add_evaluator_run_arguments,
            build_arguments=_build_evaluator_run_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.EVALUATOR,
            shortcut="+run-list",
            summary="List evaluator runs for the current workspace.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="evaluator_run_list",
            input_schema=_evaluator_run_list_input_schema(),
            output_schema=_direct_output_schema("Evaluator run list returned by Museon API."),
            examples=["museoncli evaluator +run-list --kind official_account_research"],
            add_arguments=_add_evaluator_run_list_arguments,
            build_arguments=_build_evaluator_run_list_arguments,
        ),
        CommandSpec(
            domain=Domain.EVALUATOR,
            shortcut="+run-get",
            summary="Read one evaluator run by ID.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="evaluator_run_get",
            input_schema=_evaluator_run_get_input_schema(),
            output_schema=_direct_output_schema("Evaluator run detail returned by Museon API."),
            examples=["museoncli evaluator +run-get --id <run_id>"],
            add_arguments=_add_evaluator_run_get_arguments,
            build_arguments=_build_evaluator_run_get_arguments,
        ),
    ]


# ---- executors (generated from main.py direct_* chains) ----
async def _execute_create(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    payload = {
        "workspace_id": workspace_id,
        "kind": arguments.get("kind"),
        "name": arguments.get("name"),
        "prompt": arguments.get("prompt"),
        "is_public": bool(arguments.get("is_public", False)),
    }
    return _redact_evaluator_model_config(
        await api_data(cfg, "POST", "/agent-cli/evaluators", json_body=payload)
    )


async def _execute_get(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    api_data = ctx.api_data
    evaluator_type_id = _required_evaluator_type_id(arguments)
    return _redact_evaluator_model_config(
        await api_data(cfg, "GET", f"/agent-cli/evaluators/{evaluator_type_id}")
    )


async def _execute_kind_list(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    return _redact_evaluator_model_config(
        await api_data(
            cfg,
            "GET",
            "/agent-cli/evaluators/kinds",
            params=compact_params(
                {
                    "workspace_id": workspace_id,
                    "include_inactive": arguments.get("include_inactive", False),
                    "include_private": arguments.get("include_private", False),
                    "limit": arguments.get("limit", 50),
                }
            ),
        )
    )


async def _execute_list(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    return _redact_evaluator_model_config(
        await api_data(
            cfg,
            "GET",
            "/agent-cli/evaluators",
            params=compact_params(
                {
                    "workspace_id": workspace_id,
                    "kind": arguments.get("kind"),
                    "include_inactive": arguments.get("include_inactive", False),
                    "include_private": arguments.get("include_private", False),
                    "limit": arguments.get("limit", 50),
                }
            ),
        )
    )


async def _execute_run(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    evaluator_type_id = _required_evaluator_type_id(arguments)
    payload = {
        key: value
        for key, value in arguments.items()
        if key != "evaluator_type_id" and value is not None
    }
    return _redact_evaluator_model_config(
        await api_data(
            cfg,
            "POST",
            f"/agent-cli/evaluators/{evaluator_type_id}/runs",
            json_body=payload,
            params=compact_params({"workspace_id": workspace_id}),
        )
    )


async def _execute_run_get(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    api_data = ctx.api_data
    run_id = str(arguments.get("run_id") or "")
    if not run_id:
        raise RuntimeError("missing_evaluator_run_id")
    return _redact_evaluator_model_config(
        await api_data(cfg, "GET", f"/agent-cli/evaluator-runs/{run_id}")
    )


async def _execute_run_list(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    return _redact_evaluator_model_config(
        await api_data(
            cfg,
            "GET",
            "/agent-cli/evaluator-runs",
            params=compact_params(
                {
                    "workspace_id": workspace_id,
                    "kind": arguments.get("kind"),
                    "evaluator_type_id": arguments.get("evaluator_type_id"),
                    "include_private": arguments.get("include_private", False),
                    "limit": arguments.get("limit", 50),
                }
            ),
        )
    )


async def _execute_update(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    api_data = ctx.api_data
    evaluator_type_id = _required_evaluator_type_id(arguments)
    payload = {
        key: value
        for key, value in arguments.items()
        if key != "evaluator_type_id" and value is not None
    }
    return _redact_evaluator_model_config(
        await api_data(
            cfg,
            "PATCH",
            f"/agent-cli/evaluators/{evaluator_type_id}",
            json_body=payload,
        )
    )


EXECUTORS = {
    "evaluator.create": direct_enveloped(_execute_create),
    "evaluator.get": direct_enveloped(_execute_get),
    "evaluator.kind-list": direct_enveloped(_execute_kind_list),
    "evaluator.list": direct_enveloped(_execute_list),
    "evaluator.run": direct_enveloped(_execute_run),
    "evaluator.run-get": direct_enveloped(_execute_run_get),
    "evaluator.run-list": direct_enveloped(_execute_run_list),
    "evaluator.update": direct_enveloped(_execute_update),
}


def _required_evaluator_type_id(arguments: dict[str, Any]) -> str:
    evaluator_type_id = str(arguments.get("evaluator_type_id") or "")
    if not evaluator_type_id:
        raise RuntimeError("missing_evaluator_type_id")
    return evaluator_type_id


_SENSITIVE_EVALUATOR_MODEL_FIELDS = {"model_config", "model_config_snapshot"}


def _redact_evaluator_model_config(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            key: _redact_evaluator_model_config(item)
            for key, item in value.items()
            if key not in _SENSITIVE_EVALUATOR_MODEL_FIELDS
        }
    if isinstance(value, list):
        return [_redact_evaluator_model_config(item) for item in value]
    return value
