"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

from museoncli.execution import adapter_executor

import argparse
from typing import Any
from museoncli.domains._model import CommandSpec, Domain
from museoncli.domains._shared import (
    _add_common_adapter_arguments,
    _async_output_schema,
    _direct_output_schema,
    _json_object,
    _load_structured_args,
    _without_none,
)


GENERATION_TYPE_CHOICES = ["slideshow"]


def _add_generation_create_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--type", choices=GENERATION_TYPE_CHOICES, default="slideshow")
    parser.add_argument("--schedule-item-id")
    parser.add_argument("--account-id", dest="pool_account_id")
    parser.add_argument("--pool-account-id", dest="pool_account_id")
    parser.add_argument("--format-id")
    parser.add_argument("--topic-id", dest="content_topic_id")
    parser.add_argument("--content-topic-id", dest="content_topic_id")
    parser.add_argument("--persona-id")
    parser.add_argument("--product-id")
    parser.add_argument("--notes", default="")
    parser.add_argument("--custom-prompt")
    parser.add_argument("--text-model")
    parser.add_argument("--image-model")
    parser.add_argument("--slice-model")
    parser.add_argument("--metadata-json")
    parser.add_argument("--dry-run", action="store_true")


def _build_generation_create_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    if args.metadata_json:
        payload["metadata"] = _json_object(args.metadata_json, flag="--metadata-json")
    custom_prompt = args.custom_prompt if args.custom_prompt is not None else args.notes
    payload.update(
        _without_none(
            {
                "type": args.type,
                "schedule_item_id": args.schedule_item_id,
                "pool_account_id": args.pool_account_id,
                "format_id": args.format_id,
                "content_topic_id": args.content_topic_id,
                "persona_id": args.persona_id,
                "product_id": args.product_id,
                "custom_prompt": custom_prompt.strip() if custom_prompt else None,
                "text_model": args.text_model,
                "image_model": args.image_model,
                "slice_model": args.slice_model,
            }
        )
    )
    _validate_generation_create_source(payload)
    return payload


def _validate_generation_create_source(payload: dict[str, Any]) -> None:
    has_schedule_item = bool(payload.get("schedule_item_id"))
    has_pool_account = bool(payload.get("pool_account_id"))
    explicit_fields = [
        "format_id",
        "content_topic_id",
        "persona_id",
        "product_id",
    ]
    if has_schedule_item:
        if has_pool_account or any(payload.get(key) for key in explicit_fields):
            raise ValueError(
                "generation +create cannot mix --schedule-item-id with explicit assets."
            )
        return
    if has_pool_account:
        if not payload.get("format_id") or not payload.get("content_topic_id"):
            raise ValueError(
                "generation +create with --account-id requires --format-id and --topic-id."
            )
        if payload.get("persona_id") or payload.get("product_id"):
            raise ValueError(
                "generation +create cannot mix --account-id with --persona-id or --product-id."
            )
        return
    if (
        not payload.get("format_id")
        or not payload.get("content_topic_id")
        or not payload.get("persona_id")
    ):
        raise ValueError("generation +create requires --format-id, --topic-id, and --persona-id.")


def _add_generation_get_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--type", choices=GENERATION_TYPE_CHOICES, default="slideshow")
    parser.add_argument("--id", dest="generation_id", required=True)


def _build_generation_get_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload["type"] = args.type
    payload["generation_id"] = args.generation_id
    return payload


def _add_generation_list_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--type", choices=GENERATION_TYPE_CHOICES, default="slideshow")
    parser.add_argument("--account-id", dest="pool_account_id")
    parser.add_argument("--pool-account-id", dest="pool_account_id")
    parser.add_argument("--schedule-item-id")
    parser.add_argument("--format-id")
    parser.add_argument("--topic-id", dest="content_topic_id")
    parser.add_argument("--content-topic-id", dest="content_topic_id")
    parser.add_argument("--persona-id")
    parser.add_argument("--product-id")
    parser.add_argument("--status")
    parser.add_argument("--has-persona", action="store_true")
    parser.add_argument("--created-from")
    parser.add_argument("--created-to")
    parser.add_argument("--page", type=int, default=1)
    parser.add_argument("--page-size", type=int, default=24)


def _build_generation_list_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update(
        _without_none(
            {
                "type": args.type,
                "pool_account_id": args.pool_account_id,
                "schedule_item_id": args.schedule_item_id,
                "format_id": args.format_id,
                "content_topic_id": args.content_topic_id,
                "persona_id": args.persona_id,
                "product_id": args.product_id,
                "status": args.status,
                "created_from": args.created_from,
                "created_to": args.created_to,
                "page": args.page,
                "page_size": args.page_size,
            }
        )
    )
    if args.has_persona:
        payload["has_persona"] = True
    return payload


def _generation_create_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "type": {
                "type": "string",
                "enum": GENERATION_TYPE_CHOICES,
                "default": "slideshow",
            },
            "schedule_item_id": {"type": ["string", "null"], "minLength": 1},
            "pool_account_id": {"type": ["string", "null"], "minLength": 1},
            "format_id": {"type": ["string", "null"], "minLength": 1},
            "content_topic_id": {"type": ["string", "null"], "minLength": 1},
            "persona_id": {"type": ["string", "null"], "minLength": 1},
            "product_id": {"type": ["string", "null"], "minLength": 1},
            "custom_prompt": {"type": "string", "maxLength": 4000},
            "text_model": {"type": ["string", "null"]},
            "image_model": {"type": ["string", "null"], "default": "gpt-image-2"},
            "slice_model": {"type": ["string", "null"]},
            "metadata": {"type": "object"},
            "dry_run": {"type": "boolean", "default": False},
        },
        "oneOf": [
            {"required": ["schedule_item_id"]},
            {"required": ["pool_account_id", "format_id", "content_topic_id"]},
            {"required": ["format_id", "content_topic_id", "persona_id"]},
        ],
    }


def _generation_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "type": {
                "type": "string",
                "enum": GENERATION_TYPE_CHOICES,
                "default": "slideshow",
            },
            "generation_id": {"type": "string", "minLength": 1},
        },
        "required": ["generation_id"],
    }


def _generation_list_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "type": {
                "type": "string",
                "enum": GENERATION_TYPE_CHOICES,
                "default": "slideshow",
            },
            "pool_account_id": {"type": ["string", "null"]},
            "schedule_item_id": {"type": ["string", "null"]},
            "format_id": {"type": ["string", "null"]},
            "content_topic_id": {"type": ["string", "null"]},
            "persona_id": {"type": ["string", "null"]},
            "product_id": {"type": ["string", "null"]},
            "status": {"type": ["string", "null"]},
            "has_persona": {"type": ["boolean", "null"]},
            "created_from": {"type": ["string", "null"], "format": "date-time"},
            "created_to": {"type": ["string", "null"], "format": "date-time"},
            "page": {"type": "integer", "minimum": 1, "default": 1},
            "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 24},
        },
    }


def specs() -> list[CommandSpec]:
    return [
        CommandSpec(
            domain=Domain.GENERATION,
            shortcut="+create",
            summary=(
                "Create and start one media generation — Museon's image-post (生图/图文) "
                "generation capability. Current type: slideshow, driven by format, topic, "
                "persona, and optional product assets. When the user asks to generate "
                "images or image posts but the workspace lacks these assets, do not "
                "refuse and do not ask the customer for asset IDs — follow the Content "
                "Replication flow to guide asset preparation first. Responses include a "
                "ready-made generation ref and a recommended wakeup delay. Present the ref "
                "in the current final response, tell the customer generation is in progress "
                "and the link shows live progress, then use the returned delay for the next "
                "status check instead of choosing one yourself."
            ),
            risk_level="write",
            execution="async_run",
            adapter_tool_name="generation_create",
            input_schema=_generation_create_input_schema(),
            output_schema=_async_output_schema(
                "Created slideshow generation returned by Museon API.",
                include_generation_guidance=True,
            ),
            examples=[
                (
                    "museoncli generation +create --type slideshow --format-id <format_id> "
                    "--topic-id <topic_id> --persona-id <persona_id> "
                    "--product-id <product_id>"
                ),
                (
                    "museoncli generation +create --type slideshow --format-id <format_id> "
                    "--topic-id <topic_id> --persona-id <persona_id> "
                    "--notes 'Focus on the before/after proof.'"
                ),
            ],
            add_arguments=_add_generation_create_arguments,
            build_arguments=_build_generation_create_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.GENERATION,
            shortcut="+get",
            summary=(
                "Read one media generation by id. Current type: slideshow. The response "
                "includes a ready-made generation ref; completed generations include "
                "grid_media, slide_media, and result_preview_image_urls when result media "
                "is available."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="generation_get",
            input_schema=_generation_get_input_schema(),
            output_schema=_direct_output_schema("Generation detail returned by Museon API."),
            examples=["museoncli generation +get --type slideshow --id <generation_id>"],
            add_arguments=_add_generation_get_arguments,
            build_arguments=_build_generation_get_arguments,
        ),
        CommandSpec(
            domain=Domain.GENERATION,
            shortcut="+list",
            summary=(
                "List media generations in the current workspace. Current type: slideshow. "
                "Each item includes a ready-made generation ref; completed generations "
                "include grid_media, slide_media, and result_preview_image_urls when "
                "result media is available."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="generation_list",
            input_schema=_generation_list_input_schema(),
            output_schema=_direct_output_schema("Generation list returned by Museon API."),
            examples=[
                "museoncli generation +list --type slideshow --status done --page-size 10",
                (
                    "museoncli generation +list --type slideshow "
                    "--format-id <format_id> --topic-id <topic_id>"
                ),
            ],
            add_arguments=_add_generation_list_arguments,
            build_arguments=_build_generation_list_arguments,
        ),
    ]


# ---- executors ----

EXECUTORS = {
    "generation.create": adapter_executor(),
    "generation.get": adapter_executor(),
    "generation.list": adapter_executor(),
}
