"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

from museoncli.domains._shared import dekebab, kebab_choices

from museoncli.execution import CommandContext, agent_domain_result, direct_enveloped

import argparse
from collections.abc import Callable
from pathlib import Path
from typing import Any
from uuid import uuid4
from museoncli.domains._model import CommandSpec, Domain
from museoncli.domains._shared import (
    _add_common_adapter_arguments,
    _async_output_schema,
    _direct_output_schema,
    _json_list,
    _load_structured_args,
    _reject_server_controlled_fields,
    _uuid_id_schema,
)


SEARCH_SORT_CHOICES = ["relevance", "latest", "popular", "hot", "rising", "comments", "collects"]


SEARCH_TIME_WINDOW_CHOICES = [
    "any",
    "day",
    "week",
    "month",
    "three_months",
    "six_months",
    "year",
]


SEARCH_CONTENT_TYPE_CHOICES = ["any", "video", "image", "live"]


WEB_RESEARCH_INCLUDE_CHOICES = ["search_results", "page_text", "site_visual_assets"]


SOCIAL_MEDIA_PLATFORM_CHOICES = ["tiktok", "instagram", "youtube", "xhs", "xiaohongshu"]


SOCIAL_MEDIA_SEARCH_CONTENT_CHARS_MIN = 0


SOCIAL_MEDIA_SEARCH_CONTENT_CHARS_MAX = 4000


SOCIAL_MEDIA_SEARCH_TIMEOUT_MIN = 5


SOCIAL_MEDIA_SEARCH_TIMEOUT_MAX = 60


SOCIAL_MEDIA_INTENT_CHOICES = [
    "creator_search",
    "profile",
    "creator_posts",
    "keyword_search",
    "keyword_videos",
    "keyword_photos",
    "hashtag_search",
    "hashtag_videos",
    "post",
    "comments",
    "reels",
    "keyword_reels",
    "hashtag_reels",
    "music_search",
    "music_posts",
    "channel",
    "channel_videos",
    "channel_shorts",
    "video",
]


COMMUNITY_PLATFORM_CHOICES = ["x", "reddit", "linkedin"]


COMMUNITY_INTENT_CHOICES = [
    "keyword_search",
    "profile",
    "creator_posts",
    "post",
    "comments",
    "trending",
    "community_profile",
    "community_posts",
    "company_profile",
    "company_posts",
    "people_search",
    "posts",
]


CREATIVE_SEARCH_ADS_PLATFORM_CHOICES = ["meta_ads", "tiktok_ads"]


CREATIVE_SEARCH_ADS_MEDIA_TYPE_CHOICES = ["video", "photo"]


CREATIVE_SEARCH_ADS_TIME_RANGE_CHOICES = ["all", "7d", "30d", "90d"]


CREATIVE_SEARCH_ADS_RELEVANCE_CHOICES = ["matched", "all"]


CREATIVE_SEARCH_ADS_SORT_CHOICES = [
    "published_at",
    "first_seen_at",
    "last_seen_at",
    "created_at",
]


def _int_range_arg(*, flag: str, minimum: int, maximum: int) -> Callable[[str], int]:
    def parse(value: str) -> int:
        try:
            parsed = int(value)
        except ValueError as exc:
            raise argparse.ArgumentTypeError(f"{flag} must be an integer.") from exc
        if parsed < minimum:
            raise argparse.ArgumentTypeError(f"{flag} must be >= {minimum}.")
        if parsed > maximum:
            raise argparse.ArgumentTypeError(f"{flag} must be <= {maximum}.")
        return parsed

    return parse


def _validate_int_range(
    payload: dict[str, Any],
    *,
    key: str,
    flag: str,
    minimum: int,
    maximum: int,
) -> None:
    raw = payload.get(key)
    if isinstance(raw, bool):
        raise ValueError(f"{flag} must be an integer.")
    try:
        value = int(raw)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{flag} must be an integer.") from exc
    if value < minimum:
        raise ValueError(f"{flag} must be >= {minimum} (got {value}). Retry with {flag} {minimum}.")
    if value > maximum:
        raise ValueError(f"{flag} must be <= {maximum} (got {value}). Retry with {flag} {maximum}.")
    payload[key] = value


def _add_web_research_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--query")
    parser.add_argument("--url")
    parser.add_argument(
        "--include", action="append", choices=kebab_choices(WEB_RESEARCH_INCLUDE_CHOICES)
    )
    parser.add_argument("--limit", type=int, default=5)
    parser.add_argument("--content-chars", type=int, default=800)
    parser.add_argument("--region", default="US")
    parser.add_argument("--timeout", type=int, default=45)
    parser.add_argument("--max-retries", type=int, default=3)


def _build_web_research_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    if args.query is not None:
        payload["query"] = args.query
    if args.url is not None:
        payload["url"] = args.url
    if args.include:
        payload["include"] = [dekebab(v) for v in args.include]
    payload.update(
        {
            "limit": args.limit,
            "content_chars": args.content_chars,
            "region": args.region,
            "timeout": args.timeout,
            "max_retries": args.max_retries,
        }
    )
    if not str(payload.get("query") or "").strip() and not str(payload.get("url") or "").strip():
        raise ValueError("research +web-research requires --query or --url.")
    return payload


def _add_social_media_search_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--platform", choices=SOCIAL_MEDIA_PLATFORM_CHOICES)
    parser.add_argument("--intent", choices=kebab_choices(SOCIAL_MEDIA_INTENT_CHOICES))
    parser.add_argument("--query")
    parser.add_argument("--limit", type=int, default=5)
    parser.add_argument(
        "--content-chars",
        type=_int_range_arg(
            flag="--content-chars",
            minimum=SOCIAL_MEDIA_SEARCH_CONTENT_CHARS_MIN,
            maximum=SOCIAL_MEDIA_SEARCH_CONTENT_CHARS_MAX,
        ),
        default=800,
        metavar=f"{SOCIAL_MEDIA_SEARCH_CONTENT_CHARS_MIN}-{SOCIAL_MEDIA_SEARCH_CONTENT_CHARS_MAX}",
        help=(
            "Maximum returned content characters "
            f"({SOCIAL_MEDIA_SEARCH_CONTENT_CHARS_MIN}-"
            f"{SOCIAL_MEDIA_SEARCH_CONTENT_CHARS_MAX}; default: 800)."
        ),
    )
    parser.add_argument("--region", default="US")
    parser.add_argument(
        "--timeout",
        type=_int_range_arg(
            flag="--timeout",
            minimum=SOCIAL_MEDIA_SEARCH_TIMEOUT_MIN,
            maximum=SOCIAL_MEDIA_SEARCH_TIMEOUT_MAX,
        ),
        default=10,
        metavar=f"{SOCIAL_MEDIA_SEARCH_TIMEOUT_MIN}-{SOCIAL_MEDIA_SEARCH_TIMEOUT_MAX}",
        help=(
            "Per-attempt timeout seconds "
            f"({SOCIAL_MEDIA_SEARCH_TIMEOUT_MIN}-{SOCIAL_MEDIA_SEARCH_TIMEOUT_MAX}; default: 10)."
        ),
    )
    parser.add_argument("--max-retries", type=int, default=3)
    parser.add_argument("--sort", choices=SEARCH_SORT_CHOICES, default="relevance")
    parser.add_argument(
        "--time-window", choices=kebab_choices(SEARCH_TIME_WINDOW_CHOICES), default="any"
    )
    parser.add_argument("--content-type", choices=SEARCH_CONTENT_TYPE_CHOICES, default="any")
    parser.add_argument("--cursor")


def _build_social_media_search_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    if args.platform is not None:
        payload["platform"] = args.platform
    if args.intent is not None:
        payload["intent"] = dekebab(args.intent)
    if args.query is not None:
        payload["query"] = args.query
    payload.update(
        {
            "limit": args.limit,
            "content_chars": args.content_chars,
            "region": args.region,
            "timeout": args.timeout,
            "max_retries": args.max_retries,
            "sort": args.sort,
            "time_window": dekebab(args.time_window),
            "content_type": args.content_type,
        }
    )
    if args.cursor is not None:
        payload["cursor"] = args.cursor
    _validate_int_range(
        payload,
        key="content_chars",
        flag="--content-chars",
        minimum=SOCIAL_MEDIA_SEARCH_CONTENT_CHARS_MIN,
        maximum=SOCIAL_MEDIA_SEARCH_CONTENT_CHARS_MAX,
    )
    _validate_int_range(
        payload,
        key="timeout",
        flag="--timeout",
        minimum=SOCIAL_MEDIA_SEARCH_TIMEOUT_MIN,
        maximum=SOCIAL_MEDIA_SEARCH_TIMEOUT_MAX,
    )
    for key in ("platform", "intent", "query"):
        if not str(payload.get(key) or "").strip():
            raise ValueError(f"research +social-media-search requires --{key.replace('_', '-')}.")
    return payload


def _add_social_hook_analyze_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--url", dest="post_urls", action="append")
    parser.add_argument("--profile-url", dest="profile_urls", action="append")
    parser.add_argument("--limit-per-profile", type=int, default=12)
    parser.add_argument("--max-items", type=int, default=20)
    parser.add_argument("--idempotency-key", required=True)
    parser.add_argument("--dry-run", action="store_true")


def _build_social_hook_analyze_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    if args.post_urls:
        payload["post_urls"] = list(args.post_urls)
    if args.profile_urls:
        payload["profile_urls"] = list(args.profile_urls)
    payload.update(
        {
            "limit_per_profile": args.limit_per_profile,
            "max_items": args.max_items,
            "idempotency_key": args.idempotency_key.strip(),
        }
    )
    post_urls = _optional_url_list(payload.get("post_urls"), field="post_urls")
    profile_urls = _optional_url_list(payload.get("profile_urls"), field="profile_urls")
    if not post_urls and not profile_urls:
        raise ValueError("research +social-media-hook-analyze requires --url or --profile-url.")
    if len(post_urls) + len(profile_urls) > 40:
        raise ValueError("At most 40 --url/--profile-url values are allowed.")
    payload["post_urls"] = post_urls
    payload["profile_urls"] = profile_urls
    if len(payload["idempotency_key"]) < 8 or len(payload["idempotency_key"]) > 240:
        raise ValueError("--idempotency-key must contain 8 to 240 characters.")
    _validate_int_range(
        payload, key="limit_per_profile", flag="--limit-per-profile", minimum=1, maximum=20
    )
    _validate_int_range(payload, key="max_items", flag="--max-items", minimum=1, maximum=30)
    return payload


def _add_social_hook_source_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--url", dest="candidate_urls", action="append")
    parser.add_argument("--max-items", type=int, default=20)
    parser.add_argument("--idempotency-key", required=True)
    parser.add_argument("--dry-run", action="store_true")


def _build_social_hook_source_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    if args.candidate_urls:
        payload["candidate_urls"] = list(args.candidate_urls)
    candidate_urls = _optional_url_list(
        payload.get("candidate_urls"), field="candidate_urls"
    )
    if not 1 <= len(candidate_urls) <= 40:
        raise ValueError(
            "research +social-media-hook-source requires 1 to 40 --url values."
        )
    if len(candidate_urls) != len(set(candidate_urls)):
        raise ValueError("--url values must be unique.")
    payload["candidate_urls"] = candidate_urls
    payload["max_items"] = args.max_items
    payload["idempotency_key"] = args.idempotency_key.strip()
    if not 8 <= len(payload["idempotency_key"]) <= 240:
        raise ValueError("--idempotency-key must contain 8 to 240 characters.")
    _validate_int_range(
        payload, key="max_items", flag="--max-items", minimum=1, maximum=30
    )
    return payload


def _add_social_hook_analyze_seen_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--url", dest="urls", action="append")


def _build_social_hook_analyze_seen_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    if args.urls:
        payload["urls"] = list(args.urls)
    raw_urls = payload.get("urls", [])
    if not isinstance(raw_urls, list) or any(not isinstance(url, str) for url in raw_urls):
        raise ValueError("urls must be an array of URLs.")
    urls = [url.strip() for url in raw_urls]
    if not 1 <= len(urls) <= 40:
        raise ValueError("research +social-media-hook-analyze-seen requires 1 to 40 --url values.")
    if any(not url for url in urls):
        raise ValueError("--url must not be blank.")
    if any(len(url) > 2048 for url in urls):
        raise ValueError("--url values must be at most 2048 characters.")
    return {"urls": urls}


def _add_social_hook_get_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", dest="analysis_id", required=True)


def _build_social_hook_get_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {**_load_structured_args(args), "analysis_id": args.analysis_id}


def _add_social_hook_poll_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", dest="analysis_ids", action="append", required=True)


def _build_social_hook_poll_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload["analysis_ids"] = list(dict.fromkeys(args.analysis_ids))
    if len(payload["analysis_ids"]) > 20:
        raise ValueError("--id accepts at most 20 analysis IDs per poll.")
    return payload


def _add_social_hook_results_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", dest="analysis_id", required=True)
    parser.add_argument("--page", type=int, default=1)
    parser.add_argument("--page-size", type=int, default=20)


def _add_social_hook_media_get_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", dest="analysis_id", required=True)
    parser.add_argument("--item-id", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--force", action="store_true")


def _build_social_hook_media_get_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update(
        {
            "analysis_id": args.analysis_id,
            "item_id": args.item_id,
            "output": args.output,
            "force": bool(args.force),
        }
    )
    if not str(payload["output"]).strip():
        raise ValueError("--output must not be empty.")
    return payload


def _build_social_hook_results_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update(
        {
            "analysis_id": args.analysis_id,
            "page": args.page,
            "page_size": args.page_size,
        }
    )
    if payload["page"] < 1:
        raise ValueError("--page must be at least 1.")
    _validate_int_range(payload, key="page_size", flag="--page-size", minimum=1, maximum=100)
    return {key: value for key, value in payload.items() if value is not None}


def _optional_url_list(value: Any, *, field: str) -> list[str]:
    if value is None:
        return []
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise ValueError(f"{field} must be an array of URLs.")
    normalized = [item.strip() for item in value if item.strip()]
    if any(len(item) > 2048 for item in normalized):
        raise ValueError(f"{field} values must be at most 2048 characters.")
    return list(dict.fromkeys(normalized))


def _add_community_search_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--platform", choices=COMMUNITY_PLATFORM_CHOICES)
    parser.add_argument("--intent", choices=kebab_choices(COMMUNITY_INTENT_CHOICES))
    parser.add_argument("--query")
    parser.add_argument("--limit", type=int, default=5)
    parser.add_argument("--content-chars", type=int, default=800)
    parser.add_argument("--region", default="US")
    parser.add_argument("--timeout", type=int, default=10)
    parser.add_argument("--max-retries", type=int, default=3)
    parser.add_argument("--sort", choices=SEARCH_SORT_CHOICES, default="relevance")
    parser.add_argument(
        "--time-window", choices=kebab_choices(SEARCH_TIME_WINDOW_CHOICES), default="any"
    )
    parser.add_argument("--cursor")
    parser.add_argument(
        "--search-type",
        help="Reddit keyword search category: post, community, comment, media, or people.",
    )
    parser.add_argument(
        "--allow-slow",
        action="store_true",
        help="Backward-compatible no-op retained for older invocations.",
    )


def _build_community_search_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    if args.platform is not None:
        payload["platform"] = args.platform
    if args.intent is not None:
        payload["intent"] = dekebab(args.intent)
    if args.query is not None:
        payload["query"] = args.query
    payload.update(
        {
            "limit": args.limit,
            "content_chars": args.content_chars,
            "region": args.region,
            "timeout": args.timeout,
            "max_retries": args.max_retries,
            "sort": args.sort,
            "time_window": dekebab(args.time_window),
            "allow_slow": args.allow_slow,
        }
    )
    if args.cursor is not None:
        payload["cursor"] = args.cursor
    if args.search_type is not None:
        payload["search_type"] = args.search_type
    for key in ("platform", "intent", "query"):
        if not str(payload.get(key) or "").strip():
            raise ValueError(f"research +community-search requires --{key.replace('_', '-')}.")
    return payload


def _add_creative_search_ads_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument(
        "--idempotency-key",
        help="Stable key for safe retries; use a new key only for an intentional new search.",
    )
    parser.add_argument("--keyword", dest="keywords", action="append")
    parser.add_argument(
        "--ad-platform",
        dest="ad_platforms",
        action="append",
        choices=kebab_choices(CREATIVE_SEARCH_ADS_PLATFORM_CHOICES),
    )
    parser.add_argument(
        "--media-type",
        dest="media_types",
        action="append",
        choices=CREATIVE_SEARCH_ADS_MEDIA_TYPE_CHOICES,
    )
    parser.add_argument(
        "--limit",
        type=_int_range_arg(flag="--limit", minimum=1, maximum=100),
    )
    parser.add_argument("--dry-run", action="store_true")


def _build_creative_search_ads_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    _reject_server_controlled_fields(
        payload,
        fields={"provider", "provider_name", "source_type"},
        context="research +creative-search-ads",
    )
    raw_idempotency_key = (
        args.idempotency_key if args.idempotency_key is not None else payload.get("idempotency_key")
    )
    if not isinstance(raw_idempotency_key, str):
        raise ValueError("--idempotency-key must be a string.")
    idempotency_key = raw_idempotency_key.strip()
    if not idempotency_key:
        raise ValueError("--idempotency-key must not be blank.")
    if len(idempotency_key) > 240:
        raise ValueError("--idempotency-key must be at most 240 characters.")
    payload["idempotency_key"] = idempotency_key
    if args.keywords:
        payload["keywords"] = list(args.keywords)
    if args.ad_platforms:
        payload["ad_platforms"] = list(args.ad_platforms)
    if args.media_types:
        payload["media_types"] = list(args.media_types)
    if args.limit is not None:
        payload["limit_per_platform"] = args.limit

    payload["keywords"] = _normalized_string_list(
        payload.get("keywords"),
        field="keywords",
        minimum=1,
        maximum=10,
    )
    payload["ad_platforms"] = _normalized_choice_list(
        payload.get("ad_platforms"),
        field="ad_platforms",
        choices=CREATIVE_SEARCH_ADS_PLATFORM_CHOICES,
        default=CREATIVE_SEARCH_ADS_PLATFORM_CHOICES,
    )
    payload["media_types"] = _normalized_choice_list(
        payload.get("media_types"),
        field="media_types",
        choices=CREATIVE_SEARCH_ADS_MEDIA_TYPE_CHOICES,
        default=["video"],
    )
    if "limit_per_platform" not in payload:
        payload["limit_per_platform"] = 20
    _validate_int_range(
        payload,
        key="limit_per_platform",
        flag="--limit",
        minimum=1,
        maximum=100,
    )
    return payload


def _add_creative_search_ads_get_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", dest="task_id", required=True)


def _build_creative_search_ads_get_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload["task_id"] = args.task_id
    return payload


def _add_creative_search_ads_results_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", dest="task_id", required=True)
    parser.add_argument(
        "--ad-platform",
        choices=kebab_choices(CREATIVE_SEARCH_ADS_PLATFORM_CHOICES),
    )
    parser.add_argument(
        "--time-range",
        choices=CREATIVE_SEARCH_ADS_TIME_RANGE_CHOICES,
        default="all",
    )
    parser.add_argument("--page", type=int, default=1)
    parser.add_argument("--page-size", type=int, default=20)
    parser.add_argument(
        "--sort-by",
        choices=kebab_choices(CREATIVE_SEARCH_ADS_SORT_CHOICES),
        default="published-at",
    )
    parser.add_argument(
        "--relevance",
        choices=CREATIVE_SEARCH_ADS_RELEVANCE_CHOICES,
        default="matched",
        help=(
            "matched excludes fallback search candidates from analysis; "
            "all returns every candidate with relevance metadata"
        ),
    )


def _build_creative_search_ads_results_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update(
        {
            "task_id": args.task_id,
            "platform": dekebab(args.ad_platform),
            "time_range": args.time_range,
            "page": args.page,
            "page_size": args.page_size,
            "sort_by": dekebab(args.sort_by),
            "relevance": args.relevance,
        }
    )
    if payload["page"] < 1:
        raise ValueError("--page must be at least 1.")
    _validate_int_range(
        payload,
        key="page_size",
        flag="--page-size",
        minimum=1,
        maximum=100,
    )
    return {key: value for key, value in payload.items() if value is not None}


def _normalized_string_list(
    value: Any,
    *,
    field: str,
    minimum: int,
    maximum: int,
) -> list[str]:
    if not isinstance(value, list):
        raise ValueError(f"research +creative-search-ads requires --keyword ({field}).")
    if any(not isinstance(item, str) for item in value):
        raise ValueError(f"{field} values must be strings.")
    normalized = [item.strip() for item in value if item.strip()]
    if len(normalized) < minimum:
        raise ValueError(f"{field} requires at least {minimum} value.")
    if len(normalized) > maximum:
        raise ValueError(f"{field} accepts at most {maximum} values.")
    if any(len(item) > 200 for item in normalized):
        raise ValueError(f"{field} values must be at most 200 characters.")
    if len(normalized) != len(set(normalized)):
        raise ValueError(f"{field} values must be unique.")
    return normalized


def _normalized_choice_list(
    value: Any,
    *,
    field: str,
    choices: list[str],
    default: list[str],
) -> list[str]:
    raw = default if value is None else value
    if not isinstance(raw, list):
        raise ValueError(f"{field} must be an array.")
    normalized = [dekebab(str(item)) for item in raw]
    invalid = [item for item in normalized if item not in choices]
    if invalid:
        raise ValueError(f"{field} contains unsupported values: {', '.join(invalid)}.")
    if not normalized:
        raise ValueError(f"{field} requires at least one value.")
    if len(normalized) != len(set(normalized)):
        raise ValueError(f"{field} values must be unique.")
    return normalized


def _add_visual_analyze_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument(
        "--media",
        action="append",
        dest="media_urls",
        help=(
            "Image/video URL to analyze. For TikTok or signed CDN URLs that fail "
            "direct preparation, first run `asset +create --type media --url ...` "
            "and retry with the returned media_url or permanent_media_url."
        ),
    )
    parser.add_argument("--media-json")
    parser.add_argument("--media-file")
    parser.add_argument("--prompt", required=True)
    parser.add_argument("--context")


def _build_visual_analyze_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    _reject_server_controlled_fields(
        payload,
        fields={"model", "temperature", "max_output_tokens"},
        context="research +visual-analyze",
    )
    if args.media_json:
        payload["media"] = _json_list(args.media_json, flag="--media-json")
    if args.media_file:
        media_payload = Path(args.media_file).read_text(encoding="utf-8")
        payload["media"] = _json_list(media_payload, flag="--media-file")
    if args.media_urls:
        payload["media"] = list(args.media_urls)
    if not payload.get("media"):
        raise ValueError(
            "research +visual-analyze requires --media, --media-json, or --media-file."
        )
    payload["prompt"] = args.prompt
    if args.context is not None:
        payload["context"] = args.context
    return payload


def _web_research_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "query": {
                "type": ["string", "null"],
                "minLength": 1,
                "maxLength": 1000,
                "description": "Public web search query.",
            },
            "url": {
                "type": ["string", "null"],
                "minLength": 1,
                "maxLength": 4096,
                "description": "URL to read or inspect.",
            },
            "include": {
                "type": "array",
                "items": {"type": "string", "enum": kebab_choices(WEB_RESEARCH_INCLUDE_CHOICES)},
                "maxItems": 3,
                "description": (
                    "Evidence blocks to collect. Empty defaults from provided query/url."
                ),
            },
            "limit": {"type": "integer", "minimum": 1, "maximum": 30, "default": 5},
            "content_chars": {
                "type": "integer",
                "minimum": 0,
                "maximum": 4000,
                "default": 800,
            },
            "region": {"type": "string", "minLength": 2, "maxLength": 2, "default": "US"},
            "timeout": {"type": "integer", "minimum": 5, "maximum": 300, "default": 45},
            "max_retries": {"type": "integer", "minimum": 0, "maximum": 3, "default": 3},
        },
        "anyOf": [{"required": ["query"]}, {"required": ["url"]}],
    }


def _social_media_search_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "platform": {
                "type": "string",
                "enum": SOCIAL_MEDIA_PLATFORM_CHOICES,
                "description": "Social media platform to search.",
            },
            "intent": {
                "type": "string",
                "enum": kebab_choices(SOCIAL_MEDIA_INTENT_CHOICES),
                "description": (
                    "Domain search intent. TikTok supports creator-search, profile, "
                    "creator-posts, keyword-search, keyword-videos, keyword-photos, "
                    "hashtag-search, hashtag-videos, post, comments, music-search, "
                    "and music-posts. Instagram supports profile, creator-posts, reels, "
                    "keyword-search, keyword-reels, hashtag-search, hashtag-reels, post, "
                    "comments, music-search, and music-posts. "
                    "YouTube supports channel, channel-videos, channel-shorts, video, "
                    "and keyword-search. XHS/RedNote supports keyword-search, post, "
                    "profile, and creator-posts. Comments is also supported."
                ),
            },
            "query": {
                "type": "string",
                "minLength": 1,
                "maxLength": 4096,
                "description": (
                    "Search query, creator handle, profile/channel URL, hashtag/ch_id, "
                    "post URL/id, or aweme_id depending on platform and intent. For "
                    "TikTok comments, pass the numeric video aweme_id, not a share URL. "
                    "For Instagram comments, pass a post shortcode or full post/Reel URL. "
                    "Instagram creator-posts, handles/profile URLs read an account "
                    "timeline; multi-word plain text runs keyword posts search. "
                    "For XHS keyword-search, pass a note search keyword; for XHS post, "
                    "pass a note id or share URL; for XHS comments, pass a note id, note "
                    "URL, or xhslink share link; for XHS profile/creator-posts, pass a user "
                    "id, profile URL/share link, or Xiaohongshu ID."
                ),
            },
            "limit": {"type": "integer", "minimum": 1, "maximum": 30, "default": 5},
            "content_chars": {
                "type": "integer",
                "minimum": SOCIAL_MEDIA_SEARCH_CONTENT_CHARS_MIN,
                "maximum": SOCIAL_MEDIA_SEARCH_CONTENT_CHARS_MAX,
                "default": 800,
            },
            "region": {"type": "string", "minLength": 2, "maxLength": 2, "default": "US"},
            "timeout": {
                "type": "integer",
                "minimum": SOCIAL_MEDIA_SEARCH_TIMEOUT_MIN,
                "maximum": SOCIAL_MEDIA_SEARCH_TIMEOUT_MAX,
                "default": 10,
            },
            "max_retries": {"type": "integer", "minimum": 0, "maximum": 3, "default": 3},
            "sort": {"type": "string", "enum": SEARCH_SORT_CHOICES, "default": "relevance"},
            "time_window": {
                "type": "string",
                "enum": kebab_choices(SEARCH_TIME_WINDOW_CHOICES),
                "default": "any",
            },
            "content_type": {
                "type": "string",
                "enum": SEARCH_CONTENT_TYPE_CHOICES,
                "default": "any",
                "description": (
                    "Content hint. For TikTok keyword-search, image routes to "
                    "keyword-photos; any/video routes to keyword-videos. For Instagram "
                    "creator-posts/reels, image filters to all-static carousel image "
                    "posts and video filters to posts with video media."
                    " For XHS keyword-search, image routes to normal notes, video routes to "
                    "video notes, and live routes to live notes."
                ),
            },
            "cursor": {
                "type": ["string", "null"],
                "description": (
                    "Optional pagination cursor from evidence.pagination. For TikTok comments, "
                    "pass the numeric cursor (0 for the first page). For Instagram comments, "
                    "pass pagination_token unchanged. For XHS comments, pass the opaque cursor "
                    "string unchanged. Otherwise pass a simple token directly, or the whole "
                    "pagination object as JSON when it contains multiple fields. "
                    "Supported for TikTok "
                    "creator-search/creator-posts/keyword-search/keyword-videos/keyword-photos/"
                    "hashtag-search/hashtag-videos/comments/music-posts, Instagram creator-posts/"
                    "reels/keyword-search/keyword-reels/hashtag-search/hashtag-reels/comments/"
                    "music-search/music-posts, YouTube keyword-search, XHS keyword-search/"
                    "comments, and XHS creator-posts."
                ),
            },
        },
        "required": ["platform", "intent", "query"],
    }


def _social_hook_analyze_input_schema() -> dict[str, Any]:
    url_array = {
        "type": "array",
        "items": {"type": "string", "format": "uri", "maxLength": 2048},
        "maxItems": 40,
        "uniqueItems": True,
    }
    return {
        "type": "object",
        "properties": {
            "post_urls": url_array,
            "profile_urls": url_array,
            "limit_per_profile": {"type": "integer", "minimum": 1, "maximum": 20, "default": 12},
            "max_items": {"type": "integer", "minimum": 1, "maximum": 30, "default": 20},
            "idempotency_key": {"type": "string", "minLength": 8, "maxLength": 240},
        },
        "required": ["idempotency_key"],
        "anyOf": [
            {"required": ["post_urls"], "properties": {"post_urls": {"minItems": 1}}},
            {"required": ["profile_urls"], "properties": {"profile_urls": {"minItems": 1}}},
        ],
    }


def _social_hook_source_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "candidate_urls": {
                "type": "array",
                "items": {"type": "string", "format": "uri", "maxLength": 2048},
                "minItems": 1,
                "maxItems": 40,
                "uniqueItems": True,
                "description": (
                    "Instagram post URLs retained by an Agent after opening-frame "
                    "visual prefiltering."
                ),
            },
            "max_items": {"type": "integer", "minimum": 1, "maximum": 30, "default": 20},
            "idempotency_key": {"type": "string", "minLength": 8, "maxLength": 240},
        },
        "required": ["candidate_urls", "idempotency_key"],
    }


def _social_hook_analyze_seen_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "urls": {
                "type": "array",
                "items": {"type": "string", "format": "uri", "maxLength": 2048},
                "minItems": 1,
                "maxItems": 40,
                "description": "Instagram post URLs to check against prior Hook analyses.",
            }
        },
        "required": ["urls"],
    }


def _social_hook_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {"analysis_id": _uuid_id_schema("Social Hook analysis batch ID.")},
        "required": ["analysis_id"],
    }


def _social_hook_poll_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "analysis_ids": {
                "type": "array",
                "items": _uuid_id_schema("Social Hook analysis batch ID."),
                "minItems": 1,
                "maxItems": 20,
                "uniqueItems": True,
            }
        },
        "required": ["analysis_ids"],
    }


def _social_hook_results_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "analysis_id": _uuid_id_schema("Social Hook analysis batch ID."),
            "page": {"type": "integer", "minimum": 1, "default": 1},
            "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 20},
        },
        "required": ["analysis_id"],
    }


def _social_hook_media_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "analysis_id": _uuid_id_schema("Social Hook analysis batch ID."),
            "item_id": _uuid_id_schema("Social Hook analysis item ID."),
            "output": {
                "type": "string",
                "minLength": 1,
                "description": "Local destination path for the downloaded video.",
            },
            "force": {"type": "boolean", "default": False},
        },
        "required": ["analysis_id", "item_id", "output"],
    }


def _community_search_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "platform": {
                "type": "string",
                "enum": COMMUNITY_PLATFORM_CHOICES,
                "description": "Community platform to search: x, reddit, or linkedin.",
            },
            "intent": {
                "type": "string",
                "enum": kebab_choices(COMMUNITY_INTENT_CHOICES),
                "description": (
                    "Domain search intent. Use keyword-search for discovery, "
                    "profile/company-profile for entity hydration, "
                    "creator-posts/community-posts/company-posts for timelines, "
                    "post for one item, comments for discussion, and trending for topical discovery."
                ),
            },
            "query": {
                "type": "string",
                "minLength": 1,
                "maxLength": 4096,
                "description": (
                    "Search keyword, LinkedIn company slug, or LinkedIn company URL "
                    "depending on platform and intent. For post/comments, pass the "
                    "platform post URL or ID."
                ),
            },
            "limit": {"type": "integer", "minimum": 1, "maximum": 30, "default": 5},
            "content_chars": {
                "type": "integer",
                "minimum": 0,
                "maximum": 4000,
                "default": 800,
            },
            "region": {"type": "string", "minLength": 2, "maxLength": 2, "default": "US"},
            "timeout": {"type": "integer", "minimum": 5, "maximum": 120, "default": 10},
            "max_retries": {"type": "integer", "minimum": 0, "maximum": 3, "default": 3},
            "sort": {"type": "string", "enum": SEARCH_SORT_CHOICES, "default": "relevance"},
            "time_window": {
                "type": "string",
                "enum": kebab_choices(SEARCH_TIME_WINDOW_CHOICES),
                "default": "any",
            },
            "cursor": {
                "type": ["string", "null"],
                "description": (
                    "Optional pagination cursor from evidence.pagination. "
                    "For LinkedIn search this may be a page/start number; for X and Reddit "
                    "it is the cursor/after token."
                ),
            },
            "search_type": {
                "type": ["string", "null"],
                "description": (
                    "Optional Reddit keyword search category: post, community, comment, "
                    "media, or people. Ignored by X and LinkedIn."
                ),
            },
            "allow_slow": {
                "type": "boolean",
                "default": False,
                "description": (
                    "Backward-compatible no-op kept so older CLI invocations do not break."
                ),
            },
        },
        "required": ["platform", "intent", "query"],
    }


def _creative_search_ads_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "idempotency_key": {
                "type": "string",
                "minLength": 1,
                "maxLength": 240,
                "description": (
                    "Caller-stable key reused only when retrying the same Ads search intent."
                ),
            },
            "keywords": {
                "type": "array",
                "minItems": 1,
                "maxItems": 10,
                "uniqueItems": True,
                "items": {"type": "string", "minLength": 1, "maxLength": 200},
                "description": "One to ten Ads search keywords.",
            },
            "ad_platforms": {
                "type": "array",
                "minItems": 1,
                "maxItems": 2,
                "uniqueItems": True,
                "items": {
                    "type": "string",
                    "enum": kebab_choices(CREATIVE_SEARCH_ADS_PLATFORM_CHOICES),
                },
                "default": kebab_choices(CREATIVE_SEARCH_ADS_PLATFORM_CHOICES),
                "description": "Ad libraries to search.",
            },
            "media_types": {
                "type": "array",
                "minItems": 1,
                "maxItems": 2,
                "uniqueItems": True,
                "items": {
                    "type": "string",
                    "enum": CREATIVE_SEARCH_ADS_MEDIA_TYPE_CHOICES,
                },
                "default": ["video"],
            },
            "limit_per_platform": {
                "type": "integer",
                "minimum": 1,
                "maximum": 100,
                "default": 20,
                "description": "Maximum results per keyword and ad library.",
            },
        },
        "required": ["idempotency_key", "keywords"],
    }


def _creative_search_ads_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "task_id": _uuid_id_schema("Creative Search Ads task UUID."),
        },
        "required": ["task_id"],
    }


def _creative_search_ads_results_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "task_id": _uuid_id_schema("Creative Search Ads task UUID."),
            "platform": {
                "type": ["string", "null"],
                "enum": [*kebab_choices(CREATIVE_SEARCH_ADS_PLATFORM_CHOICES), None],
            },
            "time_range": {
                "type": "string",
                "enum": CREATIVE_SEARCH_ADS_TIME_RANGE_CHOICES,
                "default": "all",
            },
            "page": {"type": "integer", "minimum": 1, "default": 1},
            "page_size": {
                "type": "integer",
                "minimum": 1,
                "maximum": 100,
                "default": 20,
            },
            "sort_by": {
                "type": "string",
                "enum": kebab_choices(CREATIVE_SEARCH_ADS_SORT_CHOICES),
                "default": "published-at",
            },
            "relevance": {
                "type": "string",
                "enum": CREATIVE_SEARCH_ADS_RELEVANCE_CHOICES,
                "default": "matched",
                "description": (
                    "Use matched for analysis-eligible results. Use all only to inspect "
                    "fallback search candidates, which may be unrelated."
                ),
            },
        },
        "required": ["task_id"],
    }


def _visual_analyze_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "media": {
                "type": "array",
                "minItems": 1,
                "maxItems": 12,
                "items": {
                    "anyOf": [
                        {"type": "string"},
                        {
                            "type": "object",
                            "properties": {
                                "url": {"type": "string"},
                                "type": {
                                    "type": ["string", "null"],
                                    "enum": ["image", "video", None],
                                },
                                "mime_type": {"type": ["string", "null"]},
                                "label": {"type": ["string", "null"]},
                            },
                            "required": ["url"],
                        },
                    ]
                },
            },
            "prompt": {"type": "string", "minLength": 1, "maxLength": 12000},
            "context": {"type": ["string", "null"], "maxLength": 4000},
        },
        "required": ["media", "prompt"],
    }


def specs() -> list[CommandSpec]:
    return [
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+web-research",
            summary=(
                "Research public web evidence from a query or URL, including page text "
                "and official-site visual assets."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="web_research",
            input_schema=_web_research_input_schema(),
            output_schema=_direct_output_schema(
                "Web Research evidence payload returned by Museon API."
            ),
            examples=[
                (
                    "museoncli research +web-research --query 'Museon AI' "
                    "--include search-results --limit 5"
                ),
                (
                    "museoncli research +web-research --url https://example.com "
                    "--include page-text --include site-visual-assets"
                ),
            ],
            add_arguments=_add_web_research_arguments,
            build_arguments=_build_web_research_arguments,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+social-media-search",
            summary=(
                "Search social-native evidence across TikTok, Instagram, YouTube, and XHS "
                "using a stable platform and intent contract."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_media_search",
            input_schema=_social_media_search_input_schema(),
            output_schema=_direct_output_schema(
                "Social Media Search evidence payload returned by Museon API. For XHS post "
                "video notes, evidence includes video_url (a directly downloadable MP4 URL), "
                "video_duration_seconds, and video_size_bytes."
            ),
            examples=[
                (
                    "museoncli research +social-media-search --platform tiktok "
                    "--intent keyword-search --query 'skincare routine' --content-type video"
                ),
                (
                    "museoncli research +social-media-search --platform tiktok "
                    "--intent hashtag-videos --query '#skincare' --limit 10"
                ),
                (
                    "museoncli research +social-media-search --platform instagram "
                    "--intent reels --query '@creator' --limit 10"
                ),
                (
                    "museoncli research +social-media-search --platform tiktok "
                    "--intent comments --query '7551234567890123456' --limit 20"
                ),
                (
                    "museoncli research +social-media-search --platform instagram "
                    "--intent comments --query 'https://www.instagram.com/reel/<shortcode>/'"
                ),
                (
                    "museoncli research +social-media-search --platform youtube "
                    "--intent keyword-search --query 'AI video ads'"
                ),
                (
                    "museoncli research +social-media-search --platform xhs "
                    "--intent keyword-search --query 'coffee shop decor' --content-type image"
                ),
                (
                    "museoncli research +social-media-search --platform xhs "
                    "--intent post --query 'https://www.xiaohongshu.com/explore/<note_id>'"
                ),
                (
                    "museoncli research +social-media-search --platform xhs "
                    "--intent comments --query 'https://xhslink.cn/o/<share_id>'"
                ),
                (
                    "museoncli research +social-media-search --platform xhs "
                    "--intent creator-posts "
                    "--query 'https://www.xiaohongshu.com/user/profile/<user_id>' --limit 10"
                ),
            ],
            add_arguments=_add_social_media_search_arguments,
            build_arguments=_build_social_media_search_arguments,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+social-media-hook-analyze",
            summary=(
                "Start a durable Instagram Hook analysis batch from post and/or profile URLs. "
                "Returns immediately; poll batches together and read structured results by page."
            ),
            risk_level="write",
            execution="async_run",
            adapter_tool_name="social_media_hook_analyze",
            input_schema=_social_hook_analyze_input_schema(),
            output_schema=_async_output_schema(
                "Accepted Social Media Hook analysis batch with stable schema and strategy versions."
            ),
            examples=[
                (
                    "museoncli research +social-media-hook-analyze "
                    "--url https://www.instagram.com/reel/<id>/ "
                    "--profile-url https://www.instagram.com/<creator>/ "
                    "--idempotency-key <stable_key>"
                )
            ],
            add_arguments=_add_social_hook_analyze_arguments,
            build_arguments=_build_social_hook_analyze_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+social-media-hook-source",
            summary=(
                "Submit Agent-prefiltered Instagram Hook candidates, recheck "
                "workspace-scoped duplicates, and start the existing durable analysis batch."
            ),
            risk_level="write",
            execution="async_run",
            adapter_tool_name="social_media_hook_source",
            input_schema=_social_hook_source_input_schema(),
            output_schema=_async_output_schema(
                "Accepted Social Hook analysis batch plus the initial duplicate preview."
            ),
            examples=[
                (
                    "museoncli research +social-media-hook-source "
                    "--url https://www.instagram.com/reel/<id>/ "
                    "--idempotency-key <stable_key>"
                )
            ],
            add_arguments=_add_social_hook_source_arguments,
            build_arguments=_build_social_hook_source_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+social-media-hook-analyze-seen",
            summary=(
                "Check up to 40 Instagram post URLs against prior workspace-scoped "
                "Social Media Hook analyses."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_media_hook_analyze_seen",
            input_schema=_social_hook_analyze_seen_input_schema(),
            output_schema=_direct_output_schema(
                "Workspace-scoped seen status for each supplied Instagram post URL."
            ),
            examples=[
                (
                    "museoncli research +social-media-hook-analyze-seen "
                    "--url https://www.instagram.com/reel/<id_1>/ "
                    "--url https://www.instagram.com/reel/<id_2>/"
                )
            ],
            add_arguments=_add_social_hook_analyze_seen_arguments,
            build_arguments=_build_social_hook_analyze_seen_arguments,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+social-media-hook-analyze-get",
            summary="Read one Social Media Hook analysis batch and its aggregate progress.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_media_hook_analyze_get",
            input_schema=_social_hook_get_input_schema(),
            output_schema=_async_output_schema("Social Media Hook analysis batch status."),
            examples=["museoncli research +social-media-hook-analyze-get --id <analysis_id>"],
            add_arguments=_add_social_hook_get_arguments,
            build_arguments=_build_social_hook_get_arguments,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+social-media-hook-analyze-poll",
            summary="Poll up to 20 Social Media Hook analysis batches in one request.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_media_hook_analyze_poll",
            input_schema=_social_hook_poll_input_schema(),
            output_schema=_async_output_schema("Grouped Social Media Hook analysis progress."),
            examples=["museoncli research +social-media-hook-analyze-poll --id <id_1> --id <id_2>"],
            add_arguments=_add_social_hook_poll_arguments,
            build_arguments=_build_social_hook_poll_arguments,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+social-media-hook-analyze-results",
            summary=(
                "List versioned, structured Hook evidence for one analysis batch. "
                "Apply scoring and recommendation policy in the consuming Skill."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_media_hook_analyze_results",
            input_schema=_social_hook_results_input_schema(),
            output_schema=_direct_output_schema(
                "Paginated Social Media Hook analysis items with policy-free structured evidence."
            ),
            examples=[
                (
                    "museoncli research +social-media-hook-analyze-results --id <analysis_id> "
                    "--page 1 --page-size 20"
                )
            ],
            add_arguments=_add_social_hook_results_arguments,
            build_arguments=_build_social_hook_results_arguments,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+social-media-hook-analyze-media-get",
            summary=(
                "Download one workspace-scoped temporary source video from a Social Media "
                "Hook analysis item without exposing a signed URL."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_media_hook_analyze_media_get",
            input_schema=_social_hook_media_get_input_schema(),
            output_schema=_direct_output_schema(
                "Local path, content type, and byte length of the downloaded Hook video."
            ),
            examples=[
                (
                    "museoncli research +social-media-hook-analyze-media-get "
                    "--id <analysis_id> --item-id <item_id> --output ./hook.mp4"
                )
            ],
            add_arguments=_add_social_hook_media_get_arguments,
            build_arguments=_build_social_hook_media_get_arguments,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+community-search",
            summary=(
                "Search community evidence across X, Reddit, and LinkedIn using "
                "a stable platform and intent contract."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="community_search",
            input_schema=_community_search_input_schema(),
            output_schema=_direct_output_schema(
                "Community Search evidence payload returned by Museon API."
            ),
            examples=[
                (
                    "museoncli research +community-search --platform reddit "
                    "--intent keyword-search --query 'AI video agent' --search-type post --limit 5"
                ),
                (
                    "museoncli research +community-search --platform x "
                    "--intent keyword-search --query 'AI video agent'"
                ),
                (
                    "museoncli research +community-search --platform linkedin "
                    "--intent company-profile --query openai"
                ),
                (
                    "museoncli research +community-search --platform linkedin "
                    "--intent keyword-search --query 'AI automation' --limit 5"
                ),
            ],
            add_arguments=_add_community_search_arguments,
            build_arguments=_build_community_search_arguments,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+creative-search-ads",
            summary=(
                "Start a durable Creative Search Ads task across Meta and TikTok ad "
                "libraries. Requires a stable idempotency key for safe retries. "
                "This is Ads-only and never falls back to organic social search."
            ),
            risk_level="write",
            execution="async_run",
            adapter_tool_name="creative_search_ads",
            input_schema=_creative_search_ads_input_schema(),
            output_schema=_async_output_schema(
                "Accepted Creative Search Ads task with a run ID, status command, "
                "and recommended wakeup delay."
            ),
            examples=[
                (
                    "museoncli research +creative-search-ads --keyword 'eco soap' "
                    "--ad-platform meta-ads --ad-platform tiktok-ads --media-type video "
                    "--idempotency-key <stable_key>"
                ),
                (
                    "museoncli research +creative-search-ads --keyword 'summer dress' "
                    "--media-type photo --limit 20 --idempotency-key <stable_key> --dry-run"
                ),
            ],
            add_arguments=_add_creative_search_ads_arguments,
            build_arguments=_build_creative_search_ads_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+creative-search-ads-get",
            summary=(
                "Read one Creative Search Ads task, including terminal aggregate "
                "statistics and sanitized partial-failure details."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="creative_search_ads_get",
            input_schema=_creative_search_ads_get_input_schema(),
            output_schema=_async_output_schema(
                "Creative Search Ads task status and terminal aggregate result."
            ),
            examples=[
                "museoncli research +creative-search-ads-get --id <task_id>",
            ],
            add_arguments=_add_creative_search_ads_get_arguments,
            build_arguments=_build_creative_search_ads_get_arguments,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+creative-search-ads-results",
            summary=(
                "List deduplicated Creative Search Ads evidence for one task. Defaults "
                "to analysis-eligible matches and returns relevance, evidence quality, "
                "metric extrema, and limitations. Treat results as one snapshot: cite "
                "item IDs for numeric claims and do not infer causality, conversion "
                "effectiveness, market growth, competition intensity, or geographic "
                "activity without additional evidence."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="creative_search_ads_results",
            input_schema=_creative_search_ads_results_input_schema(),
            output_schema=_direct_output_schema(
                "Paginated Creative Search Ads evidence with relevance metadata, "
                "deterministic aggregates, claim limitations, and source item IDs."
            ),
            examples=[
                (
                    "museoncli research +creative-search-ads-results --id <task_id> "
                    "--ad-platform meta-ads --page 1 --page-size 20"
                ),
            ],
            add_arguments=_add_creative_search_ads_results_arguments,
            build_arguments=_build_creative_search_ads_results_arguments,
        ),
        CommandSpec(
            domain=Domain.RESEARCH,
            shortcut="+visual-analyze",
            summary=(
                "Analyze one or more image/video URLs with a business prompt. "
                "If a TikTok or signed CDN URL cannot be prepared, import it as "
                "Museon media first and retry with the returned stable media URL."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="visual_analyze_media",
            input_schema=_visual_analyze_input_schema(),
            output_schema=_direct_output_schema(
                "Visual analysis payload returned by Museon API, including usage "
                "and media-import guidance when direct media preparation fails."
            ),
            examples=[
                (
                    "museoncli research +visual-analyze --media "
                    "https://example.com/image.png --prompt 'Assess visual style.'"
                ),
                (
                    "museoncli asset +create --type media --url "
                    "https://p16-sign.tiktokcdn-us.com/... && "
                    "museoncli research +visual-analyze --media <media_url> "
                    "--prompt 'Assess visual style.'"
                ),
                (
                    "museoncli research +visual-analyze --media-json "
                    '\'[{"url":"https://...","label":"hero"}]\' '
                    "--prompt 'Compare composition.'"
                ),
            ],
            add_arguments=_add_visual_analyze_arguments,
            build_arguments=_build_visual_analyze_arguments,
        ),
    ]


# ---- executors ----

_RESEARCH_PATHS = {
    "research.web-research": "/agent-cli/research/web-research",
    "research.social-media-search": "/agent-cli/research/social-media-search",
    "research.community-search": "/agent-cli/research/community-search",
    "research.visual-analyze": "/agent-cli/research/visual-analyze",
}


async def _execute_research(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    return agent_domain_result(
        await ctx.api_data(
            ctx.cfg,
            "POST",
            _RESEARCH_PATHS[ctx.spec.schema_name],
            json_body={"workspace_id": ctx.workspace_id, "payload": ctx.arguments},
        )
    )


async def _execute_creative_search_ads(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    return agent_domain_result(
        await ctx.api_data(
            ctx.cfg,
            "POST",
            "/agent-cli/research/creative-search-ads",
            json_body={"workspace_id": ctx.workspace_id, "payload": ctx.arguments},
        )
    )


async def _execute_social_hook_analyze(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    return agent_domain_result(
        await ctx.api_data(
            ctx.cfg,
            "POST",
            "/agent-cli/research/social-media-hook-analyze",
            json_body={"workspace_id": ctx.workspace_id, "payload": ctx.arguments},
        )
    )


async def _execute_social_hook_source(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    return agent_domain_result(
        await ctx.api_data(
            ctx.cfg,
            "POST",
            "/agent-cli/research/social-media-hook-source",
            json_body={"workspace_id": ctx.workspace_id, "payload": ctx.arguments},
        )
    )


async def _execute_social_hook_analyze_seen(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    return agent_domain_result(
        await ctx.api_data(
            ctx.cfg,
            "POST",
            "/agent-cli/research/social-media-hook-analyze-seen",
            json_body={"workspace_id": ctx.workspace_id, "payload": ctx.arguments},
        )
    )


async def _execute_social_hook_get(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    analysis_id = ctx.arguments["analysis_id"]
    return agent_domain_result(
        await ctx.api_data(
            ctx.cfg,
            "GET",
            f"/agent-cli/research/social-media-hook-analyze/{analysis_id}",
            params={"workspace_id": ctx.workspace_id},
        )
    )


async def _execute_social_hook_poll(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    return agent_domain_result(
        await ctx.api_data(
            ctx.cfg,
            "POST",
            "/agent-cli/research/social-media-hook-analyze-poll",
            json_body={"workspace_id": ctx.workspace_id, "payload": ctx.arguments},
        )
    )


async def _execute_social_hook_results(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    analysis_id = ctx.arguments["analysis_id"]
    params = {
        "workspace_id": ctx.workspace_id,
        **{key: value for key, value in ctx.arguments.items() if key != "analysis_id"},
    }
    return agent_domain_result(
        await ctx.api_data(
            ctx.cfg,
            "GET",
            f"/agent-cli/research/social-media-hook-analyze/{analysis_id}/results",
            params=params,
        )
    )


async def _execute_social_hook_media_get(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    if ctx.download_api_file is None:
        raise RuntimeError("download_transport_unavailable")
    destination = Path(str(ctx.arguments["output"])).expanduser().resolve()
    if destination.exists() and not ctx.arguments.get("force"):
        raise RuntimeError("output_exists")
    if destination.exists() and not destination.is_file():
        raise RuntimeError("output_not_file")
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.{uuid4().hex}.part")
    try:
        metadata = await ctx.download_api_file(
            ctx.cfg,
            (
                "/agent-cli/research/social-media-hook-analyze/"
                f"{ctx.arguments['analysis_id']}/items/{ctx.arguments['item_id']}/media"
            ),
            params={"workspace_id": ctx.workspace_id},
            destination=temporary,
            max_bytes=30 * 1024 * 1024,
        )
        if destination.exists() and not ctx.arguments.get("force"):
            raise RuntimeError("output_exists")
        temporary.replace(destination)
    finally:
        temporary.unlink(missing_ok=True)
    return {
        "analysis_id": ctx.arguments["analysis_id"],
        "item_id": ctx.arguments["item_id"],
        "path": str(destination),
        "content_type": metadata["content_type"],
        "bytes": metadata["bytes"],
    }


async def _execute_creative_search_ads_get(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    task_id = ctx.arguments["task_id"]
    return agent_domain_result(
        await ctx.api_data(
            ctx.cfg,
            "GET",
            f"/agent-cli/research/creative-search-ads/{task_id}",
            params={"workspace_id": ctx.workspace_id},
        )
    )


async def _execute_creative_search_ads_results(ctx: CommandContext) -> Any:
    if not ctx.workspace_id:
        raise RuntimeError("missing_workspace")
    task_id = ctx.arguments["task_id"]
    params = {
        "workspace_id": ctx.workspace_id,
        **{key: value for key, value in ctx.arguments.items() if key != "task_id"},
    }
    return agent_domain_result(
        await ctx.api_data(
            ctx.cfg,
            "GET",
            f"/agent-cli/research/creative-search-ads/{task_id}/results",
            params=params,
        )
    )


EXECUTORS = {
    **{schema: direct_enveloped(_execute_research) for schema in _RESEARCH_PATHS},
    "research.creative-search-ads": direct_enveloped(_execute_creative_search_ads),
    "research.creative-search-ads-get": direct_enveloped(_execute_creative_search_ads_get),
    "research.creative-search-ads-results": direct_enveloped(_execute_creative_search_ads_results),
    "research.social-media-hook-analyze": direct_enveloped(_execute_social_hook_analyze),
    "research.social-media-hook-source": direct_enveloped(_execute_social_hook_source),
    "research.social-media-hook-analyze-seen": direct_enveloped(
        _execute_social_hook_analyze_seen
    ),
    "research.social-media-hook-analyze-get": direct_enveloped(_execute_social_hook_get),
    "research.social-media-hook-analyze-poll": direct_enveloped(_execute_social_hook_poll),
    "research.social-media-hook-analyze-results": direct_enveloped(_execute_social_hook_results),
    "research.social-media-hook-analyze-media-get": direct_enveloped(
        _execute_social_hook_media_get
    ),
}
