"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

from museoncli.execution import compact_params

from museoncli.execution import (
    CommandContext,
    direct_enveloped,
)

import argparse
import json
from pathlib import Path
from typing import Any
from museoncli.domains._model import CommandSpec, Domain
from museoncli.domains._shared import _direct_output_schema


SKILL_DESCRIPTION_MAX_LENGTH = 20000


SKILL_CONTENT_MAX_LENGTH = 200000


def _add_skills_list_arguments(parser: argparse.ArgumentParser) -> None:
    _ = parser


def _build_skills_list_arguments(args: argparse.Namespace) -> dict[str, Any]:
    _ = args
    return {}


def _add_skills_get_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--name", required=True)
    parser.add_argument("--offset", type=int, default=0)
    parser.add_argument("--limit", type=int, default=1000)


def _build_skills_get_arguments(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "name": args.name,
        "offset": args.offset,
        "limit": args.limit,
    }


def _add_skills_create_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--name", required=True)
    parser.add_argument("--workspace-id")
    parser.add_argument("--description")
    parser.add_argument("--reference-json")
    parser.add_argument("--is-active", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--is-public", action=argparse.BooleanOptionalAction, default=False)
    content = parser.add_mutually_exclusive_group(required=True)
    content.add_argument("--content")
    content.add_argument("--content-file")
    parser.add_argument("--dry-run", action="store_true")


def _build_skills_create_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "name": args.name,
        "description": args.description,
        "content": _skill_content_argument(args),
        "is_active": args.is_active,
        "is_public": args.is_public,
    }
    if args.workspace_id is not None:
        payload["workspace_id"] = args.workspace_id
    if args.reference_json is not None:
        payload["reference"] = _json_argument(args.reference_json, field="--reference-json")
    return payload


def _add_skills_update_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--name", required=True)
    parser.add_argument("--description")
    parser.add_argument("--reference-json")
    parser.add_argument("--is-active", action=argparse.BooleanOptionalAction, default=None)
    parser.add_argument("--is-public", action=argparse.BooleanOptionalAction, default=None)
    content = parser.add_mutually_exclusive_group()
    content.add_argument("--content")
    content.add_argument("--content-file")
    parser.add_argument("--dry-run", action="store_true")


def _build_skills_update_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload: dict[str, Any] = {"name": args.name}
    if args.description is not None:
        payload["description"] = args.description
    if args.reference_json is not None:
        payload["reference"] = _json_argument(args.reference_json, field="--reference-json")
    if args.content is not None or args.content_file is not None:
        payload["content"] = _skill_content_argument(args)
    if args.is_active is not None:
        payload["is_active"] = args.is_active
    if args.is_public is not None:
        payload["is_public"] = args.is_public
    return payload


def _skill_content_argument(args: argparse.Namespace) -> str:
    content = getattr(args, "content", None)
    if content is not None:
        return str(content)
    content_file = getattr(args, "content_file", None)
    if content_file is None:
        return ""
    return Path(content_file).read_text(encoding="utf-8")


def _json_argument(value: str, *, field: str) -> Any:
    try:
        return json.loads(value)
    except json.JSONDecodeError as exc:
        raise ValueError(f"{field} must be valid JSON: {exc.msg}") from exc


def _skills_list_input_schema() -> dict[str, Any]:
    return {"type": "object", "properties": {}, "required": []}


def _skills_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "name": {"type": "string", "minLength": 1},
            "offset": {"type": "integer", "minimum": 0, "default": 0},
            "limit": {"type": "integer", "minimum": 1, "maximum": 1000, "default": 1000},
        },
        "required": ["name"],
    }


def _skills_create_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "name": {"type": "string", "minLength": 1, "maxLength": 80},
            "workspace_id": {"type": "string", "minLength": 1},
            "description": {"type": "string", "maxLength": SKILL_DESCRIPTION_MAX_LENGTH},
            "reference": {"description": "Optional JSON metadata for this skill."},
            "content": {"type": "string", "minLength": 1, "maxLength": SKILL_CONTENT_MAX_LENGTH},
            "is_active": {"type": "boolean", "default": True},
            "is_public": {"type": "boolean", "default": False},
        },
        "required": ["name", "content"],
    }


def _skills_update_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "name": {"type": "string", "minLength": 1, "maxLength": 80},
            "description": {"type": "string", "maxLength": SKILL_DESCRIPTION_MAX_LENGTH},
            "reference": {"description": "Optional JSON metadata for this skill."},
            "content": {"type": "string", "minLength": 1, "maxLength": SKILL_CONTENT_MAX_LENGTH},
            "is_active": {"type": "boolean"},
            "is_public": {"type": "boolean"},
        },
        "required": ["name"],
    }


def specs() -> list[CommandSpec]:
    return [
        CommandSpec(
            domain=Domain.SKILLS,
            shortcut="+list",
            summary="List business skills available to the current agent runtime.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="skills_list",
            input_schema=_skills_list_input_schema(),
            output_schema=_direct_output_schema("Skill catalog returned by Museon API."),
            examples=["museoncli skills +list"],
            add_arguments=_add_skills_list_arguments,
            build_arguments=_build_skills_list_arguments,
        ),
        CommandSpec(
            domain=Domain.SKILLS,
            shortcut="+get",
            summary="Read one business skill by name.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="skills_get",
            input_schema=_skills_get_input_schema(),
            output_schema=_direct_output_schema("Skill detail returned by Museon API."),
            examples=["museoncli skills +get --name social-persona-account-analysis"],
            add_arguments=_add_skills_get_arguments,
            build_arguments=_build_skills_get_arguments,
        ),
        CommandSpec(
            domain=Domain.SKILLS,
            shortcut="+create",
            summary=(
                "Create one workspace-private Museon skill from Markdown content; "
                "--is-public requires organization admin permission."
            ),
            risk_level="write",
            execution="direct",
            adapter_tool_name="skills_create",
            input_schema=_skills_create_input_schema(),
            output_schema=_direct_output_schema("Created skill detail returned by Museon API."),
            examples=[
                (
                    "museoncli skills +create --name social-persona-account-analysis "
                    '--content-file ./SKILL.md --reference-json \'{"source":"ops"}\''
                )
            ],
            add_arguments=_add_skills_create_arguments,
            build_arguments=_build_skills_create_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.SKILLS,
            shortcut="+update",
            summary=(
                "Update a workspace-private Museon skill's Markdown content, description, "
                "reference, or active status; changing --is-public requires organization "
                "admin permission."
            ),
            risk_level="write",
            execution="direct",
            adapter_tool_name="skills_update",
            input_schema=_skills_update_input_schema(),
            output_schema=_direct_output_schema("Updated skill detail returned by Museon API."),
            examples=[
                (
                    "museoncli skills +update --name social-persona-account-analysis "
                    "--content-file ./SKILL.md --no-is-active"
                )
            ],
            add_arguments=_add_skills_update_arguments,
            build_arguments=_build_skills_update_arguments,
            supports_dry_run=True,
        ),
    ]


# ---- executors (generated from main.py direct_* chains) ----
async def _execute_create(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    api_data = ctx.api_data
    payload = dict(arguments)
    if ctx.workspace_id and "workspace_id" not in payload:
        payload["workspace_id"] = ctx.workspace_id
    return await api_data(cfg, "POST", "/agent-cli/skills", json_body=payload)


async def _execute_get(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    api_data = ctx.api_data
    name = str(arguments.get("name") or "")
    if not name:
        raise RuntimeError("missing_skill_name")
    return await api_data(
        cfg,
        "GET",
        f"/agent-cli/skills/{name}",
        params=compact_params(
            {
                "offset": arguments.get("offset", 0),
                "limit": arguments.get("limit", 1000),
                "workspace_id": ctx.workspace_id,
            }
        ),
    )


async def _execute_list(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    api_data = ctx.api_data
    return await api_data(
        cfg,
        "GET",
        "/agent-cli/skills",
        params=compact_params({"workspace_id": ctx.workspace_id}),
    )


async def _execute_update(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    api_data = ctx.api_data
    name = str(arguments.get("name") or "")
    if not name:
        raise RuntimeError("missing_skill_name")
    payload = {key: value for key, value in arguments.items() if key != "name"}
    return await api_data(cfg, "PATCH", f"/agent-cli/skills/{name}", json_body=payload)


EXECUTORS = {
    "skills.create": direct_enveloped(_execute_create),
    "skills.get": direct_enveloped(_execute_get, with_workspace=False),
    "skills.list": direct_enveloped(_execute_list, with_workspace=False),
    "skills.update": direct_enveloped(_execute_update, with_workspace=False),
}
