"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

import argparse
import asyncio
import json
import time
from typing import Any

from museoncli.config import Config
from museoncli.domains._model import CommandSpec, Domain
from museoncli.domains._shared import (
    _add_common_adapter_arguments,
    _async_output_schema,
    _direct_output_schema,
    _load_structured_args,
    _ordered_strings,
    _uuid_id_schema,
    _without_none,
    dekebab,
    kebab_choices,
)
from museoncli.envelopes import _profile_edit_task_id
from museoncli.execution import (
    CommandContext,
    _dict_argument,
    agent_domain_result,
    api_data,
    compact_params,
    direct_enveloped,
    routine_turn_context,
)

SOCIAL_ACCOUNT_PLAN_STATUS_CHOICES = ["all", "with-plan", "without-plan"]


SOCIAL_ACCOUNT_CONNECT_PLATFORM_CHOICES = ["tiktok", "instagram", "facebook", "linkedin", "x"]


SOCIAL_ACCOUNT_PERFORMANCE_PERIOD_CHOICES = ["last-7d", "last-30d", "last-60d"]


SOCIAL_ACCOUNT_ALLOCATION_TYPE_CHOICES = [
    "all",
    "campaign",
    "account_publish",
    "unallocated",
]


SOCIAL_ACCOUNT_SEARCH_TERMS_MAX = 100
ADB_COMMAND_TIMEOUT_SECONDS = 20


SOCIAL_ACCOUNT_PROFILE_EDIT_TARGET_CHOICES = ["nickName", "bio", "avatar"]


SOCIAL_ACCOUNT_PROFILE_EDIT_DEFAULT_TARGETS = ["nickName", "bio"]


def _add_social_account_list_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--platform", help="Omit to list accounts across all platforms.")
    parser.add_argument(
        "--search",
        help="Single search term only. For multiple known handles, repeat --search-term.",
    )
    parser.add_argument(
        "--search-term",
        action="append",
        dest="search_terms",
        help=(
            "Exact batch handle term; repeat to match many handles in one request. "
            "Leading @ or TikTok profile URLs are accepted. Max 100 terms."
        ),
    )
    parser.add_argument(
        "--plan-status",
        choices=SOCIAL_ACCOUNT_PLAN_STATUS_CHOICES,
        default="all",
    )
    parser.add_argument(
        "--allocation-type",
        choices=kebab_choices(SOCIAL_ACCOUNT_ALLOCATION_TYPE_CHOICES),
        default="all",
    )
    parser.add_argument("--allocation-status")
    parser.add_argument("--oauth-status", choices=["active", "expired", "unverified"])
    parser.add_argument("--issue-type")
    parser.add_argument("--performance-level", action="append", dest="performance_levels")
    parser.add_argument("--include-null-level", action="store_true")
    parser.add_argument(
        "--tag",
        help="Filter by workspace tag (single value, set via +assets-set --tag).",
    )
    parser.add_argument("--group-name")
    parser.add_argument("--lookup-status")
    parser.add_argument("--include-inactive", action="store_true")
    public_group = parser.add_mutually_exclusive_group()
    public_group.add_argument("--public-only", action="store_true")
    public_group.add_argument("--private-only", action="store_true")
    device_group = parser.add_mutually_exclusive_group()
    device_group.add_argument("--has-device", action="store_true")
    device_group.add_argument("--without-device", action="store_true")
    parser.add_argument("--page", type=int, default=1)
    parser.add_argument("--page-size", type=int, default=100)


def _build_social_account_list_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    search_terms = _ordered_strings(args.search_terms) if args.search_terms else None
    if search_terms and len(search_terms) > SOCIAL_ACCOUNT_SEARCH_TERMS_MAX:
        raise ValueError(
            f"social-account +list supports at most {SOCIAL_ACCOUNT_SEARCH_TERMS_MAX} "
            "--search-term values per request."
        )
    payload.update(
        _without_none(
            {
                "platform": args.platform,
                "search": args.search,
                "search_terms": search_terms,
                "automation_status": (args.plan_status if args.plan_status != "all" else None),
                "allocation_type": (
                    dekebab(args.allocation_type) if args.allocation_type != "all" else None
                ),
                "allocation_status": args.allocation_status,
                "oauth_status": args.oauth_status,
                "issue_type": args.issue_type,
                "performance_levels": (
                    ",".join(args.performance_levels) if args.performance_levels else None
                ),
                "include_null_level": True if args.include_null_level else None,
                "tag": args.tag,
                "group_name": args.group_name,
                "lookup_status": args.lookup_status,
                "is_active": None if args.include_inactive else True,
                "is_public": (True if args.public_only else False if args.private_only else None),
                "has_device": (True if args.has_device else False if args.without_device else None),
                "page": args.page,
                "page_size": args.page_size,
            }
        )
    )
    return payload


def _add_social_account_id_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", required=True, dest="account_id")


def _build_social_account_id_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload["account_id"] = args.account_id
    return payload


def _add_social_account_adb_connect_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    target = parser.add_mutually_exclusive_group(required=True)
    target.add_argument("--id", dest="account_id")
    target.add_argument("--handle")
    parser.add_argument(
        "--platform",
        help="Required with --handle; must exactly match the account platform.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate the intended account target without enabling ADB or connecting locally.",
    )


def _build_social_account_adb_connect_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    if args.account_id:
        payload["account_id"] = args.account_id
        return payload
    if not args.platform:
        raise ValueError("social-account +connect-adb requires --platform with --handle.")
    payload.update({"handle": args.handle, "platform": args.platform})
    if args.workspace_id:
        payload["workspace_id"] = args.workspace_id
    return payload


def _add_social_account_profile_edit_draft_arguments(parser: argparse.ArgumentParser) -> None:
    _add_social_account_id_arguments(parser)
    parser.add_argument("--prompt", required=True)
    parser.add_argument(
        "--target",
        action="append",
        dest="targets",
        choices=SOCIAL_ACCOUNT_PROFILE_EDIT_TARGET_CHOICES,
    )


def _build_social_account_profile_edit_draft_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _build_social_account_id_arguments(args)
    payload["profile_edit"] = {
        "prompt": args.prompt,
        "targets": args.targets or SOCIAL_ACCOUNT_PROFILE_EDIT_DEFAULT_TARGETS,
    }
    return payload


def _add_social_account_profile_edit_submit_arguments(parser: argparse.ArgumentParser) -> None:
    _add_social_account_id_arguments(parser)
    parser.add_argument("--nick-name")
    parser.add_argument("--bio")
    parser.add_argument("--avatar-url")
    parser.add_argument("--wait", action="store_true")
    parser.add_argument("--timeout", type=float, default=300.0)
    parser.add_argument("--poll-interval", type=float, default=5.0)
    parser.add_argument("--dry-run", action="store_true")


def _build_social_account_profile_edit_submit_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _build_social_account_id_arguments(args)
    profile_edit = _without_none(
        {
            "nick_name": args.nick_name,
            "bio": args.bio,
            "avatar_url": args.avatar_url,
        }
    )
    if not profile_edit:
        raise ValueError(
            "social-account +submit-profile-edit requires --nick-name, --bio, or --avatar-url."
        )
    payload["profile_edit"] = profile_edit
    payload["wait"] = args.wait
    payload["wait_timeout_seconds"] = args.timeout
    payload["poll_interval_seconds"] = args.poll_interval
    return payload


def _add_social_account_avatar_generate_batch_arguments(
    parser: argparse.ArgumentParser,
) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", action="append", dest="account_ids", required=True)
    parser.add_argument("--prompt", required=True)
    parser.add_argument("--wait", action="store_true")
    parser.add_argument("--timeout", type=float, default=300.0)
    parser.add_argument("--poll-interval", type=float, default=5.0)


def _build_social_account_avatar_generate_batch_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _load_structured_args(args)
    account_ids = args.account_ids or []
    if not account_ids:
        raise ValueError("--id must be provided at least once")
    payload["account_ids"] = account_ids
    payload["prompt"] = args.prompt
    payload["wait"] = args.wait
    payload["wait_timeout_seconds"] = args.timeout
    payload["poll_interval_seconds"] = args.poll_interval
    return payload


def _add_social_account_avatar_generate_status_arguments(
    parser: argparse.ArgumentParser,
) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", dest="task_id", required=True)


def _build_social_account_avatar_generate_status_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload["task_id"] = args.task_id
    return payload


def _add_social_account_profile_edit_status_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", dest="task_id", required=True)


def _build_social_account_profile_edit_status_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload["task_id"] = args.task_id
    return payload


def _add_social_account_profile_edit_batch_submit_arguments(
    parser: argparse.ArgumentParser,
) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument(
        "--account-updates",
        required=True,
        help="JSON array of {account_id, nick_name?, bio?, avatar_url?} objects.",
    )
    parser.add_argument("--update-nick-name", action="store_true")
    parser.add_argument("--update-bio", action="store_true")
    parser.add_argument("--update-avatar", action="store_true")
    parser.add_argument("--avatar-url")
    parser.add_argument("--wait", action="store_true")
    parser.add_argument("--timeout", type=float, default=300.0)
    parser.add_argument("--poll-interval", type=float, default=5.0)
    parser.add_argument("--dry-run", action="store_true")


def _build_social_account_profile_edit_batch_submit_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _load_structured_args(args)
    try:
        account_updates = json.loads(args.account_updates)
    except json.JSONDecodeError as exc:
        raise ValueError(f"--account-updates must be valid JSON: {exc}") from exc
    if not isinstance(account_updates, list) or not account_updates:
        raise ValueError("--account-updates must be a non-empty JSON array")
    payload["account_updates"] = account_updates
    payload["update_nick_name"] = getattr(args, "update_nick_name", False)
    payload["update_bio"] = getattr(args, "update_bio", False)
    payload["update_avatar"] = getattr(args, "update_avatar", False)
    if args.avatar_url:
        payload["avatar_url"] = args.avatar_url
    payload["wait"] = args.wait
    payload["wait_timeout_seconds"] = args.timeout
    payload["poll_interval_seconds"] = args.poll_interval
    return payload


def _social_account_list_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "platform": {
                "type": ["string", "null"],
                "description": "Filter by platform; omit to list all platforms.",
            },
            "search": {
                "type": ["string", "null"],
                "description": (
                    "Single search term only. For multiple known handles, use "
                    "search_terms / repeated --search-term instead of concatenating "
                    "handles or paging through the pool."
                ),
            },
            "search_terms": {
                "type": ["array", "null"],
                "items": {"type": "string", "minLength": 1},
                "maxItems": SOCIAL_ACCOUNT_SEARCH_TERMS_MAX,
                "description": (
                    "Batch exact handle terms. Matches normalized handles against pool "
                    "account handles and linked creator username/nickname. Repeat "
                    "--search-term in CLI; leading @ or TikTok profile URLs are accepted. "
                    "Use this when resolving many known handles in one request; do not "
                    "scan pages."
                ),
            },
            "automation_status": {
                "type": ["string", "null"],
                "enum": ["with-plan", "without-plan", None],
            },
            "allocation_type": {
                "type": ["string", "null"],
                "enum": ["all", "campaign", "account-publish", "unallocated", None],
            },
            "allocation_status": {"type": ["string", "null"]},
            "oauth_status": {
                "type": ["string", "null"],
                "enum": ["active", "expired", "unverified", None],
            },
            "issue_type": {"type": ["string", "null"]},
            "performance_levels": {"type": ["string", "null"]},
            "include_null_level": {"type": ["boolean", "null"]},
            "tag": {
                "type": ["string", "null"],
                "description": ("Filter by workspace-private tag (single value)."),
            },
            "group_name": {"type": ["string", "null"]},
            "lookup_status": {"type": ["string", "null"]},
            "is_active": {"type": ["boolean", "null"], "default": True},
            "is_public": {"type": ["boolean", "null"]},
            "has_device": {"type": ["boolean", "null"]},
            "page": {"type": "integer", "minimum": 1, "default": 1},
            "page_size": {"type": "integer", "minimum": 1, "maximum": 200, "default": 100},
        },
    }


def _social_account_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {"account_id": _uuid_id_schema("Pool account UUID, not a list caption.")},
        "required": ["account_id"],
    }


def _social_account_adb_connect_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "account_id": _uuid_id_schema(
                "Pool account UUID. Mutually exclusive with handle. Museon resolves its "
                "active cloud phone internally."
            ),
            "handle": {
                "type": "string",
                "minLength": 1,
                "description": (
                    "Account handle resolved by the server. Mutually exclusive with account_id; "
                    "platform is required when handle is used."
                ),
            },
            "platform": {
                "type": "string",
                "minLength": 1,
                "description": (
                    "Exact platform string. Required with handle; accepts the same unrestricted "
                    "platform values as social-account +list."
                ),
            },
            "workspace_id": {
                "type": ["string", "null"],
                "format": "uuid",
                "description": (
                    "Optional explicit workspace scope for handle resolution. Omitted unless "
                    "--workspace-id is passed; the selected workspace is not injected."
                ),
            },
        },
        "oneOf": [
            {"required": ["account_id"], "not": {"required": ["handle"]}},
            {
                "required": ["handle", "platform"],
                "not": {"required": ["account_id"]},
            },
        ],
    }


def _social_account_profile_edit_draft_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "account_id": _uuid_id_schema("Pool account UUID."),
            "profile_edit": {
                "type": "object",
                "properties": {
                    "prompt": {"type": "string", "minLength": 1},
                    "targets": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "enum": SOCIAL_ACCOUNT_PROFILE_EDIT_TARGET_CHOICES,
                        },
                        "default": SOCIAL_ACCOUNT_PROFILE_EDIT_DEFAULT_TARGETS,
                    },
                },
                "required": ["prompt"],
            },
        },
        "required": ["account_id", "profile_edit"],
    }


def _social_account_profile_edit_submit_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "account_id": _uuid_id_schema("Pool account UUID with profile editing enabled."),
            "profile_edit": {
                "type": "object",
                "description": (
                    "Patch-style profile update. Passing nick_name, bio, or avatar_url "
                    "automatically enables the matching update flag."
                ),
                "properties": {
                    "nick_name": {
                        "type": ["string", "null"],
                        "maxLength": 30,
                        "description": "TikTok display name. Platform nickname cooldown applies.",
                    },
                    "bio": {"type": ["string", "null"], "maxLength": 160},
                    "avatar_url": {"type": ["string", "null"]},
                },
            },
            "wait": {"type": "boolean", "default": False},
            "wait_timeout_seconds": {"type": "number", "default": 300},
            "poll_interval_seconds": {"type": "number", "default": 5},
            "dry_run": {"type": "boolean", "default": False},
        },
        "required": ["account_id", "profile_edit"],
    }


def _social_account_profile_edit_status_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "task_id": _uuid_id_schema("Task UUID returned by social-account +submit-profile-edit.")
        },
        "required": ["task_id"],
    }


def _social_account_profile_edit_batch_submit_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "account_updates": {
                "description": (
                    "Non-empty array of per-account profile edits. "
                    "Each object must include account_id. "
                    "Optional per-account fields: nick_name, bio, avatar_url."
                ),
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "object",
                    "properties": {
                        "account_id": _uuid_id_schema(
                            "Pool account UUID with profile editing enabled."
                        ),
                        "nick_name": {
                            "type": ["string", "null"],
                            "description": "TikTok display name.",
                            "maxLength": 30,
                        },
                        "bio": {
                            "type": ["string", "null"],
                            "maxLength": 160,
                        },
                        "avatar_url": {"type": ["string", "null"]},
                    },
                    "required": ["account_id"],
                },
            },
            "update_nick_name": {"type": "boolean", "default": False},
            "update_bio": {"type": "boolean", "default": False},
            "update_avatar": {"type": "boolean", "default": False},
            "avatar_url": {"type": ["string", "null"]},
            "wait": {"type": "boolean", "default": False},
            "wait_timeout_seconds": {"type": "number", "default": 300},
            "poll_interval_seconds": {"type": "number", "default": 5},
            "dry_run": {"type": "boolean", "default": False},
        },
        "required": ["account_updates"],
    }


def _social_account_avatar_generate_batch_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "account_ids": {
                "description": (
                    "Non-empty array of pool account UUIDs to generate avatar drafts for. "
                    "Group accounts that share one base prompt into a single batch "
                    "(at most 20 per batch)."
                ),
                "type": "array",
                "minItems": 1,
                "items": _uuid_id_schema("Pool account UUID with profile editing enabled."),
            },
            "prompt": {
                "type": "string",
                "minLength": 1,
                "description": "Shared base avatar prompt; the server personalizes it per account.",
            },
            "wait": {"type": "boolean", "default": False},
            "wait_timeout_seconds": {"type": "number", "default": 300},
            "poll_interval_seconds": {"type": "number", "default": 5},
        },
        "required": ["account_ids", "prompt"],
    }


def _social_account_avatar_generate_status_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "task_id": _uuid_id_schema(
                "Task UUID returned by social-account +bulk-generate-avatars."
            )
        },
        "required": ["task_id"],
    }


def _add_social_account_connect_link_create_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--platform", choices=SOCIAL_ACCOUNT_CONNECT_PLATFORM_CHOICES)
    parser.add_argument("--expires-in-days", type=int, default=7)
    parser.add_argument("--redirect-url")
    parser.add_argument("--dry-run", action="store_true")


def _build_social_account_connect_link_create_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _load_structured_args(args)
    if args.platform is not None:
        payload["platform"] = args.platform
    payload["expires_in_days"] = args.expires_in_days
    # A connect link authorizes exactly one platform; a silent default here
    # used to mint TikTok links when the flag was forgotten, so the platform
    # must always be stated explicitly (flag or structured args).
    platform = payload.get("platform")
    if platform not in SOCIAL_ACCOUNT_CONNECT_PLATFORM_CHOICES:
        choices = "|".join(SOCIAL_ACCOUNT_CONNECT_PLATFORM_CHOICES)
        raise ValueError(f"social-account +create-connect-link requires --platform ({choices}).")
    if args.redirect_url is not None:
        payload["redirect_url"] = args.redirect_url
    return payload


def _add_social_account_connect_link_status_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", dest="link_id", required=True)
    parser.add_argument("--wait", action="store_true")
    parser.add_argument("--timeout", type=int, default=0)
    parser.add_argument("--poll-interval", type=float, default=2.0)


def _build_social_account_connect_link_status_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update(
        {
            "link_id": args.link_id,
            "wait": args.wait,
            "timeout": args.timeout,
            "poll_interval": args.poll_interval,
        }
    )
    if not str(payload.get("link_id") or "").strip():
        raise ValueError("social-account +get-connect-link requires --id.")
    return payload


def _social_account_connect_link_create_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "platform": {
                "type": "string",
                "enum": SOCIAL_ACCOUNT_CONNECT_PLATFORM_CHOICES,
                "description": (
                    "User-owned account platform to authorize. Required — always "
                    "pass the platform the user asked to connect."
                ),
            },
            "expires_in_days": {
                "type": ["integer", "null"],
                "minimum": 1,
                "default": 7,
                "description": (
                    "TikTok connect link lifetime. Ignored for managed OAuth platforms."
                ),
            },
            "redirect_url": {
                "type": ["string", "null"],
                "format": "uri",
                "description": "Optional OAuth redirect URL for managed OAuth platforms.",
            },
        },
        "required": ["platform"],
    }


def _social_account_connect_link_status_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "link_id": _uuid_id_schema("Connect link UUID returned by +create-connect-link."),
            "wait": {
                "type": "boolean",
                "default": False,
                "description": "Poll until completed, expired, revoked, or timeout.",
            },
            "timeout": {
                "type": "integer",
                "minimum": 0,
                "maximum": 3600,
                "default": 0,
            },
            "poll_interval": {
                "type": "number",
                "minimum": 0.1,
                "maximum": 60,
                "default": 2.0,
            },
        },
        "required": ["link_id"],
    }


def _add_social_account_performance_get_arguments(parser: argparse.ArgumentParser) -> None:
    _add_social_account_id_arguments(parser)
    parser.add_argument(
        "--period",
        choices=SOCIAL_ACCOUNT_PERFORMANCE_PERIOD_CHOICES,
        default="last-30d",
    )
    parser.add_argument(
        "--cursor",
        help="Opaque pagination cursor; pass page.next_cursor from the previous call.",
    )
    parser.add_argument("--page-size", type=int, default=20)


def _build_social_account_performance_get_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _build_social_account_id_arguments(args)
    payload.update(
        _without_none(
            {
                "period": dekebab(args.period),
                "cursor": args.cursor,
                "page_size": args.page_size,
            }
        )
    )
    return payload


def _social_account_performance_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "account_id": _uuid_id_schema("Pool account UUID."),
            "period": {
                "type": "string",
                "enum": ["last-7d", "last-30d", "last-60d"],
                "default": "last-30d",
            },
            "cursor": {
                "type": ["string", "null"],
                "description": (
                    "Opaque pagination cursor. Omit for the first page (which also "
                    "includes the account-level profile block); pass page.next_cursor "
                    "from the previous response for the next page of posts."
                ),
            },
            "page_size": {
                "type": "integer",
                "minimum": 1,
                "maximum": 50,
                "default": 20,
            },
        },
        "required": ["account_id"],
    }


def specs() -> list[CommandSpec]:
    return [
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+list",
            summary=(
                "List social accounts available to the current workspace. For "
                "multiple known handles, repeat --search-term (max 100) "
                "in one request; do not concatenate handles into --search or page-scan "
                "the account list."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_account_list",
            input_schema=_social_account_list_input_schema(),
            output_schema=_direct_output_schema(
                "Social account list payload returned by Museon API."
            ),
            examples=[
                "museoncli social-account +list --platform tiktok --plan-status with-plan",
                "museoncli social-account +list --search creator --allocation-type account-publish",
                (
                    "museoncli social-account +list --platform tiktok "
                    "--search-term @handle_a --search-term @handle_b"
                ),
                "museoncli social-account +list --platform tiktok --tag coohom --has-device",
            ],
            add_arguments=_add_social_account_list_arguments,
            build_arguments=_build_social_account_list_arguments,
        ),
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+get",
            summary="Read one workspace social account.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_account_get",
            input_schema=_social_account_get_input_schema(),
            output_schema=_direct_output_schema(
                "Social account detail payload returned by Museon API."
            ),
            examples=["museoncli social-account +get --id <pool_account_id>"],
            add_arguments=_add_social_account_id_arguments,
            build_arguments=_build_social_account_id_arguments,
        ),
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+connect-adb",
            legacy_shortcuts=("+adb-connect",),
            summary=(
                "Connect the current sandbox to this account's cloud phone over ADB. "
                "After success, use native adb or u2cli with the returned serial; "
                "the temporary connection password is never printed."
            ),
            risk_level="write",
            execution="direct",
            adapter_tool_name="social_account_adb_connect",
            input_schema=_social_account_adb_connect_input_schema(),
            output_schema=_direct_output_schema(
                "Local ADB connection result with a serial ready for native adb and u2cli."
            ),
            examples=[
                "museoncli social-account +connect-adb --id <pool_account_id>",
                "museoncli social-account +connect-adb --handle @creator --platform tiktok",
                "museoncli social-account +connect-adb --id <pool_account_id> --dry-run",
            ],
            add_arguments=_add_social_account_adb_connect_arguments,
            build_arguments=_build_social_account_adb_connect_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+get-stream-url",
            legacy_shortcuts=("+stream-url",),
            summary=(
                "Return this account's cloud-phone live-stream URL. The sandbox stream "
                "sidecar renders it to capture fast motion the u2cli clip command needs; "
                "the URL views the same phone adb-connect controls."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_account_stream_url",
            input_schema=_social_account_get_input_schema(),
            output_schema=_direct_output_schema("Cloud-phone remote stream URL and its phone id."),
            examples=["museoncli social-account +get-stream-url --id <pool_account_id>"],
            add_arguments=_add_social_account_id_arguments,
            build_arguments=_build_social_account_id_arguments,
        ),
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+create-connect-link",
            legacy_shortcuts=("+connect-link-create",),
            summary=(
                "Create a workspace self-authorization link to connect a user-owned "
                "social account. Supports TikTok, Instagram, Facebook, LinkedIn, and X."
            ),
            risk_level="write",
            execution="direct",
            adapter_tool_name="social_account_connect_link_create",
            input_schema=_social_account_connect_link_create_input_schema(),
            output_schema=_direct_output_schema(
                "Created social OAuth connect link returned by Museon API."
            ),
            examples=[
                "museoncli social-account +create-connect-link --platform tiktok --expires-in-days 7",
                "museoncli social-account +create-connect-link --platform instagram",
                "museoncli social-account +create-connect-link --platform x",
            ],
            add_arguments=_add_social_account_connect_link_create_arguments,
            build_arguments=_build_social_account_connect_link_create_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+get-connect-link",
            legacy_shortcuts=("+connect-link-status",),
            summary=("Read or wait for the authorization result of a social account connect link."),
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_account_connect_link_status",
            input_schema=_social_account_connect_link_status_input_schema(),
            output_schema=_direct_output_schema(
                "Social OAuth connect link status returned by Museon API."
            ),
            examples=[
                "museoncli social-account +get-connect-link --id <connect_link_id>",
                (
                    "museoncli social-account +get-connect-link --id <connect_link_id> "
                    "--wait --timeout 300"
                ),
            ],
            add_arguments=_add_social_account_connect_link_status_arguments,
            build_arguments=_build_social_account_connect_link_status_arguments,
        ),
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+get-performance",
            legacy_shortcuts=("+performance-get",),
            summary=(
                "Live-read performance for one social account: authorized channels "
                "first, with automatic public-data fallback when authorization is "
                "missing/expired or the platform exposes no history. Payload "
                "`source` marks provenance (official/managed analytics vs "
                "public_data) — relay that difference to customers and never show "
                "internal retrieval details. First page includes the profile block; "
                "posts paginate via --cursor."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_account_performance_get",
            input_schema=_social_account_performance_get_input_schema(),
            output_schema=_direct_output_schema(
                "Live account performance payload returned by Museon API."
            ),
            examples=[
                "museoncli social-account +get-performance --id <pool_account_id>",
                (
                    "museoncli social-account +get-performance --id <pool_account_id> "
                    "--period last-7d --cursor <next_cursor>"
                ),
            ],
            add_arguments=_add_social_account_performance_get_arguments,
            build_arguments=_build_social_account_performance_get_arguments,
        ),
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+draft-profile-edit",
            legacy_shortcuts=("+profile-edit-draft",),
            summary="Generate proposed TikTok display name, bio, or avatar drafts for one account.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_account_profile_edit_draft",
            input_schema=_social_account_profile_edit_draft_input_schema(),
            output_schema=_direct_output_schema(
                "Generated profile edit drafts returned by Museon API."
            ),
            examples=[
                (
                    "museoncli social-account +draft-profile-edit --id <pool_account_id> "
                    "--target nickName --target bio --target avatar "
                    "--prompt 'friendly AI meeting assistant'"
                )
            ],
            add_arguments=_add_social_account_profile_edit_draft_arguments,
            build_arguments=_build_social_account_profile_edit_draft_arguments,
        ),
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+submit-profile-edit",
            legacy_shortcuts=("+profile-edit-submit",),
            summary=(
                "Submit a TikTok profile edit task for one account. "
                "Use +get-profile-edit to confirm completion."
            ),
            risk_level="write",
            execution="async_run",
            adapter_tool_name="social_account_profile_edit_submit",
            input_schema=_social_account_profile_edit_submit_input_schema(),
            output_schema=_async_output_schema(
                "Accepted profile edit task returned by Museon API."
            ),
            examples=[
                (
                    "museoncli social-account +submit-profile-edit --id <pool_account_id> "
                    "--nick-name 'Notta AI' --bio 'Meeting notes, summaries, and translations.' --wait"
                ),
                (
                    "museoncli social-account +submit-profile-edit --id <pool_account_id> "
                    "--avatar-url https://example.com/avatar.png"
                ),
            ],
            add_arguments=_add_social_account_profile_edit_submit_arguments,
            build_arguments=_build_social_account_profile_edit_submit_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+bulk-submit-profile-edit",
            legacy_shortcuts=("+profile-edit-batch-submit",),
            summary=(
                "Submit a TikTok profile edit task for multiple accounts in one batch. "
                "Use +get-profile-edit to poll the single task for all account statuses."
            ),
            risk_level="write",
            execution="async_run",
            adapter_tool_name="social_account_profile_edit_batch_submit",
            input_schema=_social_account_profile_edit_batch_submit_input_schema(),
            output_schema=_async_output_schema(
                "Accepted batch profile edit task returned by Museon API."
            ),
            examples=[
                (
                    "museoncli social-account +bulk-submit-profile-edit "
                    '--account-updates \'[{"account_id":"<uuid>","bio":"AI assistant"}]\' '
                    "--update-bio --wait"
                ),
            ],
            add_arguments=_add_social_account_profile_edit_batch_submit_arguments,
            build_arguments=_build_social_account_profile_edit_batch_submit_arguments,
            supports_dry_run=True,
        ),
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+get-profile-edit",
            legacy_shortcuts=("+profile-edit-status",),
            summary="Read execution status for a profile edit task.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_account_profile_edit_status",
            input_schema=_social_account_profile_edit_status_input_schema(),
            output_schema=_direct_output_schema("Profile edit task status returned by Museon API."),
            examples=[
                "museoncli social-account +get-profile-edit --id <task_id>",
            ],
            add_arguments=_add_social_account_profile_edit_status_arguments,
            build_arguments=_build_social_account_profile_edit_status_arguments,
        ),
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+bulk-generate-avatars",
            legacy_shortcuts=("+avatar-generate-batch",),
            summary=(
                "Generate TikTok profile avatar drafts for multiple accounts as one "
                "async task. Poll +get-avatar-generation for per-account avatar URLs, "
                "then feed the succeeded ones into +bulk-submit-profile-edit."
            ),
            risk_level="read",
            execution="async_run",
            adapter_tool_name="social_account_avatar_generate_batch",
            input_schema=_social_account_avatar_generate_batch_input_schema(),
            output_schema=_async_output_schema(
                "Accepted async avatar-draft generation task returned by Museon API."
            ),
            examples=[
                (
                    "museoncli social-account +bulk-generate-avatars "
                    "--id <uuid> --id <uuid> "
                    "--prompt 'friendly late-night chef portrait'"
                ),
            ],
            add_arguments=_add_social_account_avatar_generate_batch_arguments,
            build_arguments=_build_social_account_avatar_generate_batch_arguments,
        ),
        CommandSpec(
            domain=Domain.SOCIAL_ACCOUNT,
            shortcut="+get-avatar-generation",
            legacy_shortcuts=("+avatar-generate-status",),
            summary="Read per-account status and avatar URLs for an avatar-generation task.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_account_avatar_generate_status",
            input_schema=_social_account_avatar_generate_status_input_schema(),
            output_schema=_direct_output_schema(
                "Avatar-generation task status returned by Museon API."
            ),
            examples=[
                "museoncli social-account +get-avatar-generation --id <task_id>",
            ],
            add_arguments=_add_social_account_avatar_generate_status_arguments,
            build_arguments=_build_social_account_avatar_generate_status_arguments,
        ),
    ]


# ---- executors (generated from main.py direct_* chains) ----
async def _execute_connect_link_create(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    payload = dict(arguments)
    turn_context = routine_turn_context(cfg)
    if turn_context:
        payload.setdefault("turn_context", turn_context)
    return agent_domain_result(
        await api_data(
            cfg,
            "POST",
            "/agent-cli/social-auth/connect-links",
            json_body={"workspace_id": workspace_id, "payload": payload},
        )
    )


async def _execute_connect_link_status(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    link_id = str(arguments.get("link_id") or "")
    if not link_id:
        raise RuntimeError("social-account.get-connect-link requires link_id")
    return await _poll_connect_link_status(
        cfg,
        workspace_id=workspace_id,
        link_id=link_id,
        wait=bool(arguments.get("wait")),
        timeout_seconds=int(arguments.get("timeout") or 0),
        poll_interval_seconds=float(arguments.get("poll_interval") or 2.0),
    )


async def _execute_performance_get(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    command_name = ctx.spec.schema_name
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    account_id = str(arguments.get("account_id") or "")
    if not account_id:
        raise RuntimeError(f"{command_name} requires account_id")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/social-accounts/{account_id}/performance",
            params=compact_params(
                {
                    "workspace_id": workspace_id,
                    "period": arguments.get("period"),
                    "cursor": arguments.get("cursor"),
                    "page_size": arguments.get("page_size", 20),
                }
            ),
        )
    )


async def _execute_get(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    command_name = ctx.spec.schema_name
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    account_id = str(arguments.get("account_id") or "")
    if not account_id:
        raise RuntimeError(f"{command_name} requires account_id")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/social-accounts/{account_id}",
        )
    )


async def _execute_adb_connect(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    command_name = ctx.spec.schema_name
    api_data = ctx.api_data
    account_id = str(arguments.get("account_id") or "")
    if account_id:
        if not workspace_id:
            raise RuntimeError("missing_workspace")
        connection = agent_domain_result(
            await api_data(
                cfg,
                "POST",
                f"/agent-cli/social-accounts/{account_id}/adb-credentials",
                params={"workspace_id": workspace_id},
            )
        )
        resolved_account = None
    else:
        handle = str(arguments.get("handle") or "").strip()
        platform = str(arguments.get("platform") or "").strip()
        if not handle or not platform:
            raise RuntimeError(f"{command_name} requires handle and platform")
        body = {"handle": handle, "platform": platform}
        explicit_workspace_id = arguments.get("workspace_id")
        if explicit_workspace_id:
            body["workspace_id"] = explicit_workspace_id
        connection = agent_domain_result(
            await api_data(
                cfg,
                "POST",
                "/agent-cli/social-accounts/adb-credentials",
                json_body=body,
            )
        )
        resolved_account = connection
    if not isinstance(connection, dict):
        raise RuntimeError("invalid_adb_connection_response")
    result = await _connect_adb(connection)
    if isinstance(resolved_account, dict):
        result.update(
            {
                key: resolved_account.get(key)
                for key in ("account_id", "username", "platform", "workspace_id")
            }
        )
    return result


async def _execute_stream_url(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    command_name = ctx.spec.schema_name
    api_data = ctx.api_data
    account_id = str(arguments.get("account_id") or "")
    if not account_id:
        raise RuntimeError(f"{command_name} requires account_id")
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    return agent_domain_result(
        await api_data(
            cfg,
            "POST",
            f"/agent-cli/social-accounts/{account_id}/stream-url",
            params={"workspace_id": workspace_id},
        )
    )


async def _connect_adb(connection: dict[str, Any]) -> dict[str, Any]:
    serial = str(connection.get("serial") or "").strip()
    password = str(connection.get("password") or "").strip()
    if not serial or not password:
        raise RuntimeError("incomplete_adb_connection_response")

    await _run_adb("connect", "connect", serial)
    await _run_adb("glogin", "-s", serial, "shell", "glogin", password)
    state = await _run_adb("get-state", "-s", serial, "get-state")
    if state != "device":
        raise RuntimeError("adb_device_not_ready")
    return {
        "serial": serial,
        "connected": True,
        "next_step": "Use native adb or u2cli with this serial.",
    }


async def _run_adb(operation: str, *arguments: str) -> str:
    """Run one local ADB command without exposing provider credentials in errors."""
    try:
        process = await asyncio.create_subprocess_exec(
            "adb",
            *arguments,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
    except FileNotFoundError as exc:
        raise RuntimeError("adb_not_installed") from exc
    try:
        stdout, _stderr = await asyncio.wait_for(
            process.communicate(), timeout=ADB_COMMAND_TIMEOUT_SECONDS
        )
    except TimeoutError as exc:
        try:
            process.kill()
        except ProcessLookupError:
            pass
        await process.communicate()
        raise RuntimeError(f"adb_{operation}_timed_out") from exc
    if process.returncode != 0:
        raise RuntimeError(f"adb_{operation}_failed")
    return stdout.decode("utf-8", errors="replace").strip()


async def _execute_list(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            "/agent-cli/social-accounts",
            params=compact_params(
                {
                    "workspace_id": workspace_id,
                    "platform": arguments.get("platform"),
                    "search": arguments.get("search"),
                    "search_terms": arguments.get("search_terms"),
                    "automation_status": arguments.get("automation_status"),
                    "allocation_type": arguments.get("allocation_type"),
                    "allocation_status": arguments.get("allocation_status"),
                    "oauth_status": arguments.get("oauth_status"),
                    "issue_type": arguments.get("issue_type"),
                    "performance_levels": arguments.get("performance_levels"),
                    "include_null_level": arguments.get("include_null_level"),
                    "tag": arguments.get("tag"),
                    "group_name": arguments.get("group_name"),
                    "lookup_status": arguments.get("lookup_status"),
                    "is_active": arguments.get("is_active"),
                    "is_public": arguments.get("is_public"),
                    "has_device": arguments.get("has_device"),
                    "page": arguments.get("page", 1),
                    "page_size": arguments.get("page_size", 100),
                }
            ),
        )
    )


async def _execute_profile_edit_draft(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    command_name = ctx.spec.schema_name
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    account_id = str(arguments.get("account_id") or "")
    if not account_id:
        raise RuntimeError(f"{command_name} requires account_id")
    return agent_domain_result(
        await api_data(
            cfg,
            "POST",
            f"/agent-cli/social-accounts/{account_id}/profile-edit/drafts",
            json_body={
                "workspace_id": workspace_id,
                "payload": _dict_argument(arguments, "profile_edit"),
            },
        )
    )


async def _execute_avatar_generate_batch(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    account_ids = arguments.get("account_ids")
    if not isinstance(account_ids, list) or not account_ids:
        raise RuntimeError(
            "social-account.bulk-generate-avatars requires a non-empty account_ids array"
        )
    payload = {
        "account_ids": account_ids,
        "prompt": arguments.get("prompt") or "",
    }
    result = agent_domain_result(
        await api_data(
            cfg,
            "POST",
            "/agent-cli/social-accounts/profile-edit/avatar-drafts",
            json_body={
                "workspace_id": workspace_id,
                "payload": payload,
            },
        )
    )
    if arguments.get("wait"):
        task_id = _profile_edit_task_id(result)
        if task_id:
            status_result = await _poll_avatar_generate_status(
                cfg,
                task_id=task_id,
                timeout_seconds=float(arguments.get("wait_timeout_seconds") or 300.0),
                poll_interval_seconds=float(arguments.get("poll_interval_seconds") or 5.0),
            )
            if isinstance(result, dict):
                result["provider_status"] = status_result
    return result


async def _execute_avatar_generate_status(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    task_id = str(arguments.get("task_id") or "")
    if not task_id:
        raise RuntimeError("social-account.get-avatar-generation requires task_id")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/social-accounts/profile-edit/avatar-drafts/{task_id}",
        )
    )


async def _execute_profile_edit_status(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    task_id = str(arguments.get("task_id") or "")
    if not task_id:
        raise RuntimeError("social-account.get-profile-edit requires task_id")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/social-accounts/profile-edit/tasks/{task_id}",
        )
    )


async def _execute_profile_edit_submit(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    command_name = ctx.spec.schema_name
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    account_id = str(arguments.get("account_id") or "")
    if not account_id:
        raise RuntimeError(f"{command_name} requires account_id")
    result = agent_domain_result(
        await api_data(
            cfg,
            "POST",
            f"/agent-cli/social-accounts/{account_id}/profile-edit/tasks",
            json_body={
                "workspace_id": workspace_id,
                "payload": _dict_argument(arguments, "profile_edit"),
            },
        )
    )
    if arguments.get("wait"):
        task_id = _profile_edit_task_id(result)
        if task_id:
            status_result = await _poll_profile_edit_status(
                cfg,
                task_id=task_id,
                timeout_seconds=float(arguments.get("wait_timeout_seconds") or 300.0),
                poll_interval_seconds=float(arguments.get("poll_interval_seconds") or 5.0),
            )
            if isinstance(result, dict):
                result["provider_status"] = status_result
    return result


async def _execute_profile_edit_batch_submit(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    account_updates = arguments.get("account_updates")
    if not isinstance(account_updates, list) or not account_updates:
        raise RuntimeError(
            "social-account.bulk-submit-profile-edit requires a non-empty account_updates array"
        )
    payload = {
        "account_updates": account_updates,
        "update_nick_name": arguments.get("update_nick_name", False),
        "update_bio": arguments.get("update_bio", False),
        "update_avatar": arguments.get("update_avatar", False),
    }
    avatar_url = arguments.get("avatar_url")
    if avatar_url:
        payload["avatar_url"] = avatar_url
    result = agent_domain_result(
        await api_data(
            cfg,
            "POST",
            "/agent-cli/social-accounts/profile-edit/tasks",
            json_body={
                "workspace_id": workspace_id,
                "payload": payload,
            },
        )
    )
    if arguments.get("wait"):
        task_id = _profile_edit_task_id(result)
        if task_id:
            status_result = await _poll_profile_edit_status(
                cfg,
                task_id=task_id,
                timeout_seconds=float(arguments.get("wait_timeout_seconds") or 300.0),
                poll_interval_seconds=float(arguments.get("poll_interval_seconds") or 5.0),
            )
            if isinstance(result, dict):
                result["provider_status"] = status_result
    return result


EXECUTORS = {
    "social-account.create-connect-link": direct_enveloped(_execute_connect_link_create),
    "social-account.get-connect-link": direct_enveloped(_execute_connect_link_status),
    "social-account.connect-adb": direct_enveloped(_execute_adb_connect),
    "social-account.get-stream-url": direct_enveloped(_execute_stream_url),
    "social-account.get": direct_enveloped(_execute_get),
    "social-account.get-performance": direct_enveloped(_execute_performance_get),
    "social-account.list": direct_enveloped(_execute_list),
    "social-account.bulk-generate-avatars": direct_enveloped(_execute_avatar_generate_batch),
    "social-account.get-avatar-generation": direct_enveloped(_execute_avatar_generate_status),
    "social-account.bulk-submit-profile-edit": direct_enveloped(_execute_profile_edit_batch_submit),
    "social-account.draft-profile-edit": direct_enveloped(_execute_profile_edit_draft),
    "social-account.get-profile-edit": direct_enveloped(_execute_profile_edit_status),
    "social-account.submit-profile-edit": direct_enveloped(_execute_profile_edit_submit),
}


async def _poll_connect_link_status(
    cfg: Config,
    *,
    workspace_id: str,
    link_id: str,
    wait: bool,
    timeout_seconds: int,
    poll_interval_seconds: float,
) -> Any:
    terminal_statuses = {"completed", "expired", "revoked"}
    started_at = asyncio.get_running_loop().time()
    while True:
        result = agent_domain_result(
            await api_data(
                cfg,
                "GET",
                f"/agent-cli/social-auth/connect-links/{link_id}/status",
                params={"workspace_id": workspace_id},
            )
        )
        if not wait or not isinstance(result, dict) or result.get("status") in terminal_statuses:
            return result
        if timeout_seconds <= 0:
            return result
        elapsed = asyncio.get_running_loop().time() - started_at
        if elapsed >= timeout_seconds:
            return {**result, "timed_out": True}
        await asyncio.sleep(min(max(poll_interval_seconds, 0.1), timeout_seconds - elapsed))


async def _poll_avatar_generate_status(
    cfg: Config,
    *,
    task_id: str,
    timeout_seconds: float,
    poll_interval_seconds: float,
) -> Any:
    deadline = time.monotonic() + max(timeout_seconds, 0.0)
    interval = max(poll_interval_seconds, 0.25)
    last_result: Any = None
    while True:
        last_result = agent_domain_result(
            await api_data(
                cfg,
                "GET",
                f"/agent-cli/social-accounts/profile-edit/avatar-drafts/{task_id}",
            )
        )
        if _profile_edit_status_is_settled(last_result):
            return last_result
        if time.monotonic() >= deadline:
            return {
                "timed_out": True,
                "task_id": task_id,
                "last_status": last_result,
            }
        await asyncio.sleep(interval)


async def _poll_profile_edit_status(
    cfg: Config,
    *,
    task_id: str,
    timeout_seconds: float,
    poll_interval_seconds: float,
) -> Any:
    deadline = time.monotonic() + max(timeout_seconds, 0.0)
    interval = max(poll_interval_seconds, 0.25)
    last_result: Any = None
    while True:
        last_result = agent_domain_result(
            await api_data(
                cfg,
                "GET",
                f"/agent-cli/social-accounts/profile-edit/tasks/{task_id}",
            )
        )
        if _profile_edit_status_is_settled(last_result):
            return last_result
        if time.monotonic() >= deadline:
            return {
                "timed_out": True,
                "task_id": task_id,
                "last_status": last_result,
            }
        await asyncio.sleep(interval)


def _profile_edit_status_is_settled(result: Any) -> bool:
    if not isinstance(result, dict):
        return False
    summary = result.get("summary")
    return isinstance(summary, dict) and summary.get("settled") is True
