"""Generated by domains split from domain_commands.py — see docs/museoncli-optimization-plan.md."""

from __future__ import annotations

from museoncli.execution import agent_domain_result, compact_params

from museoncli.execution import (
    CommandContext,
    direct_enveloped,
)

import argparse
from typing import Any
from museoncli.domains._model import CommandSpec, Domain
from museoncli.domains._shared import (
    _add_common_adapter_arguments,
    _direct_output_schema,
    _load_structured_args,
    _without_none,
)


def _add_social_media_creator_get_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", required=True, dest="creator_id")


def _build_social_media_creator_get_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload["creator_id"] = args.creator_id
    return payload


def _add_social_media_post_list_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--creator-id", required=True)
    parser.add_argument("--page", type=int, default=1)
    parser.add_argument("--page-size", type=int, default=20)


def _build_social_media_post_list_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload.update(
        {
            "creator_id": args.creator_id,
            "page": args.page,
            "page_size": args.page_size,
        }
    )
    return payload


def _add_social_media_creator_performance_get_arguments(
    parser: argparse.ArgumentParser,
) -> None:
    _add_social_media_creator_get_arguments(parser)
    parser.add_argument("--date-from")
    parser.add_argument("--date-to")
    parser.add_argument("--limit", type=int, default=100)


def _build_social_media_creator_performance_get_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _build_social_media_creator_get_arguments(args)
    payload.update(
        _without_none(
            {
                "date_from": args.date_from,
                "date_to": args.date_to,
                "limit": args.limit,
            }
        )
    )
    return payload


def _add_social_media_post_get_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--id", required=True, dest="content_id")


def _build_social_media_post_get_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload["content_id"] = args.content_id
    return payload


def _add_social_media_post_performance_get_arguments(parser: argparse.ArgumentParser) -> None:
    _add_social_media_post_get_arguments(parser)
    parser.add_argument("--date-from")
    parser.add_argument("--date-to")
    parser.add_argument("--limit", type=int, default=30)


def _build_social_media_post_performance_get_arguments(
    args: argparse.Namespace,
) -> dict[str, Any]:
    payload = _build_social_media_post_get_arguments(args)
    payload.update(
        _without_none(
            {
                "date_from": args.date_from,
                "date_to": args.date_to,
                "limit": args.limit,
            }
        )
    )
    return payload


def _add_social_media_post_resolve_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_adapter_arguments(parser)
    parser.add_argument("--schedule-item-id", required=True)


def _build_social_media_post_resolve_arguments(args: argparse.Namespace) -> dict[str, Any]:
    payload = _load_structured_args(args)
    payload["schedule_item_id"] = args.schedule_item_id
    return payload


def _social_media_creator_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {"creator_id": {"type": "string", "minLength": 1}},
        "required": ["creator_id"],
    }


def _social_media_post_list_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "creator_id": {"type": "string", "minLength": 1},
            "page": {"type": "integer", "minimum": 1, "default": 1},
            "page_size": {"type": "integer", "minimum": 1, "maximum": 100, "default": 20},
        },
        "required": ["creator_id"],
    }


def _social_media_creator_performance_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "creator_id": {"type": "string", "minLength": 1},
            "date_from": {"type": ["string", "null"]},
            "date_to": {"type": ["string", "null"]},
            "limit": {"type": "integer", "minimum": 1, "maximum": 500, "default": 100},
        },
        "required": ["creator_id"],
    }


def _social_media_post_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {"content_id": {"type": "string", "minLength": 1}},
        "required": ["content_id"],
    }


def _social_media_post_performance_get_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "content_id": {"type": "string", "minLength": 1},
            "date_from": {"type": ["string", "null"]},
            "date_to": {"type": ["string", "null"]},
            "limit": {"type": "integer", "minimum": 1, "maximum": 100, "default": 30},
        },
        "required": ["content_id"],
    }


def _social_media_post_resolve_input_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {"schedule_item_id": {"type": "string", "minLength": 1}},
        "required": ["schedule_item_id"],
    }


def specs() -> list[CommandSpec]:
    return [
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+creator-get",
            summary="Read one workspace-visible social account profile from Museon's store.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_media_creator_get",
            input_schema=_social_media_creator_get_input_schema(),
            output_schema=_direct_output_schema("Creator profile payload returned by Museon API."),
            examples=[
                "museoncli campaign-monitor +creator-get --id <creator_social_account_id>",
            ],
            add_arguments=_add_social_media_creator_get_arguments,
            build_arguments=_build_social_media_creator_get_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+post-list",
            summary=(
                "List Museon-synced posts for one workspace-visible social account; "
                "not a live platform-history fetch."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_media_post_list",
            input_schema=_social_media_post_list_input_schema(),
            output_schema=_direct_output_schema("Post list payload returned by Museon API."),
            examples=[
                (
                    "museoncli campaign-monitor +post-list --creator-id "
                    "<creator_social_account_id> --page-size 20"
                ),
            ],
            add_arguments=_add_social_media_post_list_arguments,
            build_arguments=_build_social_media_post_list_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+creator-performance-get",
            summary=(
                "Read local synced performance history for one workspace-visible social account."
            ),
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_media_creator_performance_get",
            input_schema=_social_media_creator_performance_get_input_schema(),
            output_schema=_direct_output_schema(
                "Creator performance history payload returned by Museon API."
            ),
            examples=[
                (
                    "museoncli campaign-monitor +creator-performance-get "
                    "--id <creator_social_account_id> --date-from 2026-06-01"
                ),
            ],
            add_arguments=_add_social_media_creator_performance_get_arguments,
            build_arguments=_build_social_media_creator_performance_get_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+post-get",
            summary="Read one Museon-synced social post/content record.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_media_post_get",
            input_schema=_social_media_post_get_input_schema(),
            output_schema=_direct_output_schema("Post detail payload returned by Museon API."),
            examples=["museoncli campaign-monitor +post-get --id <content_id>"],
            add_arguments=_add_social_media_post_get_arguments,
            build_arguments=_build_social_media_post_get_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+post-performance-get",
            summary="Read local synced performance history for one social post/content record.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_media_post_performance_get",
            input_schema=_social_media_post_performance_get_input_schema(),
            output_schema=_direct_output_schema(
                "Post performance history payload returned by Museon API."
            ),
            examples=[
                ("museoncli campaign-monitor +post-performance-get --id <content_id> --limit 10"),
            ],
            add_arguments=_add_social_media_post_performance_get_arguments,
            build_arguments=_build_social_media_post_performance_get_arguments,
        ),
        CommandSpec(
            domain=Domain.CAMPAIGN_MONITOR,
            shortcut="+post-resolve",
            summary="Resolve an account publish schedule item to its published social post.",
            risk_level="read",
            execution="direct",
            adapter_tool_name="social_media_post_resolve",
            input_schema=_social_media_post_resolve_input_schema(),
            output_schema=_direct_output_schema(
                "Schedule item to post resolution payload returned by Museon API."
            ),
            examples=[
                ("museoncli campaign-monitor +post-resolve --schedule-item-id <schedule_item_id>"),
            ],
            add_arguments=_add_social_media_post_resolve_arguments,
            build_arguments=_build_social_media_post_resolve_arguments,
        ),
    ]


# ---- executors (generated from main.py direct_* chains) ----
async def _execute_creator_get(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    creator_id = str(arguments.get("creator_id") or "")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/social-media/creators/{creator_id}",
            params={"workspace_id": workspace_id},
        )
    )


async def _execute_creator_performance_get(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    creator_id = str(arguments.get("creator_id") or "")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/social-media/creators/{creator_id}/performance",
            params=compact_params(
                {
                    "workspace_id": workspace_id,
                    "date_from": arguments.get("date_from"),
                    "date_to": arguments.get("date_to"),
                    "limit": arguments.get("limit", 100),
                }
            ),
        )
    )


async def _execute_post_get(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    content_id = str(arguments.get("content_id") or "")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/social-media/posts/{content_id}",
            params={"workspace_id": workspace_id},
        )
    )


async def _execute_post_list(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    creator_id = str(arguments.get("creator_id") or "")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/social-media/creators/{creator_id}/posts",
            params=compact_params(
                {
                    "workspace_id": workspace_id,
                    "page": arguments.get("page", 1),
                    "page_size": arguments.get("page_size", 20),
                }
            ),
        )
    )


async def _execute_post_performance_get(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    content_id = str(arguments.get("content_id") or "")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            f"/agent-cli/social-media/posts/{content_id}/performance",
            params=compact_params(
                {
                    "workspace_id": workspace_id,
                    "date_from": arguments.get("date_from"),
                    "date_to": arguments.get("date_to"),
                    "limit": arguments.get("limit", 30),
                }
            ),
        )
    )


async def _execute_post_resolve(ctx: CommandContext) -> Any:
    cfg = ctx.cfg
    arguments = ctx.arguments
    workspace_id = ctx.workspace_id
    api_data = ctx.api_data
    if not workspace_id:
        raise RuntimeError("missing_workspace")
    schedule_item_id = str(arguments.get("schedule_item_id") or "")
    return agent_domain_result(
        await api_data(
            cfg,
            "GET",
            "/agent-cli/social-media/posts/resolve",
            params={"workspace_id": workspace_id, "schedule_item_id": schedule_item_id},
        )
    )


EXECUTORS = {
    "campaign-monitor.creator-get": direct_enveloped(_execute_creator_get),
    "campaign-monitor.creator-performance-get": direct_enveloped(_execute_creator_performance_get),
    "campaign-monitor.post-get": direct_enveloped(_execute_post_get),
    "campaign-monitor.post-list": direct_enveloped(_execute_post_list),
    "campaign-monitor.post-performance-get": direct_enveloped(_execute_post_performance_get),
    "campaign-monitor.post-resolve": direct_enveloped(_execute_post_resolve),
}
